extends Node

#objects
var bricks = load('res://objects/bricks/bricks.tscn') # DONE
#var credits1 = load('res://objects/credits1/credits1.tscn')
#var credits2 = load('res://objects/credits2/credits2.tscn')
#var curs_obj = load('res://objects/curs_obj/curs_obj.tscn')
#var end = load('res://objects/end/end.tscn')
#var end2 = load('res://objects/end2/end2.tscn')
#var end3 = load('res://objects/end3/end3.tscn')
#var end_custom = load('res://objects/end_custom/end_custom.tscn')
#var final_boss = load('res://objects/final_boss/final_boss.tscn')
var game = load('res://objects/game/game.tscn') # DONE
var gamepad = load('res://objects/gamepad/gamepad.tscn') # DONE
var globals = load('res://objects/globals/globals.tscn') # DONE
#var highscores = load('res://objects/highscores/highscores.tscn')
var intro = load('res://objects/intro/intro.tscn') # DONE
#var joy_config = load('res://objects/joy_config/joy_config.tscn')
#var key_config = load('res://objects/key_config/key_config.tscn')
#var level = load('res://objects/level/level.tscn')
#var level_editor = load('res://objects/level_editor/level_editor.tscn')
#var load_level = load('res://objects/load_level/load_level.tscn')
#var moon_room = load('res://objects/moon_room/moon_room.tscn')
var music = load('res://objects/music/music.tscn') # DONE
var player1 = load('res://objects/player1/player1.tscn') # PROGRESS (need to implemention collision_with_blood)
var room = load('res://objects/room/room.tscn') # DONE
var screen = load('res://objects/screen/screen.tscn') # PROGRESS (need to finish begin step)
#var sprite = load('res://objects/sprite/sprite.tscn')
#var stars_room = load('res://objects/stars_room/stars_room.tscn')
#var sun_room = load('res://objects/sun_room/sun_room.tscn')
var title = load('res://objects/title/title.tscn') # DONE
#var transition = load('res://objects/transition/transition.tscn')


#basis
#var backdrop = load('res://objects/basis/backdrop/backdrop.tscn')
var character = load('res://objects/basis/character/character.tscn') # DONE
#var detritus = load('res://objects/basis/detritus/detritus.tscn')
#var drawn_sprite = load('res://objects/basis/drawn_sprite/drawn_sprite.tscn')
#var enemy = load('res://objects/basis/enemy/enemy.tscn')
#var foreground = load('res://objects/basis/foreground/foreground.tscn')
var frill = load('res://objects/basis/frill/frill.tscn') # DONE
var item = load('res://objects/basis/item/item.tscn') # PROGRESS
var ladder = load('res://objects/basis/ladder/ladder.tscn') # DONE
var menu = load('res://objects/basis/menu/menu.tscn') # DONE
#var moveable_solid = load('res://objects/basis/moveable_solid/moveable_solid.tscn')
#var moving_solid = load('res://objects/basis/moving_solid/moving_solid.tscn')
var platform = load('res://objects/basis/platform/platform.tscn') # DONE
#var rubble_piece = load('res://objects/basis/rubble_piece/rubble_piece.tscn')
#var solid = load('res://objects/basis/solid/solid.tscn')
#var treasure = load('res://objects/basis/treasure/treasure.tscn')
#var water = load('res://objects/basis/water/water.tscn')


#blocks
#var alien_ship = load('res://objects/blocks/alien_ship/alien_ship.tscn')
#var alien_ship_floor = load('res://objects/blocks/alien_ship_floor/alien_ship_floor.tscn')
#var altar_left = load('res://objects/blocks/altar_left/altar_left.tscn')
#var altar_right = load('res://objects/blocks/altar_right/altar_right.tscn')
var black_fade_up = load('res://objects/blocks/black_fade_up/black_fade_up.tscn') # DONE
#var block = load('res://objects/blocks/block/block.tscn')
var brick = load('res://objects/blocks/brick/brick.tscn') # DONE
var brick_smooth = load('res://objects/blocks/brick_smooth/brick_smooth.tscn') # PROGRESS
#var cave_bg = load('res://objects/blocks/cave_bg/cave_bg.tscn')
var cave_bg2 = load('res://objects/blocks/cave_bg2/cave_bg2.tscn') # DONE
var cave_bg_entrance = load('res://objects/blocks/cave_bg_entrance/cave_bg_entrance.tscn') # DONE
var dark = load('res://objects/blocks/dark/dark.tscn') # DONE
#var dark_fall = load('res://objects/blocks/dark_fall/dark_fall.tscn')
#var entrance = load('res://objects/blocks/entrance/entrance.tscn')
#var exit = load('res://objects/blocks/exit/exit.tscn')
#var frozen_caveman = load('res://objects/blocks/frozen_caveman/frozen_caveman.tscn')
#var gold = load('res://objects/blocks/gold/gold.tscn')
#var gold_big = load('res://objects/blocks/gold_big/gold_big.tscn')
#var gold_door = load('res://objects/blocks/gold_door/gold_door.tscn')
#var grave = load('res://objects/blocks/grave/grave.tscn')
var hard_block = load('res://objects/blocks/hard_block/hard_block.tscn') # DONE
#var ice = load('res://objects/blocks/ice/ice.tscn')
#var ice_block = load('res://objects/blocks/ice_block/ice_block.tscn')
#var ice_bottom = load('res://objects/blocks/ice_bottom/ice_bottom.tscn')
#var kali_head = load('res://objects/blocks/kali_head/kali_head.tscn')
var ladder_orange = load('res://objects/blocks/ladder_orange/ladder_orange.tscn')  # DONE
var ladder_top = load('res://objects/blocks/ladder_top/ladder_top.tscn')  # DONE
#var lamp = load('res://objects/blocks/lamp/lamp.tscn')
#var lamp_red = load('res://objects/blocks/lamp_red/lamp_red.tscn')
#var lava = load('res://objects/blocks/lava/lava.tscn')
#var lava_solid = load('res://objects/blocks/lava_solid/lava_solid.tscn')
#var leaves = load('res://objects/blocks/leaves/leaves.tscn')
#var leaves_tile = load('res://objects/blocks/leaves_tile/leaves_tile.tscn')
#var lush = load('res://objects/blocks/lush/lush.tscn')
#var moai = load('res://objects/blocks/moai/moai.tscn')
#var moai2 = load('res://objects/blocks/moai2/moai2.tscn')
#var moai3 = load('res://objects/blocks/moai3/moai3.tscn')
#var moai_inside = load('res://objects/blocks/moai_inside/moai_inside.tscn')
#var msg_sign = load('res://objects/blocks/msg_sign/msg_sign.tscn')
#var push_block = load('res://objects/blocks/push_block/push_block.tscn')
#var sac_altar_left = load('res://objects/blocks/sac_altar_left/sac_altar_left.tscn')
var sac_altar_right = load('res://objects/blocks/sac_altar_right/sac_altar_right.tscn')  # DONE
#var sign = load('res://objects/blocks/sign/sign.tscn')
#var splash = load('res://objects/blocks/splash/splash.tscn')
#var temple = load('res://objects/blocks/temple/temple.tscn')
#var temple_fake = load('res://objects/blocks/temple_fake/temple_fake.tscn')
#var thin_ice = load('res://objects/blocks/thin_ice/thin_ice.tscn')
#var tiki_torch = load('res://objects/blocks/tiki_torch/tiki_torch.tscn')
#var tree = load('res://objects/blocks/tree/tree.tscn')
#var tree_branch = load('res://objects/blocks/tree_branch/tree_branch.tscn')
#var tree_branch_tile = load('res://objects/blocks/tree_branch_tile/tree_branch_tile.tscn')
#var tree_tile = load('res://objects/blocks/tree_tile/tree_tile.tscn')
var vine = load('res://objects/blocks/vine/vine.tscn')  # DONE
var vine_top = load('res://objects/blocks/vine_top/vine_top.tscn')  # DONE
#var water_swim = load('res://objects/blocks/water_swim/water_swim.tscn')
var x_gold = load('res://objects/blocks/x_gold/x_gold.tscn')  # DONE
#var x_market = load('res://objects/blocks/x_market/x_market.tscn')
#var xoc_block = load('res://objects/blocks/xoc_block/xoc_block.tscn')


#characters
#var damsel = load('res://objects/characters/damsel/damsel.tscn')
#var damsel_kiss = load('res://objects/characters/damsel_kiss/damsel_kiss.tscn')
#var shopkeeper = load('res://objects/characters/shopkeeper/shopkeeper.tscn')
#var shopkeeper2 = load('res://objects/characters/shopkeeper2/shopkeeper2.tscn')
var tunnel_man = load('res://objects/characters/tunnel_man/tunnel_man.tscn') # DONE
#var yell_help = load('res://objects/characters/yell_help/yell_help.tscn')


#collectibles
#var ankh = load('res://objects/collectibles/ankh/ankh.tscn')
#var bomb_bag = load('res://objects/collectibles/bomb_bag/bomb_bag.tscn')
#var bomb_box = load('res://objects/collectibles/bomb_box/bomb_box.tscn')
#var bones = load('res://objects/collectibles/bones/bones.tscn')
#var cape = load('res://objects/collectibles/cape/cape.tscn')
#var cape_pickup = load('res://objects/collectibles/cape_pickup/cape_pickup.tscn')
#var chest = load('res://objects/collectibles/chest/chest.tscn')
#var compass = load('res://objects/collectibles/compass/compass.tscn')
#var crate = load('res://objects/collectibles/crate/crate.tscn')
#var crown = load('res://objects/collectibles/crown/crown.tscn')
#var diamond = load('res://objects/collectibles/diamond/diamond.tscn')
#var emerald = load('res://objects/collectibles/emerald/emerald.tscn')
#var emerald_big = load('res://objects/collectibles/emerald_big/emerald_big.tscn')
#var fake_bones = load('res://objects/collectibles/fake_bones/fake_bones.tscn')
#var fire_frog_armed = load('res://objects/collectibles/fire_frog_armed/fire_frog_armed.tscn')
#var flare_crate = load('res://objects/collectibles/flare_crate/flare_crate.tscn')
#var gloves = load('res://objects/collectibles/gloves/gloves.tscn')
#var gold_bar = load('res://objects/collectibles/gold_bar/gold_bar.tscn')
#var gold_bars = load('res://objects/collectibles/gold_bars/gold_bars.tscn')
#var gold_chunk = load('res://objects/collectibles/gold_chunk/gold_chunk.tscn')
#var gold_nugget = load('res://objects/collectibles/gold_nugget/gold_nugget.tscn')
#var jetpack = load('res://objects/collectibles/jetpack/jetpack.tscn')
#var jordans = load('res://objects/collectibles/jordans/jordans.tscn')
#var kapala = load('res://objects/collectibles/kapala/kapala.tscn')
#var key = load('res://objects/collectibles/key/key.tscn')
#var locked_chest = load('res://objects/collectibles/locked_chest/locked_chest.tscn')
#var mitt = load('res://objects/collectibles/mitt/mitt.tscn')
#var para_pickup = load('res://objects/collectibles/para_pickup/para_pickup.tscn')
#var para_used = load('res://objects/collectibles/para_used/para_used.tscn')
#var paste = load('res://objects/collectibles/paste/paste.tscn')
#var rope_bag = load('res://objects/collectibles/rope_bag/rope_bag.tscn')
#var rope_pile = load('res://objects/collectibles/rope_pile/rope_pile.tscn')
#var ruby = load('res://objects/collectibles/ruby/ruby.tscn')
#var ruby_big = load('res://objects/collectibles/ruby_big/ruby_big.tscn')
#var sapphire = load('res://objects/collectibles/sapphire/sapphire.tscn')
#var sapphire_big = load('res://objects/collectibles/sapphire_big/sapphire_big.tscn')
#var spectacles = load('res://objects/collectibles/spectacles/spectacles.tscn')
#var spike_shoes = load('res://objects/collectibles/spike_shoes/spike_shoes.tscn')
#var spring_shoes = load('res://objects/collectibles/spring_shoes/spring_shoes.tscn')
#var udjat_eye = load('res://objects/collectibles/udjat_eye/udjat_eye.tscn')


#effects
#var big_collect = load('res://objects/effects/big_collect/big_collect.tscn')
#var blood = load('res://objects/effects/blood/blood.tscn')
#var blood_spark = load('res://objects/effects/blood_spark/blood_spark.tscn')
#var blood_trail = load('res://objects/effects/blood_trail/blood_trail.tscn')
#var bone = load('res://objects/effects/bone/bone.tscn')
#var bubble = load('res://objects/effects/bubble/bubble.tscn')
#var bullet = load('res://objects/effects/bullet/bullet.tscn')
#var burn = load('res://objects/effects/burn/burn.tscn')
#var drip = load('res://objects/effects/drip/drip.tscn')
#var explosion = load('res://objects/effects/explosion/explosion.tscn')
#var flame = load('res://objects/effects/flame/flame.tscn')
#var flame_trail = load('res://objects/effects/flame_trail/flame_trail.tscn')
var flare_spark = load('res://objects/effects/flare_spark/flare_spark.tscn') # PROGRESS (fix animation)
#var fly = load('res://objects/effects/fly/fly.tscn')
#var heart = load('res://objects/effects/heart/heart.tscn')
#var items_get = load('res://objects/effects/items_get/items_get.tscn')
#var laser = load('res://objects/effects/laser/laser.tscn')
#var laser_explode = load('res://objects/effects/laser_explode/laser_explode.tscn')
#var laser_trail = load('res://objects/effects/laser_trail/laser_trail.tscn')
#var lava_drip = load('res://objects/effects/lava_drip/lava_drip.tscn')
#var leaf = load('res://objects/effects/leaf/leaf.tscn')
var poof = load('res://objects/effects/poof/poof.tscn') # DONE
#var psychic_create = load('res://objects/effects/psychic_create/psychic_create.tscn')
#var psychic_create2 = load('res://objects/effects/psychic_create2/psychic_create2.tscn')
#var psychic_create_p = load('res://objects/effects/psychic_create_p/psychic_create_p.tscn')
#var psychic_wave = load('res://objects/effects/psychic_wave/psychic_wave.tscn')
#var psychic_wave_p = load('res://objects/effects/psychic_wave_p/psychic_wave_p.tscn')
#var rope_burn = load('res://objects/effects/rope_burn/rope_burn.tscn')
var rubble = load('res://objects/effects/rubble/rubble.tscn')  # DONE
#var rubble_dark = load('res://objects/effects/rubble_dark/rubble_dark.tscn')
#var rubble_dark_small = load('res://objects/effects/rubble_dark_small/rubble_dark_small.tscn')
var rubble_small = load('res://objects/effects/rubble_small/rubble_small.tscn')  # DONE
#var shotgun_blast_left = load('res://objects/effects/shotgun_blast_left/shotgun_blast_left.tscn')
#var shotgun_blast_right = load('res://objects/effects/shotgun_blast_right/shotgun_blast_right.tscn')
#var small_collect = load('res://objects/effects/small_collect/small_collect.tscn')
#var smoke_puff = load('res://objects/effects/smoke_puff/smoke_puff.tscn')
#var volcano_flame = load('res://objects/effects/volcano_flame/volcano_flame.tscn')
#var web = load('res://objects/effects/web/web.tscn')
#var web_ball = load('res://objects/effects/web_ball/web_ball.tscn')
#var yellow_ball = load('res://objects/effects/yellow_ball/yellow_ball.tscn')
#var yellow_trail = load('res://objects/effects/yellow_trail/yellow_trail.tscn')


#enemies
#var alien = load('res://objects/enemies/alien/alien.tscn')
#var alien_boss = load('res://objects/enemies/alien_boss/alien_boss.tscn')
#var alien_eject = load('res://objects/enemies/alien_eject/alien_eject.tscn')
#var barrier = load('res://objects/enemies/barrier/barrier.tscn')
#var barrier_emitter = load('res://objects/enemies/barrier_emitter/barrier_emitter.tscn')
#var bat = load('res://objects/enemies/bat/bat.tscn')
#var caveman = load('res://objects/enemies/caveman/caveman.tscn')
#var caveman_worship = load('res://objects/enemies/caveman_worship/caveman_worship.tscn')
#var dead_fish = load('res://objects/enemies/dead_fish/dead_fish.tscn')
#var enemy_sight = load('res://objects/enemies/enemy_sight/enemy_sight.tscn')
#var entrance_check = load('res://objects/enemies/entrance_check/entrance_check.tscn')
#var fire_frog = load('res://objects/enemies/fire_frog/fire_frog.tscn')
#var frog = load('res://objects/enemies/frog/frog.tscn')
#var ghost = load('res://objects/enemies/ghost/ghost.tscn')
#var giant_spider = load('res://objects/enemies/giant_spider/giant_spider.tscn')
#var giant_spider_hang = load('res://objects/enemies/giant_spider_hang/giant_spider_hang.tscn')
#var hawkman = load('res://objects/enemies/hawkman/hawkman.tscn')
var hawkman_worship = load('res://objects/enemies/hawkman_worship/hawkman_worship.tscn')  # DONE
#var jaws = load('res://objects/enemies/jaws/jaws.tscn')
#var magma = load('res://objects/enemies/magma/magma.tscn')
#var magma_man = load('res://objects/enemies/magma_man/magma_man.tscn')
#var magma_trail = load('res://objects/enemies/magma_trail/magma_trail.tscn')
#var man_trap = load('res://objects/enemies/man_trap/man_trap.tscn')
#var monkey = load('res://objects/enemies/monkey/monkey.tscn')
#var olmec = load('res://objects/enemies/olmec/olmec.tscn')
#var olmec_debris = load('res://objects/enemies/olmec_debris/olmec_debris.tscn')
#var olmec_slam = load('res://objects/enemies/olmec_slam/olmec_slam.tscn')
#var piranha = load('res://objects/enemies/piranha/piranha.tscn')
#var scarab = load('res://objects/enemies/scarab/scarab.tscn')
#var skeleton = load('res://objects/enemies/skeleton/skeleton.tscn')
#var snake = load('res://objects/enemies/snake/snake.tscn')
#var spider = load('res://objects/enemies/spider/spider.tscn')
#var spider_hang = load('res://objects/enemies/spider_hang/spider_hang.tscn')
#var tomb_lord = load('res://objects/enemies/tomb_lord/tomb_lord.tscn')
#var ufo = load('res://objects/enemies/ufo/ufo.tscn')
#var ufo_crash = load('res://objects/enemies/ufo_crash/ufo_crash.tscn')
#var vampire = load('res://objects/enemies/vampire/vampire.tscn')
#var yeti = load('res://objects/enemies/yeti/yeti.tscn')
#var yeti_king = load('res://objects/enemies/yeti_king/yeti_king.tscn')
#var zombie = load('res://objects/enemies/zombie/zombie.tscn')


#init
#var check_box = load('res://objects/init/check_box/check_box.tscn')
#var check_box2 = load('res://objects/init/check_box2/check_box2.tscn')
#var check_box3 = load('res://objects/init/check_box3/check_box3.tscn')
#var check_box4 = load('res://objects/init/check_box4/check_box4.tscn')
#var joy_config_button = load('res://objects/init/joy_config_button/joy_config_button.tscn')
#var key_config_button = load('res://objects/init/key_config_button/key_config_button.tscn')
#var ok_button = load('res://objects/init/ok_button/ok_button.tscn')
#var radio_box = load('res://objects/init/radio_box/radio_box.tscn')
#var slider1 = load('res://objects/init/slider1/slider1.tscn')
#var slider2 = load('res://objects/init/slider2/slider2.tscn')
var slider_bg = load('res://objects/init/slider_bg/slider_bg.tscn')  # DONE


#items
#var arrow = load('res://objects/items/arrow/arrow.tscn')
#var ball = load('res://objects/items/ball/ball.tscn')
#var ball2 = load('res://objects/items/ball2/ball2.tscn')
#var basketball = load('res://objects/items/basketball/basketball.tscn')
#var bomb = load('res://objects/items/bomb/bomb.tscn')
#var bow = load('res://objects/items/bow/bow.tscn')
#var chain = load('res://objects/items/chain/chain.tscn')
#var chain2 = load('res://objects/items/chain2/chain2.tscn')
#var crystal_skull = load('res://objects/items/crystal_skull/crystal_skull.tscn')
#var dice = load('res://objects/items/dice/dice.tscn')
#var fire_frog_bomb = load('res://objects/items/fire_frog_bomb/fire_frog_bomb.tscn')
#var fish_bone = load('res://objects/items/fish_bone/fish_bone.tscn')
var flare = load('res://objects/items/flare/flare.tscn') # PROGRESS (fixed flare_spark spawning)
#var gold_idol = load('res://objects/items/gold_idol/gold_idol.tscn')
#var jar = load('res://objects/items/jar/jar.tscn')
#var lamp_item = load('res://objects/items/lamp_item/lamp_item.tscn')
#var lamp_red_item = load('res://objects/items/lamp_red_item/lamp_red_item.tscn')
#var machete = load('res://objects/items/machete/machete.tscn')
#var machete_pre = load('res://objects/items/machete_pre/machete_pre.tscn')
#var mattock = load('res://objects/items/mattock/mattock.tscn')
#var mattock_head = load('res://objects/items/mattock_head/mattock_head.tscn')
#var mattock_hit = load('res://objects/items/mattock_hit/mattock_hit.tscn')
#var mattock_pre = load('res://objects/items/mattock_pre/mattock_pre.tscn')
#var parachute = load('res://objects/items/parachute/parachute.tscn')
#var pistol = load('res://objects/items/pistol/pistol.tscn')
#var rock = load('res://objects/items/rock/rock.tscn')
var rope = load('res://objects/items/rope/rope.tscn') # PROGRESS (step seems to not be finished. may have been rope climbing bug I had before, so double check)
var rope_throw = load('res://objects/items/rope_throw/rope_throw.tscn') # PROGESS (step seems to not be finished)
var rope_top = load('res://objects/items/rope_top/rope_top.tscn') # DONE
#var sceptre = load('res://objects/items/sceptre/sceptre.tscn')
#var shotgun = load('res://objects/items/shotgun/shotgun.tscn')
#var skull = load('res://objects/items/skull/skull.tscn')
#var slash = load('res://objects/items/slash/slash.tscn')
#var teleporter = load('res://objects/items/teleporter/teleporter.tscn')
#var web_cannon = load('res://objects/items/web_cannon/web_cannon.tscn')
var whip = load('res://objects/items/whip/whip.tscn') # DONE
var whip_pre = load('res://objects/items/whip_pre/whip_pre.tscn') # DONE


#level editor
#var alien_boss_tile = load('res://objects/level editor/alien_boss_tile/alien_boss_tile.tscn')
#var alien_tile = load('res://objects/level editor/alien_tile/alien_tile.tscn')
var bat_tile = load('res://objects/level editor/bat_tile/bat_tile.tscn')  # DONE
#var bomb_bag_tile = load('res://objects/level editor/bomb_bag_tile/bomb_bag_tile.tscn') # DONE
var bomb_box_tile = load('res://objects/level editor/bomb_box_tile/bomb_box_tile.tscn') # DONE
var bomb_paste_tile = load('res://objects/level editor/bomb_paste_tile/bomb_paste_tile.tscn') # DONE
var bones_tile = load('res://objects/level editor/bones_tile/bones_tile.tscn') # DONE
var bow_tile = load('res://objects/level editor/bow_tile/bow_tile.tscn') # DONE
var cape_tile = load('res://objects/level editor/cape_tile/cape_tile.tscn') # DONE
var caveman_tile = load('res://objects/level editor/caveman_tile/caveman_tile.tscn') # DONE
var chest_tile = load('res://objects/level editor/chest_tile/chest_tile.tscn') # DONE
var compass_tile = load('res://objects/level editor/compass_tile/compass_tile.tscn') # DONE
var crate_tile = load('res://objects/level editor/crate_tile/crate_tile.tscn') # DONE
var crystal_skull_tile = load('res://objects/level editor/crystal_skull_tile/crystal_skull_tile.tscn') # DONE
var damsel_tile = load('res://objects/level editor/damsel_tile/damsel_tile.tscn') # DONE
var diamond_tile = load('res://objects/level editor/diamond_tile/diamond_tile.tscn') # DONE
#var edit_button = load('res://objects/level editor/edit_button/edit_button.tscn')
var emerald_big_tile = load('res://objects/level editor/emerald_big_tile/emerald_big_tile.tscn') # DONE
#var fire_frog_tile = load('res://objects/level editor/fire_frog_tile/fire_frog_tile.tscn')
#var frog_tile = load('res://objects/level editor/frog_tile/frog_tile.tscn')
#var giant_spider_tile = load('res://objects/level editor/giant_spider_tile/giant_spider_tile.tscn')
var gloves_tile = load('res://objects/level editor/gloves_tile/gloves_tile.tscn') # DONE
var gold_bars_tile = load('res://objects/level editor/gold_bars_tile/gold_bars_tile.tscn') # DONE
var gold_bar_tile = load('res://objects/level editor/gold_bar_tile/gold_bar_tile.tscn') # DONE
var gold_idol_tile = load('res://objects/level editor/gold_idol_tile/gold_idol_tile.tscn') # DONE
var hawkman_tile = load('res://objects/level editor/hawkman_tile/hawkman_tile.tscn') # DONE
var ice_tile = load('res://objects/level editor/ice_tile/ice_tile.tscn') # DONE
var jar_tile = load('res://objects/level editor/jar_tile/jar_tile.tscn') # DONE
var jetpack_tile = load('res://objects/level editor/jetpack_tile/jetpack_tile.tscn') # DONE
var lava_tile = load('res://objects/level editor/lava_tile/lava_tile.tscn') # DONE
#var load_button = load('res://objects/level editor/load_button/load_button.tscn')
var machete_tile = load('res://objects/level editor/machete_tile/machete_tile.tscn') # DONE
#var man_trap_tile = load('res://objects/level editor/man_trap_tile/man_trap_tile.tscn')
var mattock_tile = load('res://objects/level editor/mattock_tile/mattock_tile.tscn') # DONE
#var mega_mouth_tile = load('res://objects/level editor/mega_mouth_tile/mega_mouth_tile.tscn')
var mitt_tile = load('res://objects/level editor/mitt_tile/mitt_tile.tscn') # DONE
var monkey_tile = load('res://objects/level editor/monkey_tile/monkey_tile.tscn') # DONE
#var new_button = load('res://objects/level editor/new_button/new_button.tscn')
var parachute_tile = load('res://objects/level editor/parachute_tile/parachute_tile.tscn') # DONE
var piranha_tile = load('res://objects/level editor/piranha_tile/piranha_tile.tscn') # DONE
var pistol_tile = load('res://objects/level editor/pistol_tile/pistol_tile.tscn') # DONE
var rock_tile = load('res://objects/level editor/rock_tile/rock_tile.tscn') # DONE
var rope_pile_tile = load('res://objects/level editor/rope_pile_tile/rope_pile_tile.tscn') # DONE
var ruby_big_tile = load('res://objects/level editor/ruby_big_tile/ruby_big_tile.tscn') # DONE
var sapphire_big_tile = load('res://objects/level editor/sapphire_big_tile/sapphire_big_tile.tscn') # DONE
var shopkeeper_tile = load('res://objects/level editor/shopkeeper_tile/shopkeeper_tile.tscn') # DONE
var shotgun_tile = load('res://objects/level editor/shotgun_tile/shotgun_tile.tscn') # DONE
var skeleton_tile = load('res://objects/level editor/skeleton_tile/skeleton_tile.tscn') # DONE
var smash_trap_tile = load('res://objects/level editor/smash_trap_tile/smash_trap_tile.tscn') # DONE
var snake_tile = load('res://objects/level editor/snake_tile/snake_tile.tscn') # DONE
var spear_trap_tile_bot = load('res://objects/level editor/spear_trap_tile_bot/spear_trap_tile_bot.tscn') # DONE
var spear_trap_tile_top = load('res://objects/level editor/spear_trap_tile_top/spear_trap_tile_top.tscn') # DONE
var spectacles_tile = load('res://objects/level editor/spectacles_tile/spectacles_tile.tscn') # DONE
var spider_tile = load('res://objects/level editor/spider_tile/spider_tile.tscn') # DONE
var spike_shoes_tile = load('res://objects/level editor/spike_shoes_tile/spike_shoes_tile.tscn') # DONE
var spring_shoes_tile = load('res://objects/level editor/spring_shoes_tile/spring_shoes_tile.tscn') # DONE
var spring_trap_tile = load('res://objects/level editor/spring_trap_tile/spring_trap_tile.tscn') # DONE
var teleporter_tile = load('res://objects/level editor/teleporter_tile/teleporter_tile.tscn') # DONE
#var test_button = load('res://objects/level editor/test_button/test_button.tscn')
#var tomb_lord_tile = load('res://objects/level editor/tomb_lord_tile/tomb_lord_tile.tscn')
#var ufo_tile = load('res://objects/level editor/ufo_tile/ufo_tile.tscn')
#var vampire_tile = load('res://objects/level editor/vampire_tile/vampire_tile.tscn')
var water_tile = load('res://objects/level editor/water_tile/water_tile.tscn') # DONE
var web_cannon_tile = load('res://objects/level editor/web_cannon_tile/web_cannon_tile.tscn') # DONE
var web_tile = load('res://objects/level editor/web_tile/web_tile.tscn') # DONE
#var yeti_king_tile = load('res://objects/level editor/yeti_king_tile/yeti_king_tile.tscn')
var yeti_tile = load('res://objects/level editor/yeti_tile/yeti_tile.tscn') # DONE
#var zombie_tile = load('res://objects/level editor/zombie_tile/zombie_tile.tscn')


#other
var black = load('res://objects/other/black/black.tscn') # DONE
var black_bg = load('res://objects/other/black_bg/black_bg.tscn') # DONE
var cave_up = load('res://objects/other/cave_up/cave_up.tscn') # DONE
var hint_hand = load('res://objects/other/hint_hand/hint_hand.tscn') # DONE
var menu_bottom = load('res://objects/other/menu_bottom/menu_bottom.tscn') # DONE
var menu_left = load('res://objects/other/menu_left/menu_left.tscn') # DONE
var menu_ll = load('res://objects/other/menu_ll/menu_ll.tscn') # DONE
var menu_lr = load('res://objects/other/menu_lr/menu_lr.tscn') # DONE
var menu_right = load('res://objects/other/menu_right/menu_right.tscn') # DONE
#var menu_sel = load('res://objects/other/menu_sel/menu_sel.tscn')
var menu_top = load('res://objects/other/menu_top/menu_top.tscn') # DONE
var menu_ul = load('res://objects/other/menu_ul/menu_ul.tscn') # DONE
var menu_ur = load('res://objects/other/menu_ur/menu_ur.tscn')
#var page_down = load('res://objects/other/page_down/page_down.tscn')
#var page_up = load('res://objects/other/page_up/page_up.tscn')
#var p_dummy = load('res://objects/other/p_dummy/p_dummy.tscn')
#var p_dummy2 = load('res://objects/other/p_dummy2/p_dummy2.tscn')
var p_dummy3 = load('res://objects/other/p_dummy3/p_dummy3.tscn') # DONE (check for leftover test stuff)
var p_dummy4 = load('res://objects/other/p_dummy4/p_dummy4.tscn') # DONE
#var p_dummy5 = load('res://objects/other/p_dummy5/p_dummy5.tscn')
#var p_dummy6 = load('res://objects/other/p_dummy6/p_dummy6.tscn')
#var wal_damsel = load('res://objects/other/wal_damsel/wal_damsel.tscn')


#other\end
#var bg_end3 = load('res://objects/other/end/bg_end3/bg_end3.tscn')
var big_chest = load('res://objects/other/end/big_chest/big_chest.tscn') # DONE
#var big_treasure = load('res://objects/other/end/big_treasure/big_treasure.tscn')
var end2_bg = load('res://objects/other/end/end2_bg/end2_bg.tscn') # DONE
#var end_plat = load('res://objects/other/end/end_plat/end_plat.tscn')
var end_wall = load('res://objects/other/end/end_wall/end_wall.tscn') # DONE
#var lava_spray = load('res://objects/other/end/lava_spray/lava_spray.tscn')
#var player_sil = load('res://objects/other/end/player_sil/player_sil.tscn')
#var treasure_sil = load('res://objects/other/end/treasure_sil/treasure_sil.tscn')


#other\intro
var bat_intro = load('res://objects/other/intro/bat_intro/bat_intro.tscn') # DONE (might need to check speed value?)
#var camel = load('res://objects/other/intro/camel/camel.tscn')
#var caravan = load('res://objects/other/intro/caravan/caravan.tscn')
var desert = load('res://objects/other/intro/desert/desert.tscn') # DONE
var desert2 = load('res://objects/other/intro/desert2/desert2.tscn') # DONE
#var desert_scroll = load('res://objects/other/intro/desert_scroll/desert_scroll.tscn')
#var desert_scroll2 = load('res://objects/other/intro/desert_scroll2/desert_scroll2.tscn')
var desert_top = load('res://objects/other/intro/desert_top/desert_top.tscn') # DONE
#var desert_top_scroll = load('res://objects/other/intro/desert_top_scroll/desert_top_scroll.tscn')
var intro_bg = load('res://objects/other/intro/intro_bg/intro_bg.tscn') # DONE
var moon = load('res://objects/other/intro/moon/moon.tscn') # DONE
var palm_tree = load('res://objects/other/intro/palm_tree/palm_tree.tscn') # DONE
var palm_tree_dark = load('res://objects/other/intro/palm_tree_dark/palm_tree_dark.tscn') # DONE
#var palm_tree_scroll = load('res://objects/other/intro/palm_tree_scroll/palm_tree_scroll.tscn')
var shrub = load('res://objects/other/intro/shrub/shrub.tscn') # DONE
var shrub_dark = load('res://objects/other/intro/shrub_dark/shrub_dark.tscn') # DONE
#var shrub_scroll = load('res://objects/other/intro/shrub_scroll/shrub_scroll.tscn')


#other\title
#var basket = load('res://objects/other/title/basket/basket.tscn')
#var bat_target = load('res://objects/other/title/bat_target/bat_target.tscn')
#var button_highscore = load('res://objects/other/title/button_highscore/button_highscore.tscn')
var copy = load('res://objects/other/title/copy/copy.tscn') # DONE
var level13_sign = load('res://objects/other/title/level13_sign/level13_sign.tscn') # DONE
var level5_sign = load('res://objects/other/title/level5_sign/level5_sign.tscn') # DONE
var level9_sign = load('res://objects/other/title/level9_sign/level9_sign.tscn') # DONE
var multi_trophy = load('res://objects/other/title/multi_trophy/multi_trophy.tscn') # DONE
var new = load('res://objects/other/title/new/new.tscn') # DONE
var quit_sign = load('res://objects/other/title/quit_sign/quit_sign.tscn') # DONE
var reset_sign = load('res://objects/other/title/reset_sign/reset_sign.tscn') # DONE
var rim = load('res://objects/other/title/rim/rim.tscn') # DONE
var rim_deflect = load('res://objects/other/title/rim_deflect/rim_deflect.tscn') # DONE
var scores_sign = load('res://objects/other/title/scores_sign/scores_sign.tscn') # DONE
var start_sign = load('res://objects/other/title/start_sign/start_sign.tscn') # DONE
#var target = load('res://objects/other/title/target/target.tscn')
var title_bg = load('res://objects/other/title/title_bg/title_bg.tscn') # DONE
var title_logo = load('res://objects/other/title/title_logo/title_logo.tscn') # DONE
var trophy = load('res://objects/other/title/trophy/trophy.tscn') # DONE
var tutorial_sign = load('res://objects/other/title/tutorial_sign/tutorial_sign.tscn') # DONE
var x_change = load('res://objects/other/title/x_change/x_change.tscn') # DONE
var x_change2 = load('res://objects/other/title/x_change2/x_change2.tscn') # DONE
var x_end = load('res://objects/other/title/x_end/x_end.tscn') # DONE
var x_moon = load('res://objects/other/title/x_moon/x_moon.tscn') # DONE
var x_scores = load('res://objects/other/title/x_scores/x_scores.tscn') # DONE
var x_shortcut13 = load('res://objects/other/title/x_shortcut13/x_shortcut13.tscn') # DONE
var x_shortcut5 = load('res://objects/other/title/x_shortcut5/x_shortcut5.tscn') # DONE
var x_shortcut9 = load('res://objects/other/title/x_shortcut9/x_shortcut9.tscn') # DONE
var x_stars = load('res://objects/other/title/x_stars/x_stars.tscn') # DONE
var x_start = load('res://objects/other/title/x_start/x_start.tscn') # DONE
var x_sun = load('res://objects/other/title/x_sun/x_sun.tscn') # DONE
var x_title = load('res://objects/other/title/x_title/x_title.tscn') # DONE
var x_tutorial = load('res://objects/other/title/x_tutorial/x_tutorial.tscn') # DONE


#traps
#var arrow_repeater_l = load('res://objects/traps/arrow_repeater_l/arrow_repeater_l.tscn')
#var arrow_repeater_r = load('res://objects/traps/arrow_repeater_r/arrow_repeater_r.tscn')
#var arrow_trap_left = load('res://objects/traps/arrow_trap_left/arrow_trap_left.tscn')
var arrow_trap_left_lit = load('res://objects/traps/arrow_trap_left_lit/arrow_trap_left_lit.tscn') # DONE
#var arrow_trap_right = load('res://objects/traps/arrow_trap_right/arrow_trap_right.tscn')
var arrow_trap_right_lit = load('res://objects/traps/arrow_trap_right_lit/arrow_trap_right_lit.tscn') # DONE
#var arrow_trap_test = load('res://objects/traps/arrow_trap_test/arrow_trap_test.tscn')
#var boulder = load('res://objects/traps/boulder/boulder.tscn')
#var ceiling_trap = load('res://objects/traps/ceiling_trap/ceiling_trap.tscn')
#var door = load('res://objects/traps/door/door.tscn')
#var giant_tiki_head = load('res://objects/traps/giant_tiki_head/giant_tiki_head.tscn')
#var smash_trap = load('res://objects/traps/smash_trap/smash_trap.tscn')
#var smash_trap_lit = load('res://objects/traps/smash_trap_lit/smash_trap_lit.tscn')
#var spears_left = load('res://objects/traps/spears_left/spears_left.tscn')
#var spear_trap_bottom = load('res://objects/traps/spear_trap_bottom/spear_trap_bottom.tscn')
var spear_trap_lit = load('res://objects/traps/spear_trap_lit/spear_trap_lit.tscn') # DONE
#var spear_trap_top = load('res://objects/traps/spear_trap_top/spear_trap_top.tscn')
#var spikes = load('res://objects/traps/spikes/spikes.tscn')
#var spring_trap = load('res://objects/traps/spring_trap/spring_trap.tscn')
#var temp = load('res://objects/traps/temp/temp.tscn')
#var thwomp_trap = load('res://objects/traps/thwomp_trap/thwomp_trap.tscn')
#var trap_block = load('res://objects/traps/trap_block/trap_block.tscn')
