extends Node

#objects
const bricks = preload('res://objects//bricks/bricks.tscn') #\**************************************************/
#const credits1 = preload('res://objects//credits1/credits1.tscn')
#const credits2 = preload('res://objects//credits2/credits2.tscn')
#const curs_obj = preload('res://objects//curs_obj/curs_obj.tscn')
#const end = preload('res://objects//end/end.tscn')
#const end2 = preload('res://objects//end2/end2.tscn')
#const end3 = preload('res://objects//end3/end3.tscn')
#const end_custom = preload('res://objects//end_custom/end_custom.tscn')
#const final_boss = preload('res://objects//final_boss/final_boss.tscn')
const game = preload('res://objects//game/game.tscn')
const gamepad = preload('res://objects//gamepad/gamepad.tscn')
const globals = preload('res://objects//globals/globals.tscn')
#const highscores = preload('res://objects//highscores/highscores.tscn')
const intro = preload('res://objects//intro/intro.tscn')
#const joy_config = preload('res://objects//joy_config/joy_config.tscn')
#const key_config = preload('res://objects//key_config/key_config.tscn')
#const level = preload('res://objects//level/level.tscn')
#const level_editor = preload('res://objects//level_editor/level_editor.tscn')
#const load_level = preload('res://objects//load_level/load_level.tscn')
#const moon_room = preload('res://objects//moon_room/moon_room.tscn')
const music = preload('res://objects//music/music.tscn')
const player1 = preload('res://objects//player1/player1.tscn')
const screen = preload('res://objects//screen/screen.tscn')
#const sprite = preload('res://objects//sprite/sprite.tscn')
#const stars_room = preload('res://objects//stars_room/stars_room.tscn')
#const sun_room = preload('res://objects//sun_room/sun_room.tscn')
const title = preload('res://objects//title/title.tscn')
#const transition = preload('res://objects//transition/transition.tscn')


#basis
#const backdrop = preload('res://objects/basis/backdrop/backdrop.tscn')
#const detritus = preload('res://objects/basis/detritus/detritus.tscn')
#const drawn_sprite = preload('res://objects/basis/drawn_sprite/drawn_sprite.tscn')
#const enemy = preload('res://objects/basis/enemy/enemy.tscn')
#const foreground = preload('res://objects/basis/foreground/foreground.tscn')
const item = preload('res://objects/basis/item/item.tscn')
#const moveable_solid = preload('res://objects/basis/moveable_solid/moveable_solid.tscn')
#const moving_solid = preload('res://objects/basis/moving_solid/moving_solid.tscn')
#const rubble_piece = preload('res://objects/basis/rubble_piece/rubble_piece.tscn')
#const solid = preload('res://objects/basis/solid/solid.tscn')
#const treasure = preload('res://objects/basis/treasure/treasure.tscn')
#const water = preload('res://objects/basis/water/water.tscn')


#blocks
#const alien_ship = preload('res://objects/blocks/alien_ship/alien_ship.tscn')
#const alien_ship_floor = preload('res://objects/blocks/alien_ship_floor/alien_ship_floor.tscn')
#const altar_left = preload('res://objects/blocks/altar_left/altar_left.tscn')
#const altar_right = preload('res://objects/blocks/altar_right/altar_right.tscn')
#const block = preload('res://objects/blocks/block/block.tscn')
const brick = preload('res://objects/blocks/brick/brick.tscn') #\**************************************************/
const brick_smooth = preload('res://objects/blocks/brick_smooth/brick_smooth.tscn') #\**************************************************/
#const cave_bg = preload('res://objects/blocks/cave_bg/cave_bg.tscn')
const dark = preload('res://objects/blocks/dark/dark.tscn')
#const dark_fall = preload('res://objects/blocks/dark_fall/dark_fall.tscn')
#const entrance = preload('res://objects/blocks/entrance/entrance.tscn')
#const exit = preload('res://objects/blocks/exit/exit.tscn')
#const frozen_caveman = preload('res://objects/blocks/frozen_caveman/frozen_caveman.tscn')
#const gold = preload('res://objects/blocks/gold/gold.tscn')
#const gold_big = preload('res://objects/blocks/gold_big/gold_big.tscn')
#const gold_door = preload('res://objects/blocks/gold_door/gold_door.tscn')
#const grave = preload('res://objects/blocks/grave/grave.tscn')
const hard_block = preload('res://objects/blocks/hard_block/hard_block.tscn') #\**************************************************/
#const ice = preload('res://objects/blocks/ice/ice.tscn')
#const ice_block = preload('res://objects/blocks/ice_block/ice_block.tscn')
#const ice_bottom = preload('res://objects/blocks/ice_bottom/ice_bottom.tscn')
#const kali_head = preload('res://objects/blocks/kali_head/kali_head.tscn')
#const lamp = preload('res://objects/blocks/lamp/lamp.tscn')
#const lamp_red = preload('res://objects/blocks/lamp_red/lamp_red.tscn')
#const lava = preload('res://objects/blocks/lava/lava.tscn')
#const lava_solid = preload('res://objects/blocks/lava_solid/lava_solid.tscn')
#const leaves = preload('res://objects/blocks/leaves/leaves.tscn')
#const leaves_tile = preload('res://objects/blocks/leaves_tile/leaves_tile.tscn')
#const lush = preload('res://objects/blocks/lush/lush.tscn')
#const moai = preload('res://objects/blocks/moai/moai.tscn')
#const moai2 = preload('res://objects/blocks/moai2/moai2.tscn')
#const moai3 = preload('res://objects/blocks/moai3/moai3.tscn')
#const moai_inside = preload('res://objects/blocks/moai_inside/moai_inside.tscn')
#const msg_sign = preload('res://objects/blocks/msg_sign/msg_sign.tscn')
#const push_block = preload('res://objects/blocks/push_block/push_block.tscn')
#const sac_altar_left = preload('res://objects/blocks/sac_altar_left/sac_altar_left.tscn')
#const sign = preload('res://objects/blocks/sign/sign.tscn')
#const splash = preload('res://objects/blocks/splash/splash.tscn')
#const temple = preload('res://objects/blocks/temple/temple.tscn')
#const temple_fake = preload('res://objects/blocks/temple_fake/temple_fake.tscn')
#const thin_ice = preload('res://objects/blocks/thin_ice/thin_ice.tscn')
#const tiki_torch = preload('res://objects/blocks/tiki_torch/tiki_torch.tscn')
#const tree = preload('res://objects/blocks/tree/tree.tscn')
#const tree_branch = preload('res://objects/blocks/tree_branch/tree_branch.tscn')
#const tree_branch_tile = preload('res://objects/blocks/tree_branch_tile/tree_branch_tile.tscn')
#const tree_tile = preload('res://objects/blocks/tree_tile/tree_tile.tscn')
#const water_swim = preload('res://objects/blocks/water_swim/water_swim.tscn')
#const x_market = preload('res://objects/blocks/x_market/x_market.tscn')
#const xoc_block = preload('res://objects/blocks/xoc_block/xoc_block.tscn')


#characters
#const damsel = preload('res://objects/characters/damsel/damsel.tscn')
#const damsel_kiss = preload('res://objects/characters/damsel_kiss/damsel_kiss.tscn')
#const shopkeeper = preload('res://objects/characters/shopkeeper/shopkeeper.tscn')
#const shopkeeper2 = preload('res://objects/characters/shopkeeper2/shopkeeper2.tscn')
const tunnel_man = preload('res://objects/characters/tunnel_man/tunnel_man.tscn') #\**************************************************/ check inputs here and see if there's better way to handle
#const yell_help = preload('res://objects/characters/yell_help/yell_help.tscn')


#collectibles
#const ankh = preload('res://objects/collectibles/ankh/ankh.tscn')
#const bomb_bag = preload('res://objects/collectibles/bomb_bag/bomb_bag.tscn')
#const bomb_box = preload('res://objects/collectibles/bomb_box/bomb_box.tscn')
#const bones = preload('res://objects/collectibles/bones/bones.tscn')
#const cape = preload('res://objects/collectibles/cape/cape.tscn')
#const cape_pickup = preload('res://objects/collectibles/cape_pickup/cape_pickup.tscn')
#const chest = preload('res://objects/collectibles/chest/chest.tscn')
#const compass = preload('res://objects/collectibles/compass/compass.tscn')
#const crate = preload('res://objects/collectibles/crate/crate.tscn')
#const crown = preload('res://objects/collectibles/crown/crown.tscn')
#const diamond = preload('res://objects/collectibles/diamond/diamond.tscn')
#const emerald = preload('res://objects/collectibles/emerald/emerald.tscn')
#const emerald_big = preload('res://objects/collectibles/emerald_big/emerald_big.tscn')
#const fake_bones = preload('res://objects/collectibles/fake_bones/fake_bones.tscn')
#const fire_frog_armed = preload('res://objects/collectibles/fire_frog_armed/fire_frog_armed.tscn')
#const flare_crate = preload('res://objects/collectibles/flare_crate/flare_crate.tscn')
#const gloves = preload('res://objects/collectibles/gloves/gloves.tscn')
#const gold_bar = preload('res://objects/collectibles/gold_bar/gold_bar.tscn')
#const gold_bars = preload('res://objects/collectibles/gold_bars/gold_bars.tscn')
#const gold_chunk = preload('res://objects/collectibles/gold_chunk/gold_chunk.tscn')
#const gold_nugget = preload('res://objects/collectibles/gold_nugget/gold_nugget.tscn')
#const jetpack = preload('res://objects/collectibles/jetpack/jetpack.tscn')
#const jordans = preload('res://objects/collectibles/jordans/jordans.tscn')
#const kapala = preload('res://objects/collectibles/kapala/kapala.tscn')
#const key = preload('res://objects/collectibles/key/key.tscn')
#const locked_chest = preload('res://objects/collectibles/locked_chest/locked_chest.tscn')
#const mitt = preload('res://objects/collectibles/mitt/mitt.tscn')
#const para_pickup = preload('res://objects/collectibles/para_pickup/para_pickup.tscn')
#const para_used = preload('res://objects/collectibles/para_used/para_used.tscn')
#const paste = preload('res://objects/collectibles/paste/paste.tscn')
#const rope_bag = preload('res://objects/collectibles/rope_bag/rope_bag.tscn')
#const rope_pile = preload('res://objects/collectibles/rope_pile/rope_pile.tscn')
#const ruby = preload('res://objects/collectibles/ruby/ruby.tscn')
#const ruby_big = preload('res://objects/collectibles/ruby_big/ruby_big.tscn')
#const sapphire = preload('res://objects/collectibles/sapphire/sapphire.tscn')
#const sapphire_big = preload('res://objects/collectibles/sapphire_big/sapphire_big.tscn')
#const spectacles = preload('res://objects/collectibles/spectacles/spectacles.tscn')
#const spike_shoes = preload('res://objects/collectibles/spike_shoes/spike_shoes.tscn')
#const spring_shoes = preload('res://objects/collectibles/spring_shoes/spring_shoes.tscn')
#const udjat_eye = preload('res://objects/collectibles/udjat_eye/udjat_eye.tscn')


#effects
#const big_collect = preload('res://objects/effects/big_collect/big_collect.tscn')
#const blood = preload('res://objects/effects/blood/blood.tscn')
#const blood_spark = preload('res://objects/effects/blood_spark/blood_spark.tscn')
#const blood_trail = preload('res://objects/effects/blood_trail/blood_trail.tscn')
#const bone = preload('res://objects/effects/bone/bone.tscn')
#const bubble = preload('res://objects/effects/bubble/bubble.tscn')
#const bullet = preload('res://objects/effects/bullet/bullet.tscn')
#const burn = preload('res://objects/effects/burn/burn.tscn')
#const drip = preload('res://objects/effects/drip/drip.tscn')
#const explosion = preload('res://objects/effects/explosion/explosion.tscn')
#const flame = preload('res://objects/effects/flame/flame.tscn')
#const flame_trail = preload('res://objects/effects/flame_trail/flame_trail.tscn')
const flare_spark = preload('res://objects/effects/flare_spark/flare_spark.tscn') #\**************************************************/ check 'animation end' function
#const fly = preload('res://objects/effects/fly/fly.tscn')
#const heart = preload('res://objects/effects/heart/heart.tscn')
#const items_get = preload('res://objects/effects/items_get/items_get.tscn')
#const laser = preload('res://objects/effects/laser/laser.tscn')
#const laser_explode = preload('res://objects/effects/laser_explode/laser_explode.tscn')
#const laser_trail = preload('res://objects/effects/laser_trail/laser_trail.tscn')
#const lava_drip = preload('res://objects/effects/lava_drip/lava_drip.tscn')
#const leaf = preload('res://objects/effects/leaf/leaf.tscn')
const poof = preload('res://objects/effects/poof/poof.tscn') #\**************************************************/ check 'animation end' function
#const psychic_create = preload('res://objects/effects/psychic_create/psychic_create.tscn')
#const psychic_create2 = preload('res://objects/effects/psychic_create2/psychic_create2.tscn')
#const psychic_create_p = preload('res://objects/effects/psychic_create_p/psychic_create_p.tscn')
#const psychic_wave = preload('res://objects/effects/psychic_wave/psychic_wave.tscn')
#const psychic_wave_p = preload('res://objects/effects/psychic_wave_p/psychic_wave_p.tscn')
#const rope_burn = preload('res://objects/effects/rope_burn/rope_burn.tscn')
#const rubble_dark = preload('res://objects/effects/rubble_dark/rubble_dark.tscn')
#const rubble_dark_small = preload('res://objects/effects/rubble_dark_small/rubble_dark_small.tscn')
#const shotgun_blast_left = preload('res://objects/effects/shotgun_blast_left/shotgun_blast_left.tscn')
#const shotgun_blast_right = preload('res://objects/effects/shotgun_blast_right/shotgun_blast_right.tscn')
#const small_collect = preload('res://objects/effects/small_collect/small_collect.tscn')
#const smoke_puff = preload('res://objects/effects/smoke_puff/smoke_puff.tscn')
#const volcano_flame = preload('res://objects/effects/volcano_flame/volcano_flame.tscn')
#const web = preload('res://objects/effects/web/web.tscn')
#const web_ball = preload('res://objects/effects/web_ball/web_ball.tscn')
#const yellow_ball = preload('res://objects/effects/yellow_ball/yellow_ball.tscn')
#const yellow_trail = preload('res://objects/effects/yellow_trail/yellow_trail.tscn')


#enemies
#const alien = preload('res://objects/enemies/alien/alien.tscn')
#const alien_boss = preload('res://objects/enemies/alien_boss/alien_boss.tscn')
#const alien_eject = preload('res://objects/enemies/alien_eject/alien_eject.tscn')
#const barrier = preload('res://objects/enemies/barrier/barrier.tscn')
#const barrier_emitter = preload('res://objects/enemies/barrier_emitter/barrier_emitter.tscn')
#const bat = preload('res://objects/enemies/bat/bat.tscn')
#const caveman = preload('res://objects/enemies/caveman/caveman.tscn')
#const caveman_worship = preload('res://objects/enemies/caveman_worship/caveman_worship.tscn')
#const dead_fish = preload('res://objects/enemies/dead_fish/dead_fish.tscn')
#const enemy_sight = preload('res://objects/enemies/enemy_sight/enemy_sight.tscn')
#const entrance_check = preload('res://objects/enemies/entrance_check/entrance_check.tscn')
#const fire_frog = preload('res://objects/enemies/fire_frog/fire_frog.tscn')
#const frog = preload('res://objects/enemies/frog/frog.tscn')
#const ghost = preload('res://objects/enemies/ghost/ghost.tscn')
#const giant_spider = preload('res://objects/enemies/giant_spider/giant_spider.tscn')
#const giant_spider_hang = preload('res://objects/enemies/giant_spider_hang/giant_spider_hang.tscn')
#const hawkman = preload('res://objects/enemies/hawkman/hawkman.tscn')
#const jaws = preload('res://objects/enemies/jaws/jaws.tscn')
#const magma = preload('res://objects/enemies/magma/magma.tscn')
#const magma_man = preload('res://objects/enemies/magma_man/magma_man.tscn')
#const magma_trail = preload('res://objects/enemies/magma_trail/magma_trail.tscn')
#const man_trap = preload('res://objects/enemies/man_trap/man_trap.tscn')
#const monkey = preload('res://objects/enemies/monkey/monkey.tscn')
#const olmec = preload('res://objects/enemies/olmec/olmec.tscn')
#const olmec_debris = preload('res://objects/enemies/olmec_debris/olmec_debris.tscn')
#const olmec_slam = preload('res://objects/enemies/olmec_slam/olmec_slam.tscn')
#const piranha = preload('res://objects/enemies/piranha/piranha.tscn')
#const scarab = preload('res://objects/enemies/scarab/scarab.tscn')
#const skeleton = preload('res://objects/enemies/skeleton/skeleton.tscn')
#const snake = preload('res://objects/enemies/snake/snake.tscn')
#const spider = preload('res://objects/enemies/spider/spider.tscn')
#const spider_hang = preload('res://objects/enemies/spider_hang/spider_hang.tscn')
#const tomb_lord = preload('res://objects/enemies/tomb_lord/tomb_lord.tscn')
#const ufo = preload('res://objects/enemies/ufo/ufo.tscn')
#const ufo_crash = preload('res://objects/enemies/ufo_crash/ufo_crash.tscn')
#const vampire = preload('res://objects/enemies/vampire/vampire.tscn')
#const yeti = preload('res://objects/enemies/yeti/yeti.tscn')
#const yeti_king = preload('res://objects/enemies/yeti_king/yeti_king.tscn')
#const zombie = preload('res://objects/enemies/zombie/zombie.tscn')


#init
#const check_box = preload('res://objects/init/check_box/check_box.tscn')
#const check_box2 = preload('res://objects/init/check_box2/check_box2.tscn')
#const check_box3 = preload('res://objects/init/check_box3/check_box3.tscn')
#const check_box4 = preload('res://objects/init/check_box4/check_box4.tscn')
#const joy_config_button = preload('res://objects/init/joy_config_button/joy_config_button.tscn')
#const key_config_button = preload('res://objects/init/key_config_button/key_config_button.tscn')
#const ok_button = preload('res://objects/init/ok_button/ok_button.tscn')
#const radio_box = preload('res://objects/init/radio_box/radio_box.tscn')
#const slider1 = preload('res://objects/init/slider1/slider1.tscn')
#const slider2 = preload('res://objects/init/slider2/slider2.tscn')


#items
#const arrow = preload('res://objects/items/arrow/arrow.tscn')
#const ball = preload('res://objects/items/ball/ball.tscn')
#const ball2 = preload('res://objects/items/ball2/ball2.tscn')
#const basketball = preload('res://objects/items/basketball/basketball.tscn')
#const bomb = preload('res://objects/items/bomb/bomb.tscn')
#const bow = preload('res://objects/items/bow/bow.tscn')
#const chain = preload('res://objects/items/chain/chain.tscn')
#const chain2 = preload('res://objects/items/chain2/chain2.tscn')
#const crystal_skull = preload('res://objects/items/crystal_skull/crystal_skull.tscn')
#const dice = preload('res://objects/items/dice/dice.tscn')
#const fire_frog_bomb = preload('res://objects/items/fire_frog_bomb/fire_frog_bomb.tscn')
#const fish_bone = preload('res://objects/items/fish_bone/fish_bone.tscn')
const flare = preload('res://objects/items/flare/flare.tscn') #\**************************************************/ see if there is better way to deal with alarm
#const gold_idol = preload('res://objects/items/gold_idol/gold_idol.tscn')
#const jar = preload('res://objects/items/jar/jar.tscn')
#const lamp_item = preload('res://objects/items/lamp_item/lamp_item.tscn')
#const lamp_red_item = preload('res://objects/items/lamp_red_item/lamp_red_item.tscn')
#const machete = preload('res://objects/items/machete/machete.tscn')
#const machete_pre = preload('res://objects/items/machete_pre/machete_pre.tscn')
#const mattock = preload('res://objects/items/mattock/mattock.tscn')
#const mattock_head = preload('res://objects/items/mattock_head/mattock_head.tscn')
#const mattock_hit = preload('res://objects/items/mattock_hit/mattock_hit.tscn')
#const mattock_pre = preload('res://objects/items/mattock_pre/mattock_pre.tscn')
#const parachute = preload('res://objects/items/parachute/parachute.tscn')
#const pistol = preload('res://objects/items/pistol/pistol.tscn')
#const rock = preload('res://objects/items/rock/rock.tscn')
const rope = preload('res://objects/items/rope/rope.tscn') #\**************************************************/
const rope_throw = preload('res://objects/items/rope_throw/rope_throw.tscn') #\**************************************************/
const rope_top = preload('res://objects/items/rope_top/rope_top.tscn') #\**************************************************/
#const sceptre = preload('res://objects/items/sceptre/sceptre.tscn')
#const shotgun = preload('res://objects/items/shotgun/shotgun.tscn')
#const skull = preload('res://objects/items/skull/skull.tscn')
#const slash = preload('res://objects/items/slash/slash.tscn')
#const teleporter = preload('res://objects/items/teleporter/teleporter.tscn')
#const web_cannon = preload('res://objects/items/web_cannon/web_cannon.tscn')
const whip = preload('res://objects/items/whip/whip.tscn') #\**************************************************/
const whip_pre = preload('res://objects/items/whip_pre/whip_pre.tscn') #\**************************************************/ see if something can be done about alarm


#level editor
#const alien_boss_tile = preload('res://objects/level editor/alien_boss_tile/alien_boss_tile.tscn')
#const alien_tile = preload('res://objects/level editor/alien_tile/alien_tile.tscn')
#const edit_button = preload('res://objects/level editor/edit_button/edit_button.tscn')
#const fire_frog_tile = preload('res://objects/level editor/fire_frog_tile/fire_frog_tile.tscn')
#const frog_tile = preload('res://objects/level editor/frog_tile/frog_tile.tscn')
#const giant_spider_tile = preload('res://objects/level editor/giant_spider_tile/giant_spider_tile.tscn')
#const load_button = preload('res://objects/level editor/load_button/load_button.tscn')
#const man_trap_tile = preload('res://objects/level editor/man_trap_tile/man_trap_tile.tscn')
#const mega_mouth_tile = preload('res://objects/level editor/mega_mouth_tile/mega_mouth_tile.tscn')
#const new_button = preload('res://objects/level editor/new_button/new_button.tscn')
#const test_button = preload('res://objects/level editor/test_button/test_button.tscn')
#const tomb_lord_tile = preload('res://objects/level editor/tomb_lord_tile/tomb_lord_tile.tscn')
#const ufo_tile = preload('res://objects/level editor/ufo_tile/ufo_tile.tscn')
#const vampire_tile = preload('res://objects/level editor/vampire_tile/vampire_tile.tscn')
#const yeti_king_tile = preload('res://objects/level editor/yeti_king_tile/yeti_king_tile.tscn')
#const zombie_tile = preload('res://objects/level editor/zombie_tile/zombie_tile.tscn')


#other
const hint_hand = preload('res://objects/other/hint_hand/hint_hand.tscn') #\**************************************************/ check text box and hiding label in physics_process
#const menu_sel = preload('res://objects/other/menu_sel/menu_sel.tscn')
#const page_down = preload('res://objects/other/page_down/page_down.tscn')
#const page_up = preload('res://objects/other/page_up/page_up.tscn')
#const p_dummy = preload('res://objects/other/p_dummy/p_dummy.tscn')
#const p_dummy2 = preload('res://objects/other/p_dummy2/p_dummy2.tscn')
const p_dummy3 = preload('res://objects/other/p_dummy3/p_dummy3.tscn') #\**************************************************/ check alarms and flipped sprite. also put camera under animated sprite
const p_dummy4 = preload('res://objects/other/p_dummy4/p_dummy4.tscn') #\**************************************************/ check alarms
#const p_dummy5 = preload('res://objects/other/p_dummy5/p_dummy5.tscn')
#const p_dummy6 = preload('res://objects/other/p_dummy6/p_dummy6.tscn')
#const wal_damsel = preload('res://objects/other/wal_damsel/wal_damsel.tscn')


#other\end
#const bg_end3 = preload('res://objects/other/end/bg_end3/bg_end3.tscn')
#const big_treasure = preload('res://objects/other/end/big_treasure/big_treasure.tscn')
#const end_plat = preload('res://objects/other/end/end_plat/end_plat.tscn')
#const lava_spray = preload('res://objects/other/end/lava_spray/lava_spray.tscn')
#const player_sil = preload('res://objects/other/end/player_sil/player_sil.tscn')
#const treasure_sil = preload('res://objects/other/end/treasure_sil/treasure_sil.tscn')


#other\intro
const bat_intro = preload('res://objects/other/intro/bat_intro/bat_intro.tscn') #\**************************************************/
#const camel = preload('res://objects/other/intro/camel/camel.tscn')
#const caravan = preload('res://objects/other/intro/caravan/caravan.tscn')
const desert = preload('res://objects/other/intro/desert/desert.tscn') #\**************************************************/
const desert2 = preload('res://objects/other/intro/desert2/desert2.tscn') #\**************************************************/
#const desert_scroll = preload('res://objects/other/intro/desert_scroll/desert_scroll.tscn')
#const desert_scroll2 = preload('res://objects/other/intro/desert_scroll2/desert_scroll2.tscn')
const desert_top = preload('res://objects/other/intro/desert_top/desert_top.tscn') #\**************************************************/
#const desert_top_scroll = preload('res://objects/other/intro/desert_top_scroll/desert_top_scroll.tscn')
const intro_bg = preload('res://objects/other/intro/intro_bg/intro_bg.tscn') #\**************************************************/
const moon = preload('res://objects/other/intro/moon/moon.tscn') #\**************************************************/
#const palm_tree_scroll = preload('res://objects/other/intro/palm_tree_scroll/palm_tree_scroll.tscn')
#const shrub_scroll = preload('res://objects/other/intro/shrub_scroll/shrub_scroll.tscn')

const shrub_dark = preload("res://objects/other/intro/shrub_dark/shrub_dark.tscn")
const cave_bg_entrance = preload("res://objects/blocks/cave_bg_entrance/cave_bg_entrance.tscn")


#other\title
#const basket = preload('res://objects/other/title/basket/basket.tscn')
#const bat_target = preload('res://objects/other/title/bat_target/bat_target.tscn')
#const button_highscore = preload('res://objects/other/title/button_highscore/button_highscore.tscn')
#const target = preload('res://objects/other/title/target/target.tscn')


#supersound
#const re = preload('res://objects/supersound/re/re.tscn')


#traps
#const arrow_repeater_l = preload('res://objects/traps/arrow_repeater_l/arrow_repeater_l.tscn')
#const arrow_repeater_r = preload('res://objects/traps/arrow_repeater_r/arrow_repeater_r.tscn')
#const arrow_trap_left = preload('res://objects/traps/arrow_trap_left/arrow_trap_left.tscn')
#const arrow_trap_right = preload('res://objects/traps/arrow_trap_right/arrow_trap_right.tscn')
#const arrow_trap_test = preload('res://objects/traps/arrow_trap_test/arrow_trap_test.tscn')
#const boulder = preload('res://objects/traps/boulder/boulder.tscn')
#const ceiling_trap = preload('res://objects/traps/ceiling_trap/ceiling_trap.tscn')
#const door = preload('res://objects/traps/door/door.tscn')
#const giant_tiki_head = preload('res://objects/traps/giant_tiki_head/giant_tiki_head.tscn')
#const smash_trap = preload('res://objects/traps/smash_trap/smash_trap.tscn')
#const smash_trap_lit = preload('res://objects/traps/smash_trap_lit/smash_trap_lit.tscn')
#const spears_left = preload('res://objects/traps/spears_left/spears_left.tscn')
#const spear_trap_bottom = preload('res://objects/traps/spear_trap_bottom/spear_trap_bottom.tscn')
#const spear_trap_top = preload('res://objects/traps/spear_trap_top/spear_trap_top.tscn')
#const spikes = preload('res://objects/traps/spikes/spikes.tscn')
#const spring_trap = preload('res://objects/traps/spring_trap/spring_trap.tscn')
#const temp = preload('res://objects/traps/temp/temp.tscn')
#const thwomp_trap = preload('res://objects/traps/thwomp_trap/thwomp_trap.tscn')
#const trap_block = preload('res://objects/traps/trap_block/trap_block.tscn')
