extends Node

#objects
var bricks = 'res://objects/bricks/bricks.tscn' # DONE
#var credits1 = 'res://objects/credits1/credits1.tscn'
#var credits2 = 'res://objects/credits2/credits2.tscn'
#var curs_obj = 'res://objects/curs_obj/curs_obj.tscn'
#var end = 'res://objects/end/end.tscn'
var end2 = 'res://objects/end2/end2.tscn' # DONE
#var end3 = 'res://objects/end3/end3.tscn'
#var end_custom = 'res://objects/end_custom/end_custom.tscn'
var final_boss = 'res://objects/final_boss/final_boss.tscn' # DONE
var game = 'res://objects/game/game.tscn' # DONE
var gamepad = 'res://objects/gamepad/gamepad.tscn' # DONE
var globals = 'res://objects/globals/globals.tscn' # DONE
#var highscores = 'res://objects/highscores/highscores.tscn'
var intro = 'res://objects/intro/intro.tscn' # DONE
#var joy_config = 'res://objects/joy_config/joy_config.tscn'
#var key_config = 'res://objects/key_config/key_config.tscn'
#var level = 'res://objects/level/level.tscn'
#var level_editor = 'res://objects/level_editor/level_editor.tscn'
#var load_level = 'res://objects/load_level/load_level.tscn'
#var moon_room = 'res://objects/moon_room/moon_room.tscn'
var music = 'res://objects/music/music.tscn' # DONE
var player1 = 'res://objects/player1/player1.tscn' # PROGRESS (need to implemention collision_with_blood)
var room = 'res://objects/room/room.tscn' # DONE
var screen = 'res://objects/screen/screen.tscn' # PROGRESS (need to finish begin step)
var sprite = 'res://objects/sprite/sprite.tscn' # DONE
var stars_room = 'res://objects/stars_room/stars_room.tscn' # DONE
#var sun_room = 'res://objects/sun_room/sun_room.tscn'
var title = 'res://objects/title/title.tscn' # DONE
#var transition = 'res://objects/transition/transition.tscn'


#basis
var backdrop = 'res://objects/basis/backdrop/backdrop.tscn' # DONE
var character = 'res://objects/basis/character/character.tscn' # DONE
var detritus = 'res://objects/basis/detritus/detritus.tscn' # DONE
var drawn_sprite = 'res://objects/basis/drawn_sprite/drawn_sprite.tscn' # DONE
#var enemy = 'res://objects/basis/enemy/enemy.tscn'
var foreground = 'res://objects/basis/foreground/foreground.tscn' # DONE
var frill = 'res://objects/basis/frill/frill.tscn' # DONE
var item = 'res://objects/basis/item/item.tscn' # PROGRESS
var ladder = 'res://objects/basis/ladder/ladder.tscn' # DONE
var menu = 'res://objects/basis/menu/menu.tscn' # DONE
var moveable_solid = 'res://objects/basis/moveable_solid/moveable_solid.tscn' # DONE
var moving_solid = 'res://objects/basis/moving_solid/moving_solid.tscn' # DONE
var platform = 'res://objects/basis/platform/platform.tscn' # DONE
var rubble_piece = 'res://objects/basis/rubble_piece/rubble_piece.tscn' # DONE
var solid = 'res://objects/basis/solid/solid.tscn' # DONE
var treasure = 'res://objects/basis/treasure/treasure.tscn' # DONE
var water = 'res://objects/basis/water/water.tscn' # DONE


#blocks
var alien_ship = 'res://objects/blocks/alien_ship/alien_ship.tscn' # DONE
var alien_ship_floor = 'res://objects/blocks/alien_ship_floor/alien_ship_floor.tscn' # DONE
var altar_left = 'res://objects/blocks/altar_left/altar_left.tscn' # DONE
var altar_right = 'res://objects/blocks/altar_right/altar_right.tscn' # DONE
var black_fade_up = 'res://objects/blocks/black_fade_up/black_fade_up.tscn' # DONE
var block = 'res://objects/blocks/block/block.tscn' # DONE
var brick = 'res://objects/blocks/brick/brick.tscn' # DONE
var brick_smooth = 'res://objects/blocks/brick_smooth/brick_smooth.tscn' # DONE
var cave_bg = 'res://objects/blocks/cave_bg/cave_bg.tscn' # DONE
var cave_bg2 = 'res://objects/blocks/cave_bg2/cave_bg2.tscn' # DONE
var cave_bg_entrance = 'res://objects/blocks/cave_bg_entrance/cave_bg_entrance.tscn' # DONE
var dark = 'res://objects/blocks/dark/dark.tscn' # DONE
var dark_fall = 'res://objects/blocks/dark_fall/dark_fall.tscn' # DONE
var entrance = 'res://objects/blocks/entrance/entrance.tscn' # PROGRESS
#var exit = 'res://objects/blocks/exit/exit.tscn'
var frozen_caveman = 'res://objects/blocks/frozen_caveman/frozen_caveman.tscn' # DONE
var gold = 'res://objects/blocks/gold/gold.tscn' # DONE
var gold_big = 'res://objects/blocks/gold_big/gold_big.tscn' # DONE
var gold_door = 'res://objects/blocks/gold_door/gold_door.tscn' # DONE
var grave = 'res://objects/blocks/grave/grave.tscn' # DONE
var hard_block = 'res://objects/blocks/hard_block/hard_block.tscn' # DONE
var ice = 'res://objects/blocks/ice/ice.tscn' # DONE
var ice_block = 'res://objects/blocks/ice_block/ice_block.tscn' # DONE
var ice_bottom = 'res://objects/blocks/ice_bottom/ice_bottom.tscn' # DONE
var kali_head = 'res://objects/blocks/kali_head/kali_head.tscn' # DONE
var ladder_orange = 'res://objects/blocks/ladder_orange/ladder_orange.tscn' # DONE
var ladder_top = 'res://objects/blocks/ladder_top/ladder_top.tscn' # DONE
var lamp = 'res://objects/blocks/lamp/lamp.tscn' # DONE
var lamp_red = 'res://objects/blocks/lamp_red/lamp_red.tscn' # DONE
var lava = 'res://objects/blocks/lava/lava.tscn' # DONE
var lava_solid = 'res://objects/blocks/lava_solid/lava_solid.tscn' # DONE
var leaves = 'res://objects/blocks/leaves/leaves.tscn' # DONE
var leaves_tile = 'res://objects/blocks/leaves_tile/leaves_tile.tscn' # DONE
var lush = 'res://objects/blocks/lush/lush.tscn' # DONE
var moai = 'res://objects/blocks/moai/moai.tscn' # DONE
var moai2 = 'res://objects/blocks/moai2/moai2.tscn' # DONE
var moai3 = 'res://objects/blocks/moai3/moai3.tscn' # DONE
var moai_inside = 'res://objects/blocks/moai_inside/moai_inside.tscn' # DONE
var msg_sign = 'res://objects/blocks/msg_sign/msg_sign.tscn' # DONE
var push_block = 'res://objects/blocks/push_block/push_block.tscn' # DONE
var sac_altar_left = 'res://objects/blocks/sac_altar_left/sac_altar_left.tscn' # DONE
var sac_altar_right = 'res://objects/blocks/sac_altar_right/sac_altar_right.tscn' # DONE
var sign = 'res://objects/blocks/sign/sign.tscn' # DONE
var splash = 'res://objects/blocks/splash/splash.tscn' # DONE
var temple = 'res://objects/blocks/temple/temple.tscn' # DONE
var temple_fake = 'res://objects/blocks/temple_fake/temple_fake.tscn' # DONE
var thin_ice = 'res://objects/blocks/thin_ice/thin_ice.tscn' # DONE
var tiki_torch = 'res://objects/blocks/tiki_torch/tiki_torch.tscn' # DONE
var tree = 'res://objects/blocks/tree/tree.tscn' # DONE
var tree_branch = 'res://objects/blocks/tree_branch/tree_branch.tscn' # DONE
var tree_branch_tile = 'res://objects/blocks/tree_branch_tile/tree_branch_tile.tscn' # DONE
var tree_tile = 'res://objects/blocks/tree_tile/tree_tile.tscn' # DONE
var vine = 'res://objects/blocks/vine/vine.tscn' # DONE
var vine_top = 'res://objects/blocks/vine_top/vine_top.tscn' # DONE
var water_swim = 'res://objects/blocks/water_swim/water_swim.tscn' # DONE
var x_gold = 'res://objects/blocks/x_gold/x_gold.tscn' # DONE
var x_market = 'res://objects/blocks/x_market/x_market.tscn' # DONE
var xoc_block = 'res://objects/blocks/xoc_block/xoc_block.tscn' # DONE


#characters
#var damsel = 'res://objects/characters/damsel/damsel.tscn'
var damsel_kiss = 'res://objects/characters/damsel_kiss/damsel_kiss.tscn' # DONE
#var shopkeeper = 'res://objects/characters/shopkeeper/shopkeeper.tscn'
var shopkeeper2 = 'res://objects/characters/shopkeeper2/shopkeeper2.tscn' # DONE
var tunnel_man = 'res://objects/characters/tunnel_man/tunnel_man.tscn' # DONE
var yell_help = 'res://objects/characters/yell_help/yell_help.tscn' # DONE


#collectibles
var ankh = 'res://objects/collectibles/ankh/ankh.tscn' # DONE
var bomb_bag = 'res://objects/collectibles/bomb_bag/bomb_bag.tscn' # DONE
var bomb_box = 'res://objects/collectibles/bomb_box/bomb_box.tscn' # DONE
var bones = 'res://objects/collectibles/bones/bones.tscn' # DONE
var cape = 'res://objects/collectibles/cape/cape.tscn' # DONE
var cape_pickup = 'res://objects/collectibles/cape_pickup/cape_pickup.tscn' # DONE
var chest = 'res://objects/collectibles/chest/chest.tscn' # DONE
var compass = 'res://objects/collectibles/compass/compass.tscn' # DONE
var crate = 'res://objects/collectibles/crate/crate.tscn' # DONE
var crown = 'res://objects/collectibles/crown/crown.tscn' # DONE
var diamond = 'res://objects/collectibles/diamond/diamond.tscn' # DONE
var emerald = 'res://objects/collectibles/emerald/emerald.tscn' # DONE
var emerald_big = 'res://objects/collectibles/emerald_big/emerald_big.tscn' # DONE
var fake_bones = 'res://objects/collectibles/fake_bones/fake_bones.tscn' # DONE
var fire_frog_armed = 'res://objects/collectibles/fire_frog_armed/fire_frog_armed.tscn' # DONE
var flare_crate = 'res://objects/collectibles/flare_crate/flare_crate.tscn' # DONE
var gloves = 'res://objects/collectibles/gloves/gloves.tscn' # DONE
var gold_bar = 'res://objects/collectibles/gold_bar/gold_bar.tscn' # DONE
var gold_bars = 'res://objects/collectibles/gold_bars/gold_bars.tscn' # DONE
var gold_chunk = 'res://objects/collectibles/gold_chunk/gold_chunk.tscn' # DONE
var gold_nugget = 'res://objects/collectibles/gold_nugget/gold_nugget.tscn' # DONE
var jetpack = 'res://objects/collectibles/jetpack/jetpack.tscn' # DONE
var jordans = 'res://objects/collectibles/jordans/jordans.tscn' # DONE
var kapala = 'res://objects/collectibles/kapala/kapala.tscn' # DONE
var key = 'res://objects/collectibles/key/key.tscn' # DONE
var locked_chest = 'res://objects/collectibles/locked_chest/locked_chest.tscn' # DONE
var mitt = 'res://objects/collectibles/mitt/mitt.tscn' # DONE
var para_pickup = 'res://objects/collectibles/para_pickup/para_pickup.tscn' # DONE
var para_used = 'res://objects/collectibles/para_used/para_used.tscn' # DONE
var paste = 'res://objects/collectibles/paste/paste.tscn' # DONE
var rope_bag = 'res://objects/collectibles/rope_bag/rope_bag.tscn' # DONE
var rope_pile = 'res://objects/collectibles/rope_pile/rope_pile.tscn' # DONE
var ruby = 'res://objects/collectibles/ruby/ruby.tscn' # DONE
var ruby_big = 'res://objects/collectibles/ruby_big/ruby_big.tscn' # DONE
var sapphire = 'res://objects/collectibles/sapphire/sapphire.tscn' # DONE
var sapphire_big = 'res://objects/collectibles/sapphire_big/sapphire_big.tscn' # DONE
var spectacles = 'res://objects/collectibles/spectacles/spectacles.tscn' # DONE
var spike_shoes = 'res://objects/collectibles/spike_shoes/spike_shoes.tscn' # DONE
var spring_shoes = 'res://objects/collectibles/spring_shoes/spring_shoes.tscn' # DONE
var udjat_eye = 'res://objects/collectibles/udjat_eye/udjat_eye.tscn' # DONE


#effects
var big_collect = 'res://objects/effects/big_collect/big_collect.tscn' # DONE
var blood = 'res://objects/effects/blood/blood.tscn' # DONE
var blood_spark = 'res://objects/effects/blood_spark/blood_spark.tscn' # DONE
var blood_trail = 'res://objects/effects/blood_trail/blood_trail.tscn' # DONE
var bone = 'res://objects/effects/bone/bone.tscn' # DONE
var bubble = 'res://objects/effects/bubble/bubble.tscn' # DONE
var bullet = 'res://objects/effects/bullet/bullet.tscn' # DONE
var burn = 'res://objects/effects/burn/burn.tscn' # DONE
var drip = 'res://objects/effects/drip/drip.tscn' # DONE
#var explosion = 'res://objects/effects/explosion/explosion.tscn'
var flame = 'res://objects/effects/flame/flame.tscn' # DONE
var flame_trail = 'res://objects/effects/flame_trail/flame_trail.tscn' # DONE
var flare_spark = 'res://objects/effects/flare_spark/flare_spark.tscn' # PROGRESS (fix animation)
var fly = 'res://objects/effects/fly/fly.tscn' # DONE
var heart = 'res://objects/effects/heart/heart.tscn' # DONE
var items_get = 'res://objects/effects/items_get/items_get.tscn' # DONE
var laser = 'res://objects/effects/laser/laser.tscn' # DONE
var laser_explode = 'res://objects/effects/laser_explode/laser_explode.tscn' # DONE
var laser_trail = 'res://objects/effects/laser_trail/laser_trail.tscn' # DONE
var lava_drip = 'res://objects/effects/lava_drip/lava_drip.tscn' # DONE
var leaf = 'res://objects/effects/leaf/leaf.tscn' # DONE
var poof = 'res://objects/effects/poof/poof.tscn' # DONE
var psychic_create = 'res://objects/effects/psychic_create/psychic_create.tscn' # DONE
var psychic_create2 = 'res://objects/effects/psychic_create2/psychic_create2.tscn' # DONE
var psychic_create_p = 'res://objects/effects/psychic_create_p/psychic_create_p.tscn' # DONE
var psychic_wave = 'res://objects/effects/psychic_wave/psychic_wave.tscn' # DONE
var psychic_wave_p = 'res://objects/effects/psychic_wave_p/psychic_wave_p.tscn' # DONE
var rope_burn = 'res://objects/effects/rope_burn/rope_burn.tscn' # DONE
var rubble = 'res://objects/effects/rubble/rubble.tscn' # DONE
var rubble_dark = 'res://objects/effects/rubble_dark/rubble_dark.tscn' # DONE
#var rubble_dark_small = 'res://objects/effects/rubble_dark_small/rubble_dark_small.tscn'
var rubble_small = 'res://objects/effects/rubble_small/rubble_small.tscn' # DONE
var shotgun_blast_left = 'res://objects/effects/shotgun_blast_left/shotgun_blast_left.tscn' # DONE
var shotgun_blast_right = 'res://objects/effects/shotgun_blast_right/shotgun_blast_right.tscn' # DONE
var small_collect = 'res://objects/effects/small_collect/small_collect.tscn' # DONE
var smoke_puff = 'res://objects/effects/smoke_puff/smoke_puff.tscn' # DONE
var volcano_flame = 'res://objects/effects/volcano_flame/volcano_flame.tscn' # DONE
var web = 'res://objects/effects/web/web.tscn' # DONE
var web_ball = 'res://objects/effects/web_ball/web_ball.tscn' # DONE
var yellow_ball = 'res://objects/effects/yellow_ball/yellow_ball.tscn' # DONE
var yellow_trail = 'res://objects/effects/yellow_trail/yellow_trail.tscn' # DONE


#enemies
var alien = 'res://objects/enemies/alien/alien.tscn' # DONE
var alien_boss = 'res://objects/enemies/alien_boss/alien_boss.tscn' # DONE
var alien_eject = 'res://objects/enemies/alien_eject/alien_eject.tscn' # DONE
var barrier = 'res://objects/enemies/barrier/barrier.tscn' # DONE
var barrier_emitter = 'res://objects/enemies/barrier_emitter/barrier_emitter.tscn' # DONE
var bat = 'res://objects/enemies/bat/bat.tscn' # DONE
#var caveman = 'res://objects/enemies/caveman/caveman.tscn'
var caveman_worship = 'res://objects/enemies/caveman_worship/caveman_worship.tscn' # DONE
var dead_fish = 'res://objects/enemies/dead_fish/dead_fish.tscn' # DONE
var enemy_sight = 'res://objects/enemies/enemy_sight/enemy_sight.tscn' # DONE
var entrance_check = 'res://objects/enemies/entrance_check/entrance_check.tscn' # DONE
var fire_frog = 'res://objects/enemies/fire_frog/fire_frog.tscn' # DONE
var frog = 'res://objects/enemies/frog/frog.tscn' # DONE
var ghost = 'res://objects/enemies/ghost/ghost.tscn' # DONE
#var giant_spider = 'res://objects/enemies/giant_spider/giant_spider.tscn'
var giant_spider_hang = 'res://objects/enemies/giant_spider_hang/giant_spider_hang.tscn' # DONE
#var hawkman = 'res://objects/enemies/hawkman/hawkman.tscn'
var hawkman_worship = 'res://objects/enemies/hawkman_worship/hawkman_worship.tscn' # DONE
#var jaws = 'res://objects/enemies/jaws/jaws.tscn'
var magma = 'res://objects/enemies/magma/magma.tscn' # DONE
#var magma_man = 'res://objects/enemies/magma_man/magma_man.tscn'
var magma_trail = 'res://objects/enemies/magma_trail/magma_trail.tscn' # DONE
#var man_trap = 'res://objects/enemies/man_trap/man_trap.tscn'
#var monkey = 'res://objects/enemies/monkey/monkey.tscn'
#var olmec = 'res://objects/enemies/olmec/olmec.tscn'
var olmec_debris = 'res://objects/enemies/olmec_debris/olmec_debris.tscn' # DONE
var olmec_slam = 'res://objects/enemies/olmec_slam/olmec_slam.tscn' # DONE
var piranha = 'res://objects/enemies/piranha/piranha.tscn' # DONE
var scarab = 'res://objects/enemies/scarab/scarab.tscn' # DONE
var skeleton = 'res://objects/enemies/skeleton/skeleton.tscn' # DONE
var snake = 'res://objects/enemies/snake/snake.tscn' # DONE
var spider = 'res://objects/enemies/spider/spider.tscn' # DONE
var spider_hang = 'res://objects/enemies/spider_hang/spider_hang.tscn' # DONE
#var tomb_lord = 'res://objects/enemies/tomb_lord/tomb_lord.tscn'
var ufo = 'res://objects/enemies/ufo/ufo.tscn' # DONE
var ufo_crash = 'res://objects/enemies/ufo_crash/ufo_crash.tscn' # DONE
#var vampire = 'res://objects/enemies/vampire/vampire.tscn'
#var yeti = 'res://objects/enemies/yeti/yeti.tscn'
#var yeti_king = 'res://objects/enemies/yeti_king/yeti_king.tscn'
var zombie = 'res://objects/enemies/zombie/zombie.tscn' # DONE


#init
#var check_box = 'res://objects/init/check_box/check_box.tscn'
#var check_box2 = 'res://objects/init/check_box2/check_box2.tscn'
#var check_box3 = 'res://objects/init/check_box3/check_box3.tscn'
#var check_box4 = 'res://objects/init/check_box4/check_box4.tscn'
#var joy_config_button = 'res://objects/init/joy_config_button/joy_config_button.tscn'
#var key_config_button = 'res://objects/init/key_config_button/key_config_button.tscn'
#var ok_button = 'res://objects/init/ok_button/ok_button.tscn'
#var radio_box = 'res://objects/init/radio_box/radio_box.tscn'
#var slider1 = 'res://objects/init/slider1/slider1.tscn'
#var slider2 = 'res://objects/init/slider2/slider2.tscn'
var slider_bg = 'res://objects/init/slider_bg/slider_bg.tscn' # DONE


#items
var arrow = 'res://objects/items/arrow/arrow.tscn' # DONE
var ball = 'res://objects/items/ball/ball.tscn' # DONE
var ball2 = 'res://objects/items/ball2/ball2.tscn' # DONE
var basketball = 'res://objects/items/basketball/basketball.tscn' # DONE
var bomb = 'res://objects/items/bomb/bomb.tscn' # DONE
var bow = 'res://objects/items/bow/bow.tscn' # DONE
var chain = 'res://objects/items/chain/chain.tscn' # DONE
var chain2 = 'res://objects/items/chain2/chain2.tscn' # DONE
var crystal_skull = 'res://objects/items/crystal_skull/crystal_skull.tscn' # DONE
#var dice = 'res://objects/items/dice/dice.tscn'
var fire_frog_bomb = 'res://objects/items/fire_frog_bomb/fire_frog_bomb.tscn' # DONE
var fish_bone = 'res://objects/items/fish_bone/fish_bone.tscn' # DONE
var flare = 'res://objects/items/flare/flare.tscn' # PROGRESS (fixed flare_spark spawning)
var gold_idol = 'res://objects/items/gold_idol/gold_idol.tscn' # DONE
#var jar = 'res://objects/items/jar/jar.tscn'
var lamp_item = 'res://objects/items/lamp_item/lamp_item.tscn' # DONE
var lamp_red_item = 'res://objects/items/lamp_red_item/lamp_red_item.tscn' # DONE
var machete = 'res://objects/items/machete/machete.tscn' # DONE
var machete_pre = 'res://objects/items/machete_pre/machete_pre.tscn' # DONE
var mattock = 'res://objects/items/mattock/mattock.tscn' # DONE
var mattock_head = 'res://objects/items/mattock_head/mattock_head.tscn' # DONE
var mattock_hit = 'res://objects/items/mattock_hit/mattock_hit.tscn' # DONE
var mattock_pre = 'res://objects/items/mattock_pre/mattock_pre.tscn' # DONE
var parachute = 'res://objects/items/parachute/parachute.tscn' # DONE
var pistol = 'res://objects/items/pistol/pistol.tscn' # DONE
var rock = 'res://objects/items/rock/rock.tscn' # DONE
var rope = 'res://objects/items/rope/rope.tscn' # PROGRESS (step seems to not be finished. may have been rope climbing bug I had before, so double check)
var rope_throw = 'res://objects/items/rope_throw/rope_throw.tscn' # PROGESS (step seems to not be finished)
var rope_top = 'res://objects/items/rope_top/rope_top.tscn' # DONE
var sceptre = 'res://objects/items/sceptre/sceptre.tscn' # DONE
var shotgun = 'res://objects/items/shotgun/shotgun.tscn' # DONE
#var skull = 'res://objects/items/skull/skull.tscn'
var slash = 'res://objects/items/slash/slash.tscn' # DONE
var teleporter = 'res://objects/items/teleporter/teleporter.tscn' # DONE
var web_cannon = 'res://objects/items/web_cannon/web_cannon.tscn' # DONE
var whip = 'res://objects/items/whip/whip.tscn' # DONE
var whip_pre = 'res://objects/items/whip_pre/whip_pre.tscn' # DONE


#level editor
var alien_boss_tile = 'res://objects/level editor/alien_boss_tile/alien_boss_tile.tscn' # DONE
var alien_tile = 'res://objects/level editor/alien_tile/alien_tile.tscn' # DONE
var bat_tile = 'res://objects/level editor/bat_tile/bat_tile.tscn' # DONE
#var bomb_bag_tile = 'res://objects/level editor/bomb_bag_tile/bomb_bag_tile.tscn' # DONE
var bomb_box_tile = 'res://objects/level editor/bomb_box_tile/bomb_box_tile.tscn' # DONE
var bomb_paste_tile = 'res://objects/level editor/bomb_paste_tile/bomb_paste_tile.tscn' # DONE
var bones_tile = 'res://objects/level editor/bones_tile/bones_tile.tscn' # DONE
var bow_tile = 'res://objects/level editor/bow_tile/bow_tile.tscn' # DONE
var cape_tile = 'res://objects/level editor/cape_tile/cape_tile.tscn' # DONE
var caveman_tile = 'res://objects/level editor/caveman_tile/caveman_tile.tscn' # DONE
var chest_tile = 'res://objects/level editor/chest_tile/chest_tile.tscn' # DONE
var compass_tile = 'res://objects/level editor/compass_tile/compass_tile.tscn' # DONE
var crate_tile = 'res://objects/level editor/crate_tile/crate_tile.tscn' # DONE
var crystal_skull_tile = 'res://objects/level editor/crystal_skull_tile/crystal_skull_tile.tscn' # DONE
var damsel_tile = 'res://objects/level editor/damsel_tile/damsel_tile.tscn' # DONE
var diamond_tile = 'res://objects/level editor/diamond_tile/diamond_tile.tscn' # DONE
#var edit_button = 'res://objects/level editor/edit_button/edit_button.tscn'
var emerald_big_tile = 'res://objects/level editor/emerald_big_tile/emerald_big_tile.tscn' # DONE
var fire_frog_tile = 'res://objects/level editor/fire_frog_tile/fire_frog_tile.tscn' # DONE
var frog_tile = 'res://objects/level editor/frog_tile/frog_tile.tscn' # DONE
var giant_spider_tile = 'res://objects/level editor/giant_spider_tile/giant_spider_tile.tscn' # DONE
var gloves_tile = 'res://objects/level editor/gloves_tile/gloves_tile.tscn' # DONE
var gold_bars_tile = 'res://objects/level editor/gold_bars_tile/gold_bars_tile.tscn' # DONE
var gold_bar_tile = 'res://objects/level editor/gold_bar_tile/gold_bar_tile.tscn' # DONE
var gold_idol_tile = 'res://objects/level editor/gold_idol_tile/gold_idol_tile.tscn' # DONE
var hawkman_tile = 'res://objects/level editor/hawkman_tile/hawkman_tile.tscn' # DONE
var ice_tile = 'res://objects/level editor/ice_tile/ice_tile.tscn' # DONE
var jar_tile = 'res://objects/level editor/jar_tile/jar_tile.tscn' # DONE
var jetpack_tile = 'res://objects/level editor/jetpack_tile/jetpack_tile.tscn' # DONE
var lava_tile = 'res://objects/level editor/lava_tile/lava_tile.tscn' # DONE
#var load_button = 'res://objects/level editor/load_button/load_button.tscn'
var machete_tile = 'res://objects/level editor/machete_tile/machete_tile.tscn' # DONE
var man_trap_tile = 'res://objects/level editor/man_trap_tile/man_trap_tile.tscn' # DONE
var mattock_tile = 'res://objects/level editor/mattock_tile/mattock_tile.tscn' # DONE
var mega_mouth_tile = 'res://objects/level editor/mega_mouth_tile/mega_mouth_tile.tscn' # DONE
var mitt_tile = 'res://objects/level editor/mitt_tile/mitt_tile.tscn' # DONE
var monkey_tile = 'res://objects/level editor/monkey_tile/monkey_tile.tscn' # DONE
#var new_button = 'res://objects/level editor/new_button/new_button.tscn'
var parachute_tile = 'res://objects/level editor/parachute_tile/parachute_tile.tscn' # DONE
var piranha_tile = 'res://objects/level editor/piranha_tile/piranha_tile.tscn' # DONE
var pistol_tile = 'res://objects/level editor/pistol_tile/pistol_tile.tscn' # DONE
var rock_tile = 'res://objects/level editor/rock_tile/rock_tile.tscn' # DONE
var rope_pile_tile = 'res://objects/level editor/rope_pile_tile/rope_pile_tile.tscn' # DONE
var ruby_big_tile = 'res://objects/level editor/ruby_big_tile/ruby_big_tile.tscn' # DONE
var sapphire_big_tile = 'res://objects/level editor/sapphire_big_tile/sapphire_big_tile.tscn' # DONE
var shopkeeper_tile = 'res://objects/level editor/shopkeeper_tile/shopkeeper_tile.tscn' # DONE
var shotgun_tile = 'res://objects/level editor/shotgun_tile/shotgun_tile.tscn' # DONE
var skeleton_tile = 'res://objects/level editor/skeleton_tile/skeleton_tile.tscn' # DONE
var smash_trap_tile = 'res://objects/level editor/smash_trap_tile/smash_trap_tile.tscn' # DONE
var snake_tile = 'res://objects/level editor/snake_tile/snake_tile.tscn' # DONE
var spear_trap_tile_bot = 'res://objects/level editor/spear_trap_tile_bot/spear_trap_tile_bot.tscn' # DONE
var spear_trap_tile_top = 'res://objects/level editor/spear_trap_tile_top/spear_trap_tile_top.tscn' # DONE
var spectacles_tile = 'res://objects/level editor/spectacles_tile/spectacles_tile.tscn' # DONE
var spider_tile = 'res://objects/level editor/spider_tile/spider_tile.tscn' # DONE
var spike_shoes_tile = 'res://objects/level editor/spike_shoes_tile/spike_shoes_tile.tscn' # DONE
var spring_shoes_tile = 'res://objects/level editor/spring_shoes_tile/spring_shoes_tile.tscn' # DONE
var spring_trap_tile = 'res://objects/level editor/spring_trap_tile/spring_trap_tile.tscn' # DONE
var teleporter_tile = 'res://objects/level editor/teleporter_tile/teleporter_tile.tscn' # DONE
#var test_button = 'res://objects/level editor/test_button/test_button.tscn'
var tomb_lord_tile = 'res://objects/level editor/tomb_lord_tile/tomb_lord_tile.tscn' # DONE
var ufo_tile = 'res://objects/level editor/ufo_tile/ufo_tile.tscn' # DONE
var vampire_tile = 'res://objects/level editor/vampire_tile/vampire_tile.tscn' # DONE
var water_tile = 'res://objects/level editor/water_tile/water_tile.tscn' # DONE
var web_cannon_tile = 'res://objects/level editor/web_cannon_tile/web_cannon_tile.tscn' # DONE
var web_tile = 'res://objects/level editor/web_tile/web_tile.tscn' # DONE
var yeti_king_tile = 'res://objects/level editor/yeti_king_tile/yeti_king_tile.tscn' # DONE
var yeti_tile = 'res://objects/level editor/yeti_tile/yeti_tile.tscn' # DONE
var zombie_tile = 'res://objects/level editor/zombie_tile/zombie_tile.tscn' # DONE


#other
var black = 'res://objects/other/black/black.tscn' # DONE
var black_bg = 'res://objects/other/black_bg/black_bg.tscn' # DONE
var cave_up = 'res://objects/other/cave_up/cave_up.tscn' # DONE
var hint_hand = 'res://objects/other/hint_hand/hint_hand.tscn' # PROGRESS
var menu_bottom = 'res://objects/other/menu_bottom/menu_bottom.tscn' # DONE
var menu_left = 'res://objects/other/menu_left/menu_left.tscn' # DONE
var menu_ll = 'res://objects/other/menu_ll/menu_ll.tscn' # DONE
var menu_lr = 'res://objects/other/menu_lr/menu_lr.tscn' # DONE
var menu_right = 'res://objects/other/menu_right/menu_right.tscn' # DONE
#var menu_sel = 'res://objects/other/menu_sel/menu_sel.tscn'
var menu_top = 'res://objects/other/menu_top/menu_top.tscn' # DONE
var menu_ul = 'res://objects/other/menu_ul/menu_ul.tscn' # DONE
var menu_ur = 'res://objects/other/menu_ur/menu_ur.tscn'
#var page_down = 'res://objects/other/page_down/page_down.tscn'
#var page_up = 'res://objects/other/page_up/page_up.tscn'
#var p_dummy = 'res://objects/other/p_dummy/p_dummy.tscn'
var p_dummy2 = 'res://objects/other/p_dummy2/p_dummy2.tscn' # DONE
var p_dummy3 = 'res://objects/other/p_dummy3/p_dummy3.tscn' # DONE (check for leftover test stuff)
var p_dummy4 = 'res://objects/other/p_dummy4/p_dummy4.tscn' # DONE
var p_dummy5 = 'res://objects/other/p_dummy5/p_dummy5.tscn' # DONE
var p_dummy6 = 'res://objects/other/p_dummy6/p_dummy6.tscn' # DONE
var wal_damsel = 'res://objects/other/wal_damsel/wal_damsel.tscn' # DONE


#other\end
var bg_end3 = 'res://objects/other/end/bg_end3/bg_end3.tscn' # DONE
var big_chest = 'res://objects/other/end/big_chest/big_chest.tscn' # DONE
var big_treasure = 'res://objects/other/end/big_treasure/big_treasure.tscn' # DONE
var end2_bg = 'res://objects/other/end/end2_bg/end2_bg.tscn' # DONE
var end_plat = 'res://objects/other/end/end_plat/end_plat.tscn' # DONE
var end_wall = 'res://objects/other/end/end_wall/end_wall.tscn' # DONE
var lava_spray = 'res://objects/other/end/lava_spray/lava_spray.tscn' # DONE
var player_sil = 'res://objects/other/end/player_sil/player_sil.tscn' # DONE
var treasure_sil = 'res://objects/other/end/treasure_sil/treasure_sil.tscn' # DONE


#other\intro
var bat_intro = 'res://objects/other/intro/bat_intro/bat_intro.tscn' # DONE (might need to check speed value?)
var camel = 'res://objects/other/intro/camel/camel.tscn' # DONE
var caravan = 'res://objects/other/intro/caravan/caravan.tscn' # DONE
var desert = 'res://objects/other/intro/desert/desert.tscn' # DONE
var desert2 = 'res://objects/other/intro/desert2/desert2.tscn' # DONE
var desert_scroll = 'res://objects/other/intro/desert_scroll/desert_scroll.tscn' # DONE
var desert_scroll2 = 'res://objects/other/intro/desert_scroll2/desert_scroll2.tscn' # DONE
var desert_top = 'res://objects/other/intro/desert_top/desert_top.tscn' # DONE
var desert_top_scroll = 'res://objects/other/intro/desert_top_scroll/desert_top_scroll.tscn' # DONE
var intro_bg = 'res://objects/other/intro/intro_bg/intro_bg.tscn' # DONE
var moon = 'res://objects/other/intro/moon/moon.tscn' # DONE
var palm_tree = 'res://objects/other/intro/palm_tree/palm_tree.tscn' # DONE
var palm_tree_dark = 'res://objects/other/intro/palm_tree_dark/palm_tree_dark.tscn' # DONE
var palm_tree_scroll = 'res://objects/other/intro/palm_tree_scroll/palm_tree_scroll.tscn' # DONE
var shrub = 'res://objects/other/intro/shrub/shrub.tscn' # DONE
var shrub_dark = 'res://objects/other/intro/shrub_dark/shrub_dark.tscn' # DONE
var shrub_scroll = 'res://objects/other/intro/shrub_scroll/shrub_scroll.tscn' # DONE


#other\title
var basket = 'res://objects/other/title/basket/basket.tscn' # DONE
var bat_target = 'res://objects/other/title/bat_target/bat_target.tscn' # DONE
var button_highscore = 'res://objects/other/title/button_highscore/button_highscore.tscn' # DONE
var copy = 'res://objects/other/title/copy/copy.tscn' # DONE
var level13_sign = 'res://objects/other/title/level13_sign/level13_sign.tscn' # DONE
var level5_sign = 'res://objects/other/title/level5_sign/level5_sign.tscn' # DONE
var level9_sign = 'res://objects/other/title/level9_sign/level9_sign.tscn' # DONE
var multi_trophy = 'res://objects/other/title/multi_trophy/multi_trophy.tscn' # DONE
var new = 'res://objects/other/title/new/new.tscn' # DONE
var quit_sign = 'res://objects/other/title/quit_sign/quit_sign.tscn' # DONE
var reset_sign = 'res://objects/other/title/reset_sign/reset_sign.tscn' # DONE
var rim = 'res://objects/other/title/rim/rim.tscn' # DONE
var rim_deflect = 'res://objects/other/title/rim_deflect/rim_deflect.tscn' # DONE
var scores_sign = 'res://objects/other/title/scores_sign/scores_sign.tscn' # DONE
var start_sign = 'res://objects/other/title/start_sign/start_sign.tscn' # DONE
var target = 'res://objects/other/title/target/target.tscn' # DONE
var title_bg = 'res://objects/other/title/title_bg/title_bg.tscn' # DONE
var title_logo = 'res://objects/other/title/title_logo/title_logo.tscn' # DONE
var trophy = 'res://objects/other/title/trophy/trophy.tscn' # DONE
var tutorial_sign = 'res://objects/other/title/tutorial_sign/tutorial_sign.tscn' # DONE
var x_change = 'res://objects/other/title/x_change/x_change.tscn' # DONE
var x_change2 = 'res://objects/other/title/x_change2/x_change2.tscn' # DONE
var x_end = 'res://objects/other/title/x_end/x_end.tscn' # DONE
var x_moon = 'res://objects/other/title/x_moon/x_moon.tscn' # DONE
var x_scores = 'res://objects/other/title/x_scores/x_scores.tscn' # DONE
var x_shortcut13 = 'res://objects/other/title/x_shortcut13/x_shortcut13.tscn' # DONE
var x_shortcut5 = 'res://objects/other/title/x_shortcut5/x_shortcut5.tscn' # DONE
var x_shortcut9 = 'res://objects/other/title/x_shortcut9/x_shortcut9.tscn' # DONE
var x_stars = 'res://objects/other/title/x_stars/x_stars.tscn' # DONE
var x_start = 'res://objects/other/title/x_start/x_start.tscn' # DONE
var x_sun = 'res://objects/other/title/x_sun/x_sun.tscn' # DONE
var x_title = 'res://objects/other/title/x_title/x_title.tscn' # DONE
var x_tutorial = 'res://objects/other/title/x_tutorial/x_tutorial.tscn' # DONE


#traps
var arrow_repeater_l = 'res://objects/traps/arrow_repeater_l/arrow_repeater_l.tscn' # DONE
var arrow_repeater_r = 'res://objects/traps/arrow_repeater_r/arrow_repeater_r.tscn' # DONE
var arrow_trap_left = 'res://objects/traps/arrow_trap_left/arrow_trap_left.tscn' # DONE
var arrow_trap_left_lit = 'res://objects/traps/arrow_trap_left_lit/arrow_trap_left_lit.tscn' # DONE
var arrow_trap_right = 'res://objects/traps/arrow_trap_right/arrow_trap_right.tscn' # DONE
var arrow_trap_right_lit = 'res://objects/traps/arrow_trap_right_lit/arrow_trap_right_lit.tscn' # DONE
#var arrow_trap_test = 'res://objects/traps/arrow_trap_test/arrow_trap_test.tscn'
var boulder = 'res://objects/traps/boulder/boulder.tscn' # DONE
var ceiling_trap = 'res://objects/traps/ceiling_trap/ceiling_trap.tscn' # DONE
var door = 'res://objects/traps/door/door.tscn' # DONE
var giant_tiki_head = 'res://objects/traps/giant_tiki_head/giant_tiki_head.tscn' # DONE
var smash_trap = 'res://objects/traps/smash_trap/smash_trap.tscn' # DONE
var smash_trap_lit = 'res://objects/traps/smash_trap_lit/smash_trap_lit.tscn' # DONE
var spears_left = 'res://objects/traps/spears_left/spears_left.tscn' # DONE
var spear_trap_bottom = 'res://objects/traps/spear_trap_bottom/spear_trap_bottom.tscn' # DONE
var spear_trap_lit = 'res://objects/traps/spear_trap_lit/spear_trap_lit.tscn' # DONE
var spear_trap_top = 'res://objects/traps/spear_trap_top/spear_trap_top.tscn' # DONE
var spikes = 'res://objects/traps/spikes/spikes.tscn' # DONE
var spring_trap = 'res://objects/traps/spring_trap/spring_trap.tscn' # DONE
var temp = 'res://objects/traps/temp/temp.tscn' # DONE
var thwomp_trap = 'res://objects/traps/thwomp_trap/thwomp_trap.tscn' # DONE
var trap_block = 'res://objects/traps/trap_block/trap_block.tscn' # DONE
