extends Node
class_name Objects

#objects
const bricks = 'res://objects/bricks/bricks.tscn' # DONE
const credits1 = 'res://objects/credits1/credits1.tscn' # DONE
const credits2 = 'res://objects/credits2/credits2.tscn' # DONE
#const curs_obj = 'res://objects/curs_obj/curs_obj.tscn'
const end = 'res://objects/end/end.tscn' # DONE
const end2 = 'res://objects/end2/end2.tscn' # DONE
const end3 = 'res://objects/end3/end3.tscn' # DONE
const end_custom = 'res://objects/end_custom/end_custom.tscn' # DONE
const final_boss = 'res://objects/final_boss/final_boss.tscn' # DONE
const game = 'res://objects/game/game.tscn' # DONE
const gamepad = 'res://objects/gamepad/gamepad.tscn' # DONE
const globals = 'res://objects/globals/globals.tscn' # DONE
const highscores = 'res://objects/highscores/highscores.tscn' # DONE
const intro = 'res://objects/intro/intro.tscn' # DONE
#const joy_config = 'res://objects/joy_config/joy_config.tscn'
#const key_config = 'res://objects/key_config/key_config.tscn'
const level = 'res://objects/level/level.tscn' # DONE
#const level_editor = 'res://objects/level_editor/level_editor.tscn'
#const load_level = 'res://objects/load_level/load_level.tscn'
const moon_room = 'res://objects/moon_room/moon_room.tscn' # DONE
const music = 'res://objects/music/music.tscn' # DONE
const player1 = 'res://objects/player1/player1.tscn' # PROGRESS (need to implement collision_with_blood)
const room = 'res://objects/room/room.tscn' # DONE
const screen = 'res://objects/screen/screen.tscn' # PROGRESS (need to finish begin step)
const sprite = 'res://objects/sprite/sprite.tscn' # DONE
const stars_room = 'res://objects/stars_room/stars_room.tscn' # DONE
const sun_room = 'res://objects/sun_room/sun_room.tscn' # DONE
const title = 'res://objects/title/title.tscn' # PROGRESS
const transition = 'res://objects/transition/transition.tscn' # DONE


#basis
const backdrop = 'res://objects/basis/backdrop/backdrop.tscn' # DONE
const character = 'res://objects/basis/character/character.tscn' # DONE
const detritus = 'res://objects/basis/detritus/detritus.tscn' # DONE
const drawn_sprite = 'res://objects/basis/drawn_sprite/drawn_sprite.tscn' # DONE
const enemy = 'res://objects/basis/enemy/enemy.tscn' # DONE ---[FLAG] finish "outside room"
const foreground = 'res://objects/basis/foreground/foreground.tscn' # DONE
const frill = 'res://objects/basis/frill/frill.tscn' # DONE
const item = 'res://objects/basis/item/item.tscn' # DONE
const ladder = 'res://objects/basis/ladder/ladder.tscn' # DONE
const menu = 'res://objects/basis/menu/menu.tscn' # DONE
const moveable_solid = 'res://objects/basis/moveable_solid/moveable_solid.tscn' # DONE
const moving_solid = 'res://objects/basis/moving_solid/moving_solid.tscn' # DONE
const platform = 'res://objects/basis/platform/platform.tscn' # DONE
const rubble_piece = 'res://objects/basis/rubble_piece/rubble_piece.tscn' # DONE
const solid = 'res://objects/basis/solid/solid.tscn' # DONE
const treasure = 'res://objects/basis/treasure/treasure.tscn' # DONE
const water = 'res://objects/basis/water/water.tscn' # DONE


#blocks
const alien_ship = 'res://objects/blocks/alien_ship/alien_ship.tscn' # DONE
const alien_ship_floor = 'res://objects/blocks/alien_ship_floor/alien_ship_floor.tscn' # DONE
const altar_left = 'res://objects/blocks/altar_left/altar_left.tscn' # DONE
const altar_right = 'res://objects/blocks/altar_right/altar_right.tscn' # DONE
const black_fade_up = 'res://objects/blocks/black_fade_up/black_fade_up.tscn' # DONE
const block = 'res://objects/blocks/block/block.tscn' # DONE
const brick = 'res://objects/blocks/brick/brick.tscn' # DONE
const brick_smooth = 'res://objects/blocks/brick_smooth/brick_smooth.tscn' # DONE
const cave_bg = 'res://objects/blocks/cave_bg/cave_bg.tscn' # DONE
const cave_bg2 = 'res://objects/blocks/cave_bg2/cave_bg2.tscn' # DONE
const cave_bg_entrance = 'res://objects/blocks/cave_bg_entrance/cave_bg_entrance.tscn' # DONE
const dark = 'res://objects/blocks/dark/dark.tscn' # DONE
const dark_fall = 'res://objects/blocks/dark_fall/dark_fall.tscn' # DONE
const entrance = 'res://objects/blocks/entrance/entrance.tscn' # PROGRESS
const exit = 'res://objects/blocks/exit/exit.tscn' #--- TODO: implemented partially
const frozen_caveman = 'res://objects/blocks/frozen_caveman/frozen_caveman.tscn' # DONE
const gold = 'res://objects/blocks/gold/gold.tscn' # DONE
const gold_big = 'res://objects/blocks/gold_big/gold_big.tscn' # DONE
const gold_door = 'res://objects/blocks/gold_door/gold_door.tscn' # DONE
const grave = 'res://objects/blocks/grave/grave.tscn' # DONE
const hard_block = 'res://objects/blocks/hard_block/hard_block.tscn' # DONE
const ice = 'res://objects/blocks/ice/ice.tscn' # DONE
const ice_block = 'res://objects/blocks/ice_block/ice_block.tscn' # DONE
const ice_bottom = 'res://objects/blocks/ice_bottom/ice_bottom.tscn' # DONE
const kali_head = 'res://objects/blocks/kali_head/kali_head.tscn' # DONE
const ladder_orange = 'res://objects/blocks/ladder_orange/ladder_orange.tscn' # DONE
const ladder_top = 'res://objects/blocks/ladder_top/ladder_top.tscn' # DONE
const lamp = 'res://objects/blocks/lamp/lamp.tscn' # DONE
const lamp_red = 'res://objects/blocks/lamp_red/lamp_red.tscn' # DONE
const lava = 'res://objects/blocks/lava/lava.tscn' # DONE
const lava_solid = 'res://objects/blocks/lava_solid/lava_solid.tscn' # DONE
const leaves = 'res://objects/blocks/leaves/leaves.tscn' # DONE
const leaves_tile = 'res://objects/blocks/leaves_tile/leaves_tile.tscn' # DONE
const lush = 'res://objects/blocks/lush/lush.tscn' # DONE
const moai = 'res://objects/blocks/moai/moai.tscn' # DONE
const moai2 = 'res://objects/blocks/moai2/moai2.tscn' # DONE
const moai3 = 'res://objects/blocks/moai3/moai3.tscn' # DONE
const moai_inside = 'res://objects/blocks/moai_inside/moai_inside.tscn' # DONE
const msg_sign = 'res://objects/blocks/msg_sign/msg_sign.tscn' # DONE
const push_block = 'res://objects/blocks/push_block/push_block.tscn' # DONE
const sac_altar_left = 'res://objects/blocks/sac_altar_left/sac_altar_left.tscn' # DONE
const sac_altar_right = 'res://objects/blocks/sac_altar_right/sac_altar_right.tscn' # DONE
const sign = 'res://objects/blocks/sign/sign.tscn' # DONE
const splash = 'res://objects/blocks/splash/splash.tscn' # DONE
const temple = 'res://objects/blocks/temple/temple.tscn' # DONE
const temple_fake = 'res://objects/blocks/temple_fake/temple_fake.tscn' # DONE
const thin_ice = 'res://objects/blocks/thin_ice/thin_ice.tscn' # DONE
const tiki_torch = 'res://objects/blocks/tiki_torch/tiki_torch.tscn' # DONE
const tree = 'res://objects/blocks/tree/tree.tscn' # DONE
const tree_branch = 'res://objects/blocks/tree_branch/tree_branch.tscn' # DONE
const tree_branch_tile = 'res://objects/blocks/tree_branch_tile/tree_branch_tile.tscn' # DONE
const tree_tile = 'res://objects/blocks/tree_tile/tree_tile.tscn' # DONE
const vine = 'res://objects/blocks/vine/vine.tscn' # DONE
const vine_top = 'res://objects/blocks/vine_top/vine_top.tscn' # DONE
const water_swim = 'res://objects/blocks/water_swim/water_swim.tscn' # DONE
const x_gold = 'res://objects/blocks/x_gold/x_gold.tscn' # DONE
const x_market = 'res://objects/blocks/x_market/x_market.tscn' # DONE
const xoc_block = 'res://objects/blocks/xoc_block/xoc_block.tscn' # DONE


#characters
const damsel = 'res://objects/characters/damsel/damsel.tscn' # DONE
const damsel_kiss = 'res://objects/characters/damsel_kiss/damsel_kiss.tscn' # DONE
const shopkeeper = 'res://objects/characters/shopkeeper/shopkeeper.tscn' # DONE
const shopkeeper2 = 'res://objects/characters/shopkeeper2/shopkeeper2.tscn' # DONE
const tunnel_man = 'res://objects/characters/tunnel_man/tunnel_man.tscn' # DONE
const yell_help = 'res://objects/characters/yell_help/yell_help.tscn' # DONE


#collectibles
const ankh = 'res://objects/collectibles/ankh/ankh.tscn' # DONE
const bomb_bag = 'res://objects/collectibles/bomb_bag/bomb_bag.tscn' # DONE
const bomb_box = 'res://objects/collectibles/bomb_box/bomb_box.tscn' # DONE
const bones = 'res://objects/collectibles/bones/bones.tscn' # DONE
const cape = 'res://objects/collectibles/cape/cape.tscn' # DONE
const cape_pickup = 'res://objects/collectibles/cape_pickup/cape_pickup.tscn' # DONE
const chest = 'res://objects/collectibles/chest/chest.tscn' # DONE
const compass = 'res://objects/collectibles/compass/compass.tscn' # DONE
const crate = 'res://objects/collectibles/crate/crate.tscn' # DONE
const crown = 'res://objects/collectibles/crown/crown.tscn' # DONE
const diamond = 'res://objects/collectibles/diamond/diamond.tscn' # DONE
const emerald = 'res://objects/collectibles/emerald/emerald.tscn' # DONE
const emerald_big = 'res://objects/collectibles/emerald_big/emerald_big.tscn' # DONE
const fake_bones = 'res://objects/collectibles/fake_bones/fake_bones.tscn' # DONE
const fire_frog_armed = 'res://objects/collectibles/fire_frog_armed/fire_frog_armed.tscn' # DONE
const flare_crate = 'res://objects/collectibles/flare_crate/flare_crate.tscn' # DONE
const gloves = 'res://objects/collectibles/gloves/gloves.tscn' # DONE
const gold_bar = 'res://objects/collectibles/gold_bar/gold_bar.tscn' # DONE
const gold_bars = 'res://objects/collectibles/gold_bars/gold_bars.tscn' # DONE
const gold_chunk = 'res://objects/collectibles/gold_chunk/gold_chunk.tscn' # DONE
const gold_nugget = 'res://objects/collectibles/gold_nugget/gold_nugget.tscn' # DONE
const jetpack = 'res://objects/collectibles/jetpack/jetpack.tscn' # DONE
const jordans = 'res://objects/collectibles/jordans/jordans.tscn' # DONE
const kapala = 'res://objects/collectibles/kapala/kapala.tscn' # DONE
const key = 'res://objects/collectibles/key/key.tscn' # DONE
const locked_chest = 'res://objects/collectibles/locked_chest/locked_chest.tscn' # DONE
const mitt = 'res://objects/collectibles/mitt/mitt.tscn' # DONE
const para_pickup = 'res://objects/collectibles/para_pickup/para_pickup.tscn' # DONE
const para_used = 'res://objects/collectibles/para_used/para_used.tscn' # DONE
const paste = 'res://objects/collectibles/paste/paste.tscn' # DONE
const rope_bag = 'res://objects/collectibles/rope_bag/rope_bag.tscn' # DONE
const rope_pile = 'res://objects/collectibles/rope_pile/rope_pile.tscn' # DONE
const ruby = 'res://objects/collectibles/ruby/ruby.tscn' # DONE
const ruby_big = 'res://objects/collectibles/ruby_big/ruby_big.tscn' # DONE
const sapphire = 'res://objects/collectibles/sapphire/sapphire.tscn' # DONE
const sapphire_big = 'res://objects/collectibles/sapphire_big/sapphire_big.tscn' # DONE
const spectacles = 'res://objects/collectibles/spectacles/spectacles.tscn' # DONE
const spike_shoes = 'res://objects/collectibles/spike_shoes/spike_shoes.tscn' # DONE
const spring_shoes = 'res://objects/collectibles/spring_shoes/spring_shoes.tscn' # DONE
const udjat_eye = 'res://objects/collectibles/udjat_eye/udjat_eye.tscn' # DONE


#effects
const big_collect = 'res://objects/effects/big_collect/big_collect.tscn' # DONE
const blood = 'res://objects/effects/blood/blood.tscn' # DONE
const blood_spark = 'res://objects/effects/blood_spark/blood_spark.tscn' # DONE
const blood_trail = 'res://objects/effects/blood_trail/blood_trail.tscn' # DONE
const bone = 'res://objects/effects/bone/bone.tscn' # DONE
const bubble = 'res://objects/effects/bubble/bubble.tscn' # DONE
const bullet = 'res://objects/effects/bullet/bullet.tscn' # DONE
const burn = 'res://objects/effects/burn/burn.tscn' # DONE
const drip = 'res://objects/effects/drip/drip.tscn' # DONE
const explosion = 'res://objects/effects/explosion/explosion.tscn' # DONE
const flame = 'res://objects/effects/flame/flame.tscn' # DONE
const flame_trail = 'res://objects/effects/flame_trail/flame_trail.tscn' # DONE
const flare_spark = 'res://objects/effects/flare_spark/flare_spark.tscn' # DONE
const fly = 'res://objects/effects/fly/fly.tscn' # DONE
const heart = 'res://objects/effects/heart/heart.tscn' # DONE
const items_get = 'res://objects/effects/items_get/items_get.tscn' # DONE
const laser = 'res://objects/effects/laser/laser.tscn' # DONE
const laser_explode = 'res://objects/effects/laser_explode/laser_explode.tscn' # DONE
const laser_trail = 'res://objects/effects/laser_trail/laser_trail.tscn' # DONE
const lava_drip = 'res://objects/effects/lava_drip/lava_drip.tscn' # DONE
const leaf = 'res://objects/effects/leaf/leaf.tscn' # DONE
const poof = 'res://objects/effects/poof/poof.tscn' # DONE
const psychic_create = 'res://objects/effects/psychic_create/psychic_create.tscn' # DONE
const psychic_create2 = 'res://objects/effects/psychic_create2/psychic_create2.tscn' # DONE
const psychic_create_p = 'res://objects/effects/psychic_create_p/psychic_create_p.tscn' # DONE
const psychic_wave = 'res://objects/effects/psychic_wave/psychic_wave.tscn' # DONE
const psychic_wave_p = 'res://objects/effects/psychic_wave_p/psychic_wave_p.tscn' # DONE
const rope_burn = 'res://objects/effects/rope_burn/rope_burn.tscn' # DONE
const rubble = 'res://objects/effects/rubble/rubble.tscn' # DONE
const rubble_dark = 'res://objects/effects/rubble_dark/rubble_dark.tscn' # DONE
const rubble_dark_small = 'res://objects/effects/rubble_dark_small/rubble_dark_small.tscn' # PROGRESS (have to do outside room function)
const rubble_small = 'res://objects/effects/rubble_small/rubble_small.tscn' # DONE
const shotgun_blast_left = 'res://objects/effects/shotgun_blast_left/shotgun_blast_left.tscn' # DONE
const shotgun_blast_right = 'res://objects/effects/shotgun_blast_right/shotgun_blast_right.tscn' # DONE
const small_collect = 'res://objects/effects/small_collect/small_collect.tscn' # DONE
const smoke_puff = 'res://objects/effects/smoke_puff/smoke_puff.tscn' # DONE
const volcano_flame = 'res://objects/effects/volcano_flame/volcano_flame.tscn' # DONE
const web = 'res://objects/effects/web/web.tscn' # DONE
const web_ball = 'res://objects/effects/web_ball/web_ball.tscn' # DONE
const yellow_ball = 'res://objects/effects/yellow_ball/yellow_ball.tscn' # DONE
const yellow_trail = 'res://objects/effects/yellow_trail/yellow_trail.tscn' # DONE


#enemies
const alien = 'res://objects/enemies/alien/alien.tscn' # DONE
const alien_boss = 'res://objects/enemies/alien_boss/alien_boss.tscn' # DONE
const alien_eject = 'res://objects/enemies/alien_eject/alien_eject.tscn' # DONE
const barrier = 'res://objects/enemies/barrier/barrier.tscn' # DONE
const barrier_emitter = 'res://objects/enemies/barrier_emitter/barrier_emitter.tscn' # DONE
const bat = 'res://objects/enemies/bat/bat.tscn' # DONE
const caveman = 'res://objects/enemies/caveman/caveman.tscn' # DONE
const caveman_worship = 'res://objects/enemies/caveman_worship/caveman_worship.tscn' # DONE
const dead_fish = 'res://objects/enemies/dead_fish/dead_fish.tscn' # DONE
const enemy_sight = 'res://objects/enemies/enemy_sight/enemy_sight.tscn' # DONE
const entrance_check = 'res://objects/enemies/entrance_check/entrance_check.tscn' # DONE
const fire_frog = 'res://objects/enemies/fire_frog/fire_frog.tscn' # DONE
const frog = 'res://objects/enemies/frog/frog.tscn' # DONE
const ghost = 'res://objects/enemies/ghost/ghost.tscn' # DONE
const giant_spider = 'res://objects/enemies/giant_spider/giant_spider.tscn' # DONE
const giant_spider_hang = 'res://objects/enemies/giant_spider_hang/giant_spider_hang.tscn' # DONE
const hawkman = 'res://objects/enemies/hawkman/hawkman.tscn' # DONE
const hawkman_worship = 'res://objects/enemies/hawkman_worship/hawkman_worship.tscn' # DONE
const jaws = 'res://objects/enemies/jaws/jaws.tscn' # DONE
const magma = 'res://objects/enemies/magma/magma.tscn' # DONE
const magma_man = 'res://objects/enemies/magma_man/magma_man.tscn' # DONE
const magma_trail = 'res://objects/enemies/magma_trail/magma_trail.tscn' # DONE
const man_trap = 'res://objects/enemies/man_trap/man_trap.tscn' # DONE
const monkey = 'res://objects/enemies/monkey/monkey.tscn' # DONE
const olmec = 'res://objects/enemies/olmec/olmec.tscn' # DONE
const olmec_debris = 'res://objects/enemies/olmec_debris/olmec_debris.tscn' # DONE
const olmec_slam = 'res://objects/enemies/olmec_slam/olmec_slam.tscn' # DONE
const piranha = 'res://objects/enemies/piranha/piranha.tscn' # DONE
const scarab = 'res://objects/enemies/scarab/scarab.tscn' # DONE
const skeleton = 'res://objects/enemies/skeleton/skeleton.tscn' # DONE
const snake = 'res://objects/enemies/snake/snake.tscn' # DONE
const spider = 'res://objects/enemies/spider/spider.tscn' # DONE
const spider_hang = 'res://objects/enemies/spider_hang/spider_hang.tscn' # DONE
const tomb_lord = 'res://objects/enemies/tomb_lord/tomb_lord.tscn' # DONE
const ufo = 'res://objects/enemies/ufo/ufo.tscn' # DONE
const ufo_crash = 'res://objects/enemies/ufo_crash/ufo_crash.tscn' # DONE
const vampire = 'res://objects/enemies/vampire/vampire.tscn' # DONE
const yeti = 'res://objects/enemies/yeti/yeti.tscn' # DONE
const yeti_king = 'res://objects/enemies/yeti_king/yeti_king.tscn' # DONE
const zombie = 'res://objects/enemies/zombie/zombie.tscn' # DONE


#init
#const check_box = 'res://objects/init/check_box/check_box.tscn'
#const check_box2 = 'res://objects/init/check_box2/check_box2.tscn'
#const check_box3 = 'res://objects/init/check_box3/check_box3.tscn'
#const check_box4 = 'res://objects/init/check_box4/check_box4.tscn'
#const joy_config_button = 'res://objects/init/joy_config_button/joy_config_button.tscn'
#const key_config_button = 'res://objects/init/key_config_button/key_config_button.tscn'
#const ok_button = 'res://objects/init/ok_button/ok_button.tscn'
#const radio_box = 'res://objects/init/radio_box/radio_box.tscn'
#const slider1 = 'res://objects/init/slider1/slider1.tscn'
#const slider2 = 'res://objects/init/slider2/slider2.tscn'
const slider_bg = 'res://objects/init/slider_bg/slider_bg.tscn' # DONE


#items
const arrow = 'res://objects/items/arrow/arrow.tscn' # DONE
const ball = 'res://objects/items/ball/ball.tscn' # DONE
const ball2 = 'res://objects/items/ball2/ball2.tscn' # DONE
const basketball = 'res://objects/items/basketball/basketball.tscn' # DONE
const bomb = 'res://objects/items/bomb/bomb.tscn' # DONE
const bow = 'res://objects/items/bow/bow.tscn' # DONE
const chain = 'res://objects/items/chain/chain.tscn' # DONE
const chain2 = 'res://objects/items/chain2/chain2.tscn' # DONE
const crystal_skull = 'res://objects/items/crystal_skull/crystal_skull.tscn' # DONE
const dice = 'res://objects/items/dice/dice.tscn' # DONE
const fire_frog_bomb = 'res://objects/items/fire_frog_bomb/fire_frog_bomb.tscn' # DONE
const fish_bone = 'res://objects/items/fish_bone/fish_bone.tscn' # DONE
const flare = 'res://objects/items/flare/flare.tscn' # DONE
const gold_idol = 'res://objects/items/gold_idol/gold_idol.tscn' # DONE
const jar = 'res://objects/items/jar/jar.tscn' # DONE
const lamp_item = 'res://objects/items/lamp_item/lamp_item.tscn' # DONE
const lamp_red_item = 'res://objects/items/lamp_red_item/lamp_red_item.tscn' # DONE
const machete = 'res://objects/items/machete/machete.tscn' # DONE
const machete_pre = 'res://objects/items/machete_pre/machete_pre.tscn' # DONE
const mattock = 'res://objects/items/mattock/mattock.tscn' # DONE
const mattock_head = 'res://objects/items/mattock_head/mattock_head.tscn' # DONE
const mattock_hit = 'res://objects/items/mattock_hit/mattock_hit.tscn' # DONE
const mattock_pre = 'res://objects/items/mattock_pre/mattock_pre.tscn' # DONE
const parachute = 'res://objects/items/parachute/parachute.tscn' # DONE
const pistol = 'res://objects/items/pistol/pistol.tscn' # DONE
const rock = 'res://objects/items/rock/rock.tscn' # DONE
const rope = 'res://objects/items/rope/rope.tscn' # PROGRESS (step seems to not be finished. may have been rope climbing bug I had before, so double check)
const rope_throw = 'res://objects/items/rope_throw/rope_throw.tscn' # PROGESS (step seems to not be finished)
const rope_top = 'res://objects/items/rope_top/rope_top.tscn' # DONE
const sceptre = 'res://objects/items/sceptre/sceptre.tscn' # DONE
const shotgun = 'res://objects/items/shotgun/shotgun.tscn' # DONE
const skull = 'res://objects/items/skull/skull.tscn' # DONE
const slash = 'res://objects/items/slash/slash.tscn' # DONE
const teleporter = 'res://objects/items/teleporter/teleporter.tscn' # DONE
const web_cannon = 'res://objects/items/web_cannon/web_cannon.tscn' # DONE
const whip = 'res://objects/items/whip/whip.tscn' # DONE
const whip_pre = 'res://objects/items/whip_pre/whip_pre.tscn' # DONE


#level editor
const alien_boss_tile = 'res://objects/level editor/alien_boss_tile/alien_boss_tile.tscn' # DONE
const alien_tile = 'res://objects/level editor/alien_tile/alien_tile.tscn' # DONE
const bat_tile = 'res://objects/level editor/bat_tile/bat_tile.tscn' # DONE
#const bomb_bag_tile = 'res://objects/level editor/bomb_bag_tile/bomb_bag_tile.tscn' # DONE
const bomb_box_tile = 'res://objects/level editor/bomb_box_tile/bomb_box_tile.tscn' # DONE
const bomb_paste_tile = 'res://objects/level editor/bomb_paste_tile/bomb_paste_tile.tscn' # DONE
const bones_tile = 'res://objects/level editor/bones_tile/bones_tile.tscn' # DONE
const bow_tile = 'res://objects/level editor/bow_tile/bow_tile.tscn' # DONE
const cape_tile = 'res://objects/level editor/cape_tile/cape_tile.tscn' # DONE
const caveman_tile = 'res://objects/level editor/caveman_tile/caveman_tile.tscn' # DONE
const chest_tile = 'res://objects/level editor/chest_tile/chest_tile.tscn' # DONE
const compass_tile = 'res://objects/level editor/compass_tile/compass_tile.tscn' # DONE
const crate_tile = 'res://objects/level editor/crate_tile/crate_tile.tscn' # DONE
const crystal_skull_tile = 'res://objects/level editor/crystal_skull_tile/crystal_skull_tile.tscn' # DONE
const damsel_tile = 'res://objects/level editor/damsel_tile/damsel_tile.tscn' # DONE
const diamond_tile = 'res://objects/level editor/diamond_tile/diamond_tile.tscn' # DONE
#const edit_button = 'res://objects/level editor/edit_button/edit_button.tscn'
const emerald_big_tile = 'res://objects/level editor/emerald_big_tile/emerald_big_tile.tscn' # DONE
const fire_frog_tile = 'res://objects/level editor/fire_frog_tile/fire_frog_tile.tscn' # DONE
const frog_tile = 'res://objects/level editor/frog_tile/frog_tile.tscn' # DONE
const giant_spider_tile = 'res://objects/level editor/giant_spider_tile/giant_spider_tile.tscn' # DONE
const gloves_tile = 'res://objects/level editor/gloves_tile/gloves_tile.tscn' # DONE
const gold_bars_tile = 'res://objects/level editor/gold_bars_tile/gold_bars_tile.tscn' # DONE
const gold_bar_tile = 'res://objects/level editor/gold_bar_tile/gold_bar_tile.tscn' # DONE
const gold_idol_tile = 'res://objects/level editor/gold_idol_tile/gold_idol_tile.tscn' # DONE
const hawkman_tile = 'res://objects/level editor/hawkman_tile/hawkman_tile.tscn' # DONE
const ice_tile = 'res://objects/level editor/ice_tile/ice_tile.tscn' # DONE
const jar_tile = 'res://objects/level editor/jar_tile/jar_tile.tscn' # DONE
const jetpack_tile = 'res://objects/level editor/jetpack_tile/jetpack_tile.tscn' # DONE
const lava_tile = 'res://objects/level editor/lava_tile/lava_tile.tscn' # DONE
#const load_button = 'res://objects/level editor/load_button/load_button.tscn'
const machete_tile = 'res://objects/level editor/machete_tile/machete_tile.tscn' # DONE
const man_trap_tile = 'res://objects/level editor/man_trap_tile/man_trap_tile.tscn' # DONE
const mattock_tile = 'res://objects/level editor/mattock_tile/mattock_tile.tscn' # DONE
const mega_mouth_tile = 'res://objects/level editor/mega_mouth_tile/mega_mouth_tile.tscn' # DONE
const mitt_tile = 'res://objects/level editor/mitt_tile/mitt_tile.tscn' # DONE
const monkey_tile = 'res://objects/level editor/monkey_tile/monkey_tile.tscn' # DONE
#const new_button = 'res://objects/level editor/new_button/new_button.tscn'
const parachute_tile = 'res://objects/level editor/parachute_tile/parachute_tile.tscn' # DONE
const piranha_tile = 'res://objects/level editor/piranha_tile/piranha_tile.tscn' # DONE
const pistol_tile = 'res://objects/level editor/pistol_tile/pistol_tile.tscn' # DONE
const rock_tile = 'res://objects/level editor/rock_tile/rock_tile.tscn' # DONE
const rope_pile_tile = 'res://objects/level editor/rope_pile_tile/rope_pile_tile.tscn' # DONE
const ruby_big_tile = 'res://objects/level editor/ruby_big_tile/ruby_big_tile.tscn' # DONE
const sapphire_big_tile = 'res://objects/level editor/sapphire_big_tile/sapphire_big_tile.tscn' # DONE
const shopkeeper_tile = 'res://objects/level editor/shopkeeper_tile/shopkeeper_tile.tscn' # DONE
const shotgun_tile = 'res://objects/level editor/shotgun_tile/shotgun_tile.tscn' # DONE
const skeleton_tile = 'res://objects/level editor/skeleton_tile/skeleton_tile.tscn' # DONE
const smash_trap_tile = 'res://objects/level editor/smash_trap_tile/smash_trap_tile.tscn' # DONE
const snake_tile = 'res://objects/level editor/snake_tile/snake_tile.tscn' # DONE
const spear_trap_tile_bot = 'res://objects/level editor/spear_trap_tile_bot/spear_trap_tile_bot.tscn' # DONE
const spear_trap_tile_top = 'res://objects/level editor/spear_trap_tile_top/spear_trap_tile_top.tscn' # DONE
const spectacles_tile = 'res://objects/level editor/spectacles_tile/spectacles_tile.tscn' # DONE
const spider_tile = 'res://objects/level editor/spider_tile/spider_tile.tscn' # DONE
const spike_shoes_tile = 'res://objects/level editor/spike_shoes_tile/spike_shoes_tile.tscn' # DONE
const spring_shoes_tile = 'res://objects/level editor/spring_shoes_tile/spring_shoes_tile.tscn' # DONE
const spring_trap_tile = 'res://objects/level editor/spring_trap_tile/spring_trap_tile.tscn' # DONE
const teleporter_tile = 'res://objects/level editor/teleporter_tile/teleporter_tile.tscn' # DONE
#const test_button = 'res://objects/level editor/test_button/test_button.tscn'
const tomb_lord_tile = 'res://objects/level editor/tomb_lord_tile/tomb_lord_tile.tscn' # DONE
const ufo_tile = 'res://objects/level editor/ufo_tile/ufo_tile.tscn' # DONE
const vampire_tile = 'res://objects/level editor/vampire_tile/vampire_tile.tscn' # DONE
const water_tile = 'res://objects/level editor/water_tile/water_tile.tscn' # DONE
const web_cannon_tile = 'res://objects/level editor/web_cannon_tile/web_cannon_tile.tscn' # DONE
const web_tile = 'res://objects/level editor/web_tile/web_tile.tscn' # DONE
const yeti_king_tile = 'res://objects/level editor/yeti_king_tile/yeti_king_tile.tscn' # DONE
const yeti_tile = 'res://objects/level editor/yeti_tile/yeti_tile.tscn' # DONE
const zombie_tile = 'res://objects/level editor/zombie_tile/zombie_tile.tscn' # DONE


#other
const black = 'res://objects/other/black/black.tscn' # DONE
const black_bg = 'res://objects/other/black_bg/black_bg.tscn' # DONE
const cave_up = 'res://objects/other/cave_up/cave_up.tscn' # DONE
const hint_hand = 'res://objects/other/hint_hand/hint_hand.tscn' # PROGRESS
const menu_bottom = 'res://objects/other/menu_bottom/menu_bottom.tscn' # DONE
const menu_left = 'res://objects/other/menu_left/menu_left.tscn' # DONE
const menu_ll = 'res://objects/other/menu_ll/menu_ll.tscn' # DONE
const menu_lr = 'res://objects/other/menu_lr/menu_lr.tscn' # DONE
const menu_right = 'res://objects/other/menu_right/menu_right.tscn' # DONE
#const menu_sel = 'res://objects/other/menu_sel/menu_sel.tscn'
const menu_top = 'res://objects/other/menu_top/menu_top.tscn' # DONE
const menu_ul = 'res://objects/other/menu_ul/menu_ul.tscn' # DONE
const menu_ur = 'res://objects/other/menu_ur/menu_ur.tscn'
#const page_down = 'res://objects/other/page_down/page_down.tscn'
#const page_up = 'res://objects/other/page_up/page_up.tscn'
const p_dummy = 'res://objects/other/p_dummy/p_dummy.tscn' # DONE
const p_dummy2 = 'res://objects/other/p_dummy2/p_dummy2.tscn' # DONE
const p_dummy3 = 'res://objects/other/p_dummy3/p_dummy3.tscn' # DONE (check for leftover test stuff)
const p_dummy4 = 'res://objects/other/p_dummy4/p_dummy4.tscn' # DONE
const p_dummy5 = 'res://objects/other/p_dummy5/p_dummy5.tscn' # DONE
const p_dummy6 = 'res://objects/other/p_dummy6/p_dummy6.tscn' # DONE
const wal_damsel = 'res://objects/other/wal_damsel/wal_damsel.tscn' # DONE


#other\end
const bg_end3 = 'res://objects/other/end/bg_end3/bg_end3.tscn' # DONE
const big_chest = 'res://objects/other/end/big_chest/big_chest.tscn' # DONE
const big_treasure = 'res://objects/other/end/big_treasure/big_treasure.tscn' # DONE
const end2_bg = 'res://objects/other/end/end2_bg/end2_bg.tscn' # DELETED ?
const end_plat = 'res://objects/other/end/end_plat/end_plat.tscn' # DONE
const end_wall = 'res://objects/other/end/end_wall/end_wall.tscn' # DONE
const lava_spray = 'res://objects/other/end/lava_spray/lava_spray.tscn' # DONE
const player_sil = 'res://objects/other/end/player_sil/player_sil.tscn' # DONE
const treasure_sil = 'res://objects/other/end/treasure_sil/treasure_sil.tscn' # DONE


#other\intro
const bat_intro = 'res://objects/other/intro/bat_intro/bat_intro.tscn' # DONE (might need to check speed value?)
const camel = 'res://objects/other/intro/camel/camel.tscn' # DONE
const caravan = 'res://objects/other/intro/caravan/caravan.tscn' # DONE
const desert = 'res://objects/other/intro/desert/desert.tscn' # DONE
const desert2 = 'res://objects/other/intro/desert2/desert2.tscn' # DONE
const desert_scroll = 'res://objects/other/intro/desert_scroll/desert_scroll.tscn' # DONE
const desert_scroll2 = 'res://objects/other/intro/desert_scroll2/desert_scroll2.tscn' # DONE
const desert_top = 'res://objects/other/intro/desert_top/desert_top.tscn' # DONE
const desert_top_scroll = 'res://objects/other/intro/desert_top_scroll/desert_top_scroll.tscn' # DONE
const intro_bg = 'res://objects/other/intro/intro_bg/intro_bg.tscn' # DONE
const moon = 'res://objects/other/intro/moon/moon.tscn' # DONE
const palm_tree = 'res://objects/other/intro/palm_tree/palm_tree.tscn' # DONE
const palm_tree_dark = 'res://objects/other/intro/palm_tree_dark/palm_tree_dark.tscn' # DONE
const palm_tree_scroll = 'res://objects/other/intro/palm_tree_scroll/palm_tree_scroll.tscn' # DONE
const shrub = 'res://objects/other/intro/shrub/shrub.tscn' # DONE
const shrub_dark = 'res://objects/other/intro/shrub_dark/shrub_dark.tscn' # DONE
const shrub_scroll = 'res://objects/other/intro/shrub_scroll/shrub_scroll.tscn' # DONE


#other\title
const basket = 'res://objects/other/title/basket/basket.tscn' # DONE
const bat_target = 'res://objects/other/title/bat_target/bat_target.tscn' # DONE
const button_highscore = 'res://objects/other/title/button_highscore/button_highscore.tscn' # DONE
const copy = 'res://objects/other/title/copy/copy.tscn' # DONE
const level13_sign = 'res://objects/other/title/level13_sign/level13_sign.tscn' # DONE
const level5_sign = 'res://objects/other/title/level5_sign/level5_sign.tscn' # DONE
const level9_sign = 'res://objects/other/title/level9_sign/level9_sign.tscn' # DONE
const multi_trophy = 'res://objects/other/title/multi_trophy/multi_trophy.tscn' # DONE
const new_text = 'res://objects/other/title/new/new.tscn' # DONE. changed name to prevent issues (because "new" can be a callable)
const quit_sign = 'res://objects/other/title/quit_sign/quit_sign.tscn' # DONE
const reset_sign = 'res://objects/other/title/reset_sign/reset_sign.tscn' # DONE
const rim = 'res://objects/other/title/rim/rim.tscn' # DONE
const rim_deflect = 'res://objects/other/title/rim_deflect/rim_deflect.tscn' # DONE
const scores_sign = 'res://objects/other/title/scores_sign/scores_sign.tscn' # DONE
const start_sign = 'res://objects/other/title/start_sign/start_sign.tscn' # DONE
const target = 'res://objects/other/title/target/target.tscn' # DONE
const title_bg = 'res://objects/other/title/title_bg/title_bg.tscn' # DONE
const title_logo = 'res://objects/other/title/title_logo/title_logo.tscn' # DONE
const trophy = 'res://objects/other/title/trophy/trophy.tscn' # DONE
const tutorial_sign = 'res://objects/other/title/tutorial_sign/tutorial_sign.tscn' # DONE
const x_change = 'res://objects/other/title/x_change/x_change.tscn' # DONE
const x_change2 = 'res://objects/other/title/x_change2/x_change2.tscn' # DONE
const x_end = 'res://objects/other/title/x_end/x_end.tscn' # DONE
const x_moon = 'res://objects/other/title/x_moon/x_moon.tscn' # DONE
const x_scores = 'res://objects/other/title/x_scores/x_scores.tscn' # DONE
const x_shortcut13 = 'res://objects/other/title/x_shortcut13/x_shortcut13.tscn' # DONE
const x_shortcut5 = 'res://objects/other/title/x_shortcut5/x_shortcut5.tscn' # DONE
const x_shortcut9 = 'res://objects/other/title/x_shortcut9/x_shortcut9.tscn' # DONE
const x_stars = 'res://objects/other/title/x_stars/x_stars.tscn' # DONE
const x_start = 'res://objects/other/title/x_start/x_start.tscn' # DONE
const x_sun = 'res://objects/other/title/x_sun/x_sun.tscn' # DONE
const x_title = 'res://objects/other/title/x_title/x_title.tscn' # DONE
const x_tutorial = 'res://objects/other/title/x_tutorial/x_tutorial.tscn' # DONE


#traps
const arrow_repeater_l = 'res://objects/traps/arrow_repeater_l/arrow_repeater_l.tscn' # DONE
const arrow_repeater_r = 'res://objects/traps/arrow_repeater_r/arrow_repeater_r.tscn' # DONE
const arrow_trap_left = 'res://objects/traps/arrow_trap_left/arrow_trap_left.tscn' # DONE
const arrow_trap_left_lit = 'res://objects/traps/arrow_trap_left_lit/arrow_trap_left_lit.tscn' # DONE
const arrow_trap_right = 'res://objects/traps/arrow_trap_right/arrow_trap_right.tscn' # DONE
const arrow_trap_right_lit = 'res://objects/traps/arrow_trap_right_lit/arrow_trap_right_lit.tscn' # DONE
const arrow_trap_test = 'res://objects/traps/arrow_trap_test/arrow_trap_test.tscn' # DONE
const boulder = 'res://objects/traps/boulder/boulder.tscn' # DONE
const ceiling_trap = 'res://objects/traps/ceiling_trap/ceiling_trap.tscn' # DONE
const door = 'res://objects/traps/door/door.tscn' # DONE
const giant_tiki_head = 'res://objects/traps/giant_tiki_head/giant_tiki_head.tscn' # DONE
const smash_trap = 'res://objects/traps/smash_trap/smash_trap.tscn' # DONE
const smash_trap_lit = 'res://objects/traps/smash_trap_lit/smash_trap_lit.tscn' # DONE
const spears_left = 'res://objects/traps/spears_left/spears_left.tscn' # DONE
const spear_trap_bottom = 'res://objects/traps/spear_trap_bottom/spear_trap_bottom.tscn' # DONE
const spear_trap_lit = 'res://objects/traps/spear_trap_lit/spear_trap_lit.tscn' # DONE
const spear_trap_top = 'res://objects/traps/spear_trap_top/spear_trap_top.tscn' # DONE
const spikes = 'res://objects/traps/spikes/spikes.tscn' # DONE
const spring_trap = 'res://objects/traps/spring_trap/spring_trap.tscn' # DONE
const temp = 'res://objects/traps/temp/temp.tscn' # DONE
const thwomp_trap = 'res://objects/traps/thwomp_trap/thwomp_trap.tscn' # DONE
const trap_block = 'res://objects/traps/trap_block/trap_block.tscn' # DONE
