extends Node

# contains the sprites that each object should be able to display

const OBJECT_SPRITES: Dictionary = {'alien': ['alien'],
 'alien_boss': ['alien_boss', 'alien_boss_dead', 'alien_boss_die', 'alien_boss_hurt'],
 'alien_boss_tile': ['alien_boss_tile'],
 'alien_eject': ['alien_eject', 'alien_parachute', 'alien_deploy'],
 'alien_ship': ['alien_top'],
 'alien_ship_floor': ['alien_floor'],
 'alien_tile': ['alien'],
 'altar_left': ['altar_left'],
 'altar_right': ['altar_right'],
 'ankh': ['ankh'],
 'arrow': ['arrow_right'],
 'arrow_repeater_l': ['arrow_trap_left'],
 'arrow_repeater_r': ['arrow_trap_right'],
 'arrow_trap_left': ['arrow_trap_left'],
 'arrow_trap_left_lit': ['arrow_trap_left_lit'],
 'arrow_trap_right': ['arrow_trap_right'],
 'arrow_trap_right_lit': ['arrow_trap_right_lit'],
 'arrow_trap_test': ['red'],
 'backdrop': [],
 'ball': ['ball'],
 'ball2': ['ball'],
 'barrier': ['barrier', 'bomb_armed'],
 'barrier_emitter': ['barrier_emitter'],
 'basket': ['basket', 'basket_swoosh'],
 'basketball': ['basketball', 'dribble'],
 'bat': ['bat_hang', 'bat_left', 'bat_right'],
 'bat_intro': ['bat_left'],
 'bat_target': ['bat_left', 'ufo'],
 'bat_tile': ['bat_hang'],
 'bg_end3': ['bg_end3'],
 'big_chest': ['big_chest', 'big_chest_open'],
 'big_collect': ['big_collect'],
 'big_treasure': ['big_treasure'],
 'black': ['black'],
 'black_bg': ['black'],
 'black_fade_up': ['black_fade_up'],
 'block': ['block', 'gold_block'],
 'blood': ['blood'],
 'blood_spark': ['blood_spark'],
 'blood_trail': ['blood_trail'],
 'bomb': ['bomb', 'bomb_armed'],
 'bomb_bag': ['bomb_bag'],
 'bomb_bag_tile': ['bomb_bag_tile'],
 'bomb_box': ['bomb_box'],
 'bomb_box_tile': ['bomb_box_tile'],
 'bomb_paste_tile': ['bomb_paste_tile'],
 'bone': ['bone', 'smoke_puff'],
 'bones': ['bones_left'],
 'bones_tile': ['fake_bones_left'],
 'boulder': ['boulder', 'boulder_rotate_l', 'boulder_rotate_r'],
 'bow': ['bow_right', 'bow_left'],
 'bow_tile': ['bow_tile'],
 'brick': ['brick', 'brick2', 'brick_gold', 'brick_gold_big'],
 'brick_smooth': ['cave_smooth'],
 'bricks': [],
 'bubble': ['bubble'],
 'bullet': ['bullet'],
 'burn': ['burn'],
 'button_highscore': ['button', 'button_pushed'],
 'camel': ['camel', 'camel_damsel', 'camel_tunnel'],
 'cape': ['cape_right',
		  'cape_back',
		  'cape_dr',
		  'cape_ur',
		  'cape_ul',
		  'cape_left',
		  'cape_dl'],
 'cape_pickup': ['cape'],
 'cape_tile': ['cape_tile'],
 'caravan': ['caravan1', 'caravan3', 'caravan2'],
 'cave_bg': ['cave_bg1', 'cave_bg2'],
 'cave_bg2': ['cave_bg'],
 'cave_bg_entrance': ['cave_bg_entrance'],
 'cave_up': ['cave_up'],
 'caveman': ['caveman_left',
			 'caveman_stun_l',
			 'caveman_bounce_l',
			 'caveman_fall_l',
			 'caveman_die_ll',
			 'caveman_die_lr',
			 'caveman_dead_l',
			 'caveman_run_left',
			 'caveman_held_l',
			 'caveman_d_held_l'],
 'caveman_tile': ['caveman_left'],
 'caveman_worship': ['caveman_worship_r'],
 'ceiling_trap': ['block', 'ceiling_trap', 'ceiling_trap_s'],
 'chain': ['chain'],
 'chain2': ['chain'],
 'character': [],
 'check_box': ['box_checked', 'box'],
 'check_box2': ['box_checked', 'box'],
 'check_box3': ['box_checked', 'box'],
 'check_box4': ['box_checked', 'box'],
 'chest': ['chest', 'chest_open'],
 'chest_tile': ['chest_tile'],
 'compass': ['compass'],
 'compass_tile': ['compass_tile'],
 'copy': ['copy'],
 'crate': ['crate'],
 'crate_tile': ['crate_tile'],
 'credits1': [],
 'credits2': [],
 'crown': ['crown'],
 'crystal_skull': ['crystal_skull'],
 'crystal_skull_tile': ['crystal_skull_tile'],
 'curs_obj': ['entrance', 'bat_left', 'spikes', 'gold_bar_tile'],
 'damsel': ['damsel_left',
			'p_exit',
			'damsel_exit2',
			'die_l',
			'damsel_die_l',
			'stand_left',
			'yell_left',
			'damsel_yell_l',
			'run_left',
			'damsel_run_l',
			'stun_l',
			'die_l_bounce',
			'die_l_fall',
			'die_ll',
			'die_lr',
			'damsel_stun_l',
			'damsel_bounce_l',
			'damsel_fall_l',
			'damsel_die_ll',
			'damsel_die_lr',
			'die_l_bounce',
			'damsel_hold_l',
			'p_kiss_l',
			'damsel_kiss_l'],
 'damsel_kiss': ['damsel_left', 'stand_left', 'p_kiss_l'],
 'damsel_tile': ['damsel_left_ico'],
 'dark': ['dark', 'dark_gold', 'dark_gold_big'],
 'dark_fall': ['dark_fall'],
 'dead_fish': ['dead_fish_left', 'dead_fish_right'],
 'desert': ['desert', 'desert_night'],
 'desert2': ['desert2', 'desert_night2'],
 'desert_scroll': ['desert', 'desert_night'],
 'desert_scroll2': ['desert2', 'desert_night2'],
 'desert_top': ['desert_top', 'desert_top_night'],
 'desert_top_scroll': ['desert_top', 'desert_top_night'],
 'detritus': [],
 'diamond': ['diamond'],
 'diamond_tile': ['diamond_tile'],
 'dice': ['dice1',
		  'dice_roll',
		  'dice2',
		  'dice3',
		  'dice4',
		  'dice5',
		  'dice6'],
 'door': ['door'],
 'drawn_sprite': [],
 'drip': ['drip'],
 'edit_button': ['edit_button'],
 'emerald': ['emerald'],
 'emerald_big': ['emerald_big'],
 'emerald_big_tile': ['emerald_big_tile'],
 'end': [],
 'end2': [],
 'end2_bg': ['end2_bg'],
 'end3': [],
 'end_custom': [],
 'end_plat': ['end_plat'],
 'end_wall': ['end_wall'],
 'enemy': [],
 'enemy_sight': ['sight'],
 'entrance': ['entrance'],
 'entrance_check': ['sight'],
 'exit': ['exit'],
 'explosion': ['explosion', 'bomb_armed'],
 'fake_bones': ['fake_bones_left', 'skeleton_create_l'],
 'final_boss': [],
 'fire_frog': ['fire_frog_left', 'fire_frog_jump_l'],
 'fire_frog_armed': ['fire_frog_armed_l'],
 'fire_frog_bomb': ['fire_frog_armed_l'],
 'fire_frog_tile': ['fire_frog_left'],
 'fish_bone': ['fish_bone'],
 'flame': ['flame'],
 'flame_trail': ['flame_trail'],
 'flare': ['flare'],
 'flare_crate': ['flare_crate'],
 'flare_spark': ['flare_spark'],
 'fly': ['fly_left', 'fly_right'],
 'foreground': [],
 'frill': [],
 'frog': ['frog_left', 'frog_jump_l'],
 'frog_tile': ['frog_left'],
 'frozen_caveman': ['frozen_caveman'],
 'game': ['lava_top', 'water_top'],
 'gamepad': [],
 'ghost': ['ghost_right',
		   'ghost_left',
		   'ghost_disappear',
		   'ghost_turn_left',
		   'ghost_turn_right'],
 'giant_spider': ['giant_spider_flip',
				  'giant_spider_jump',
				  'giant_spider',
				  'giant_spider_crawl',
				  'giant_spider_squirt'],
 'giant_spider_hang': ['giant_spider_hang'],
 'giant_spider_tile': ['giant_spider_hang'],
 'giant_tiki_head': ['giant_tiki_head'],
 'globals': [],
 'gloves': ['glove'],
 'gloves_tile': ['gloves_tile'],
 'gold': ['gold'],
 'gold_bar': ['gold_bar'],
 'gold_bar_tile': ['gold_bar_tile'],
 'gold_bars': ['gold_bars'],
 'gold_bars_tile': ['gold_bars_tile'],
 'gold_big': ['gold_big'],
 'gold_chunk': ['gold_chunk'],
 'gold_door': ['gold_door'],
 'gold_idol': ['gold_idol'],
 'gold_idol_tile': ['gold_idol_tile'],
 'gold_nugget': ['gold_nugget'],
 'grave': ['grave', 'grave2', 'grave3', 'grave4', 'grave5', 'grave6'],
 'hard_block': ['brick'],
 'hawkman': ['hawk_left',
			 'hawk_throw_l',
			 'hawk_stun_l',
			 'hawk_bounce_l',
			 'hawk_fall_l',
			 'hawk_die_ll',
			 'hawk_die_lr',
			 'hawk_dead_l',
			 'hawk_run_left',
			 'hawk_held_l',
			 'hawk_d_held_l'],
 'hawkman_tile': ['hawk_left'],
 'hawkman_worship': ['hawk_left'],
 'heart': ['smooch_heart'],
 'highscores': [],
 'hint_hand': ['hint_point'],
 'ice': ['ice'],
 'ice_block': ['ice_block', 'gold_block'],
 'ice_bottom': ['ice_bottom2'],
 'ice_tile': ['ice'],
 'intro': [],
 'intro_bg': ['intro_bg'],
 'item': ['bomb_armed', 'bomb_arrow_right'],
 'items_get': ['item_get', 'bombs_get', 'rope_get'],
 'jar': ['jar'],
 'jar_tile': ['jar_tile'],
 'jaws': ['jaws_left', 'jaws_right', 'jaws_turn_l', 'jaws_turn_r'],
 'jetpack': ['jetpack_right'],
 'jetpack_tile': ['jetpack_tile'],
 'jordans': ['jordans'],
 'joy_config': [],
 'joy_config_button': ['joy_config_button'],
 'kali_head': ['kali_head1', 'kali_head2', 'kali_head3'],
 'kapala': ['kapala'],
 'key': ['key_right', 'key_left'],
 'key_config': [],
 'key_config_button': ['key_config_button'],
 'ladder': [],
 'ladder_orange': ['ladder'],
 'ladder_top': ['ladder_top'],
 'lamp': ['lamp'],
 'lamp_item': ['lamp_item'],
 'lamp_red': ['lamp_red'],
 'lamp_red_item': ['lamp_red_item'],
 'laser': ['laser'],
 'laser_explode': ['laser_explode'],
 'laser_trail': ['laser_trail'],
 'lava': ['lava'],
 'lava_drip': ['lava_drip'],
 'lava_solid': ['lava'],
 'lava_spray': ['lava_spray'],
 'lava_tile': ['lava'],
 'leaf': ['leaf'],
 'leaves': ['leaves',
			'leaves_dead',
			'leaves_dead_r',
			'leaves_right',
			'leaves_top'],
 'leaves_tile': ['leaves', 'leaves_right'],
 'level': [],
 'level13_sign': ['level13_sign'],
 'level5_sign': ['level5_sign'],
 'level9_sign': ['level9_sign'],
 'level_editor': [],
 'load_button': ['load_button'],
 'load_level': ['menu_sel_off'],
 'locked_chest': ['locked_chest', 'locked_chest_open'],
 'lush': ['lush', 'lush_gold', 'lush_gold_big'],
 'machete': ['machete_right', 'machete_left'],
 'machete_pre': ['machete_pre_r', 'machete_pre_l'],
 'machete_tile': ['machete_tile'],
 'magma': ['magma', 'magma_man_create'],
 'magma_man': ['magma_man_left',
			   'bomb_armed',
			   'magma_man_die',
			   'magma_man_walk_l'],
 'magma_trail': ['flame_trail'],
 'man_trap': ['man_trap_left',
			  'man_trap_sleep_l',
			  'man_trap_stun_l',
			  'man_trap_eat_caveman_l',
			  'man_trap_eat_damsel_l',
			  'man_trap_eat_tunnel_l',
			  'man_trap_eat_l',
			  'man_trap_eat_shopkeeper_l'],
 'man_trap_tile': ['man_trap_left'],
 'mattock': ['mattock_right', 'mattock_left'],
 'mattock_head': ['mattock_head'],
 'mattock_hit': ['mattock_hit_r', 'mattock_hit_l', 'mattock_hit_r'],
 'mattock_pre': ['mattock_pre_r', 'mattock_pre_l'],
 'mattock_tile': ['mattock_tile'],
 'mega_mouth_tile': ['mega_mouth_tile'],
 'menu': [],
 'menu_bottom': ['menu_bottom'],
 'menu_left': ['menu_left'],
 'menu_ll': ['menu_ll'],
 'menu_lr': ['menu_lr'],
 'menu_right': ['menu_right'],
 'menu_sel': ['menu_sel_off', 'menu_sel_on'],
 'menu_top': ['menu_top'],
 'menu_ul': ['menu_ul'],
 'menu_ur': ['menu_ur'],
 'mitt': ['mitt'],
 'mitt_tile': ['mitt_tile'],
 'moai': ['moai'],
 'moai2': ['moai2'],
 'moai3': ['moai3'],
 'moai_inside': ['moai_inside'],
 'monkey': ['monkey_left',
			'monkey_hang_l',
			'monkey_climb_l',
			'monkey_jump_l',
			'monkey_walk_l'],
 'monkey_tile': ['monkey_left'],
 'moon': ['moon'],
 'moon_room': [],
 'moveable_solid': [],
 'moving_solid': [],
 'msg_sign': ['msg_sign'],
 'multi_trophy': ['multi_gold'],
 'music': [],
 'new': ['new'],
 'new_button': ['new_button'],
 'ok_button': ['ok_button'],
 'olmec': ['olmec_start1', 'olmec_start2', 'olmec_start3'],
 'olmec_debris': ['olmec_debris', 'olmec_debris2', 'olmec_debris3'],
 'olmec_slam': ['olmec_slam'],
 'p_dummy': ['run_left',
			 'damsel_run_l',
			 'tunnel_run_l',
			 'damsel_left',
			 'tunnel_left',
			 'stand_left',
			 'p_kiss_l',
			 'damsel_kiss_l',
			 'damsel_exit',
			 'tunnel_exit',
			 'p_exit'],
 'p_dummy2': ['run_left',
			  'damsel_left',
			  'tunnel_left',
			  'stand_left',
			  'damsel_run_l',
			  'tunnel_run_l',
			  'damsel_fall_l',
			  'tunnel_fall_l',
			  'die_l_fall',
			  'damsel_stun_l',
			  'tunnel_stun_l',
			  'stun_l',
			  'damsel_die_lr',
			  'tunnel_die_lr',
			  'jump_left'],
 'p_dummy3': ['run_left', 'duck_left', 'climb_up3'],
 'p_dummy4': ['run_left', 'fall_left', 'climb_up3'],
 'p_dummy5': ['run_left', 'damsel_climb2', 'tunnel_climb2', 'climb_up2'],
 'p_dummy6': ['stand_left', 'damsel_left', 'tunnel_left'],
 'page_down': ['page_down', 'menu_sel_off'],
 'page_up': ['page_up', 'menu_sel_off'],
 'palm_tree': ['palm_tree'],
 'palm_tree_dark': ['palm_tree_dark'],
 'palm_tree_scroll': ['palm_tree', 'palm_tree_dark'],
 'para_pickup': ['para_pickup'],
 'para_used': ['para_used'],
 'parachute': ['para_open', 'parachute'],
 'parachute_tile': ['parachute_tile'],
 'paste': ['paste'],
 'piranha': ['piranha_left', 'piranha_right'],
 'piranha_tile': ['piranha_tile'],
 'pistol': ['pistol_right', 'pistol_left'],
 'pistol_tile': ['pistol_tile'],
 'platform': [],
 'player1': ['stand_left',
			 'damsel_attack_l',
			 'tunnel_attack_l',
			 'damsel_dt_hl',
			 'tunnel_dt_hl',
			 'damsel_left',
			 'tunnel_left',
			 'bomb_armed',
			 'damsel_exit',
			 'tunnel_exit',
			 'p_exit',
			 'attack_left',
			 'damsel_die_l',
			 'damsel_stun_l',
			 'damsel_bounce_l',
			 'damsel_fall_l',
			 'damsel_die_ll',
			 'damsel_die_lr',
			 'tunnel_die_l',
			 'tunnel_stun_l',
			 'tunnel_l_bounce',
			 'tunnel_fall_l',
			 'tunnel_die_ll',
			 'tunnel_die_lr',
			 'die_l',
			 'stun_l',
			 'die_l_bounce',
			 'die_l_fall',
			 'die_ll',
			 'die_lr',
			 'damsel_exit2'],
 'player_sil': ['player_sil'],
 'poof': ['poof'],
 'psychic_create': ['psychic_create'],
 'psychic_create2': ['psychic_create'],
 'psychic_create_p': ['psychic_create'],
 'psychic_wave': ['psychic_wave'],
 'psychic_wave_p': ['psychic_wave_p'],
 'push_block': ['block', 'gold_block'],
 'quit_sign': ['quit_sign'],
 'radio_box': ['box', 'box_marked'],
 'reset_sign': ['reset_sign'],
 'rim': ['rim'],
 'rim_deflect': ['rim_deflect'],
 'rock': ['rock'],
 'rock_tile': ['rock_tile'],
 'room': ['room'],
 'rope': ['rope'],
 'rope_bag': ['rope_end'],
 'rope_burn': ['burn'],
 'rope_pile': ['rope_pile'],
 'rope_pile_tile': ['rope_pile_tile'],
 'rope_throw': ['rope_end'],
 'rope_top': ['rope_top'],
 'rubble': ['rubble', 'rubble_tan', 'rubble_tan_small'],
 'rubble_dark': ['rubble_dark'],
 'rubble_dark_small': ['rubble_dark_small'],
 'rubble_piece': ['leaf_still'],
 'rubble_small': ['rubble_small'],
 'ruby': ['ruby'],
 'ruby_big': ['ruby_big'],
 'ruby_big_tile': ['ruby_big_tile'],
 'sac_altar_left': ['sac_altar_left'],
 'sac_altar_right': ['sac_altar_right'],
 'sapphire': ['sapphire'],
 'sapphire_big': ['sapphire_big'],
 'sapphire_big_tile': ['sapphire_big_tile'],
 'scarab': ['scarab'],
 'sceptre': ['sceptre_right', 'sceptre_left'],
 'scores_sign': ['scores_sign'],
 'screen': [],
 'shopkeeper': ['shop_left',
				'shop_throw_l',
				'shop_stun_l',
				'shop_bounce_l',
				'shop_fall_l',
				'shop_die_ll',
				'shop_die_lr',
				'shop_die_l',
				'shop_run_left',
				'shop_held_l',
				'shop_d_held_l'],
 'shopkeeper2': ['shop_left'],
 'shopkeeper_tile': ['shop_left_ico'],
 'shotgun': ['shotgun_right', 'shotgun_left'],
 'shotgun_blast_left': ['shotgun_blast_left'],
 'shotgun_blast_right': ['shotgun_blast_right'],
 'shotgun_tile': ['shotgun_tile'],
 'shrub': ['shrub'],
 'shrub_dark': ['shrub_dark'],
 'shrub_scroll': ['shrub', 'shrub_dark'],
 'sign': ['sign_general'],
 'skeleton': ['skeleton_create_l', 'skeleton_walk_left', 'skeleton_left'],
 'skeleton_tile': ['skeleton_left'],
 'skull': ['skull'],
 'slash': ['slash_right', 'slash_left'],
 'slider1': ['slider'],
 'slider2': ['slider'],
 'slider_bg': ['slider_bg'],
 'small_collect': ['small_collect'],
 'smash_trap': ['smash_trap'],
 'smash_trap_lit': ['smash_trap_lit'],
 'smash_trap_tile': ['smash_trap'],
 'smoke_puff': ['smoke_puff'],
 'snake': ['snake_left', 'snake_walk_l', 'snake_walk_r'],
 'snake_tile': ['snake_left'],
 'solid': [],
 'spear_trap_bottom': ['spear_trap2'],
 'spear_trap_lit': ['spear_trap_lit'],
 'spear_trap_tile_bot': ['spear_trap2'],
 'spear_trap_tile_top': ['spear_trap1'],
 'spear_trap_top': ['spear_trap1'],
 'spears_left': ['spears_left', 'spears_right'],
 'spectacles': ['spectacles'],
 'spectacles_tile': ['spectacles_tile'],
 'spider': ['spider_flip', 'spider', 'spider_drowning'],
 'spider_hang': ['spider_hang'],
 'spider_tile': ['spider_hang'],
 'spike_shoes': ['spike_shoes'],
 'spike_shoes_tile': ['spike_shoes_tile'],
 'spikes': ['spikes', 'spikes_blood'],
 'splash': ['splash'],
 'spring_shoes': ['spring_shoes'],
 'spring_shoes_tile': ['spring_shoes_tile'],
 'spring_trap': ['spring_trap', 'spring_trap_sprung'],
 'spring_trap_tile': ['spring_trap'],
 'sprite': ['bat_left',
			'gold_chunk',
			'emerald',
			'sapphire',
			'ruby',
			'gold_nugget',
			'gold_bar_draw',
			'gold_bars_draw',
			'emerald_big',
			'sapphire_big',
			'ruby_big',
			'diamond',
			'stand_left',
			'damsel_left',
			'scarab_disp',
			'gold_idol_ico',
			'crystal_skull_ico',
			'snake_left',
			'spider',
			'dead_fish_left_ico',
			'piranha_left_ico',
			'skeleton_left',
			'zombie_left',
			'vampire_left',
			'frog_left',
			'fire_frog_left',
			'monkey_left',
			'man_trap_left',
			'yeti_left',
			'ufo',
			'alien',
			'alien_boss_disp',
			'caveman_left',
			'hawk_left',
			'giant_spider_disp',
			'mega_mouth',
			'yeti_king_disp',
			'tomb_lord_disp',
			'stand_left_ico',
			'damsel_left_ico',
			'shop_left_ico',
			'spears_right'],
 'stars_room': [],
 'start_sign': ['start_sign'],
 'sun_room': [],
 'target': ['target'],
 'teleporter': ['teleporter'],
 'teleporter_tile': ['teleporter_tile'],
 'temp': ['arrow_trap_left'],
 'temple': ['temple', 'g_temple', 'temple_gold', 'temple_gold_big'],
 'temple_fake': ['temple'],
 'test_button': ['test_button'],
 'thin_ice': ['thin_ice1',
			  'thin_ice2',
			  'thin_ice3',
			  'thin_ice4',
			  'thin_ice5',
			  'thin_ice6'],
 'thwomp_trap': ['thwomp_trap'],
 'tiki_torch': ['tiki_torch'],
 'title': [],
 'title_bg': ['title_bg'],
 'title_logo': ['title'],
 'tomb_lord': ['tomb_lord_left',
			   'tomb_lord_turn_r',
			   'tomb_lord_attack_l',
			   'tomb_lord_turn_l',
			   'tomb_lord_attack_r',
			   'tomb_lord_walk_l',
			   'tomb_lord_walk_r',
			   'tomb_lord_right'],
 'tomb_lord_tile': ['tomb_lord_left'],
 'transition': [],
 'trap_block': ['skull_block'],
 'treasure': [],
 'treasure_sil': ['treasure_sil'],
 'tree': ['tree_trunk'],
 'tree_branch': ['tree_branch_right', 'tree_branch_dead_r'],
 'tree_branch_tile': ['tree_branch_left'],
 'tree_tile': ['tree_trunk'],
 'trophy': ['bronze_trophy', 'gold_trophy', 'silver_trophy'],
 'tunnel_man': ['tunnel_man_left',
				'tunnel_man_right',
				'damsel_run_l',
				'run_left'],
 'tutorial_sign': ['tutorial_sign'],
 'udjat_eye': ['udjat_eye'],
 'ufo': ['ufo', 'ufo_blast'],
 'ufo_crash': ['ufo_crash'],
 'ufo_tile': ['ufo'],
 'vampire': ['vampire_left',
			 'vampire_stun_l',
			 'vampire_bounce_l',
			 'vampire_fall_l',
			 'vampire_die_ll',
			 'vampire_die_lr',
			 'vampire_bat_hang',
			 'vampire_bat_left',
			 'vampire_jump_l',
			 'vampire_run_l',
			 'vampire_held_l',
			 'vampire_d_held_l'],
 'vampire_tile': ['vampire_left'],
 'vine': ['vine'],
 'vine_top': ['vine_top'],
 'volcano_flame': ['volcano_flame'],
 'wal_damsel': ['wal_damsel'],
 'water': [],
 'water_swim': ['water'],
 'water_tile': ['water'],
 'web': ['web'],
 'web_ball': ['web_ball', 'web_create'],
 'web_cannon': ['web_cannon_r', 'web_cannon_l'],
 'web_cannon_tile': ['web_cannon_tile'],
 'web_tile': ['web_tile'],
 'whip': ['whip_right', 'whip_left'],
 'whip_pre': ['whip_pre_r', 'whip_pre_l'],
 'x_change': ['exit'],
 'x_change2': ['exit'],
 'x_end': ['exit'],
 'x_gold': ['exit'],
 'x_market': ['exit'],
 'x_moon': ['exit'],
 'x_scores': ['exit'],
 'x_shortcut13': ['exit'],
 'x_shortcut5': ['exit'],
 'x_shortcut9': ['exit'],
 'x_stars': ['exit'],
 'x_start': ['exit'],
 'x_sun': ['exit'],
 'x_title': ['exit'],
 'x_tutorial': ['exit'],
 'xoc_block': ['gold_block'],
 'yell_help': ['yell_help'],
 'yellow_ball': ['yellow_ball'],
 'yellow_trail': ['yellow_trail'],
 'yeti': ['yeti_left',
		  'yeti_throw_l',
		  'yeti_stun_l',
		  'yeti_bounce_l',
		  'yeti_fall_l',
		  'yeti_die_ll',
		  'yeti_die_lr',
		  'yeti_dead_l',
		  'yeti_run_left',
		  'yeti_held_l',
		  'yeti_d_held_l'],
 'yeti_king': ['yeti_king_left',
			   'yeti_king_turn_r',
			   'yeti_king_yell_l',
			   'yeti_king_turn_l',
			   'yeti_king_yell_r',
			   'yeti_king_walk_l',
			   'yeti_king_walk_r',
			   'yeti_king_right'],
 'yeti_king_tile': ['yeti_king_left'],
 'yeti_tile': ['yeti_left'],
 'zombie': ['zombie_left', 'zombie_jump_l'],
 'zombie_tile': ['zombie_left']}
