class_name ObjectDatabase

const object_database = {
	"bricks" : {
		"object_id" : 578,
		"sprite" : null,
		"solid" : false,
		"visible" : true,
		"depth" : 0,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"credits1" : {
		"object_id" : 683,
		"sprite" : null,
		"solid" : false,
		"visible" : true,
		"depth" : 0,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"credits2" : {
		"object_id" : 767,
		"sprite" : null,
		"solid" : false,
		"visible" : true,
		"depth" : 0,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"curs_obj" : {
		"object_id" : 813,
		"sprite" : "entrance",
		"solid" : false,
		"visible" : false,
		"depth" : 0,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"end" : {
		"object_id" : 584,
		"sprite" : null,
		"solid" : false,
		"visible" : true,
		"depth" : 0,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"end2" : {
		"object_id" : 605,
		"sprite" : null,
		"solid" : false,
		"visible" : true,
		"depth" : 0,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"end3" : {
		"object_id" : 613,
		"sprite" : null,
		"solid" : false,
		"visible" : true,
		"depth" : 0,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"end_custom" : {
		"object_id" : 897,
		"sprite" : null,
		"solid" : false,
		"visible" : true,
		"depth" : 0,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"final_boss" : {
		"object_id" : 580,
		"sprite" : null,
		"solid" : false,
		"visible" : true,
		"depth" : 0,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"game" : {
		"object_id" : 318,
		"sprite" : null,
		"solid" : false,
		"visible" : true,
		"depth" : 0,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"gamepad" : {
		"object_id" : 801,
		"sprite" : null,
		"solid" : false,
		"visible" : true,
		"depth" : 0,
		"persistent" : true,
		"parent" : null,
		"mask" : null,
		},
	"globals" : {
		"object_id" : 509,
		"sprite" : null,
		"solid" : false,
		"visible" : false,
		"depth" : 0,
		"persistent" : true,
		"parent" : null,
		"mask" : null,
		},
	"highscores" : {
		"object_id" : 548,
		"sprite" : null,
		"solid" : false,
		"visible" : true,
		"depth" : 0,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"intro" : {
		"object_id" : 615,
		"sprite" : null,
		"solid" : false,
		"visible" : true,
		"depth" : 0,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"joy_config" : {
		"object_id" : 808,
		"sprite" : null,
		"solid" : false,
		"visible" : true,
		"depth" : 0,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"key_config" : {
		"object_id" : 803,
		"sprite" : null,
		"solid" : false,
		"visible" : true,
		"depth" : 0,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"level" : {
		"object_id" : 553,
		"sprite" : null,
		"solid" : false,
		"visible" : true,
		"depth" : 0,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"level_editor" : {
		"object_id" : 812,
		"sprite" : null,
		"solid" : false,
		"visible" : true,
		"depth" : 1,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"load_level" : {
		"object_id" : 825,
		"sprite" : null,
		"solid" : false,
		"visible" : true,
		"depth" : 0,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"moon_room" : {
		"object_id" : 715,
		"sprite" : null,
		"solid" : false,
		"visible" : true,
		"depth" : 0,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"music" : {
		"object_id" : 731,
		"sprite" : null,
		"solid" : false,
		"visible" : false,
		"depth" : 0,
		"persistent" : true,
		"parent" : null,
		"mask" : null,
		},
	"player1" : {
		"object_id" : 319,
		"sprite" : "stand_left",
		"solid" : false,
		"visible" : true,
		"depth" : 50,
		"persistent" : false,
		"parent" : "character",
		"mask" : null,
		},
	"room" : {
		"object_id" : 442,
		"sprite" : "room",
		"solid" : false,
		"visible" : false,
		"depth" : 0,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"screen" : {
		"object_id" : 645,
		"sprite" : null,
		"solid" : false,
		"visible" : false,
		"depth" : 0,
		"persistent" : true,
		"parent" : null,
		"mask" : null,
		},
	"sprite" : {
		"object_id" : 563,
		"sprite" : null,
		"solid" : false,
		"visible" : true,
		"depth" : 1,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"stars_room" : {
		"object_id" : 701,
		"sprite" : null,
		"solid" : false,
		"visible" : true,
		"depth" : 0,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"sun_room" : {
		"object_id" : 721,
		"sprite" : null,
		"solid" : false,
		"visible" : true,
		"depth" : 0,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"title" : {
		"object_id" : 617,
		"sprite" : null,
		"solid" : false,
		"visible" : true,
		"depth" : 0,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"transition" : {
		"object_id" : 562,
		"sprite" : null,
		"solid" : false,
		"visible" : true,
		"depth" : 0,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"backdrop" : {
		"object_id" : 343,
		"sprite" : null,
		"solid" : false,
		"visible" : true,
		"depth" : 0,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"character" : {
		"object_id" : 271,
		"sprite" : null,
		"solid" : false,
		"visible" : true,
		"depth" : 0,
		"persistent" : true,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"detritus" : {
		"object_id" : 453,
		"sprite" : null,
		"solid" : false,
		"visible" : true,
		"depth" : 0,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"drawn_sprite" : {
		"object_id" : 598,
		"sprite" : null,
		"solid" : false,
		"visible" : true,
		"depth" : 0,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"enemy" : {
		"object_id" : 358,
		"sprite" : null,
		"solid" : false,
		"visible" : true,
		"depth" : 0,
		"persistent" : true,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"foreground" : {
		"object_id" : 348,
		"sprite" : null,
		"solid" : false,
		"visible" : true,
		"depth" : 0,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"frill" : {
		"object_id" : 455,
		"sprite" : null,
		"solid" : false,
		"visible" : true,
		"depth" : 0,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"item" : {
		"object_id" : 451,
		"sprite" : null,
		"solid" : true,
		"visible" : true,
		"depth" : 0,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"ladder" : {
		"object_id" : 129,
		"sprite" : null,
		"solid" : false,
		"visible" : true,
		"depth" : 0,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"menu" : {
		"object_id" : 614,
		"sprite" : null,
		"solid" : false,
		"visible" : true,
		"depth" : 0,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"moveable_solid" : {
		"object_id" : 145,
		"sprite" : null,
		"solid" : false,
		"visible" : true,
		"depth" : 0,
		"persistent" : false,
		"parent" : "solid",
		"mask" : null,
		},
	"moving_solid" : {
		"object_id" : 127,
		"sprite" : null,
		"solid" : false,
		"visible" : true,
		"depth" : 0,
		"persistent" : false,
		"parent" : "solid",
		"mask" : null,
		},
	"platform" : {
		"object_id" : 128,
		"sprite" : null,
		"solid" : false,
		"visible" : true,
		"depth" : 0,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"rubble_piece" : {
		"object_id" : 600,
		"sprite" : null,
		"solid" : false,
		"visible" : true,
		"depth" : 0,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"solid" : {
		"object_id" : 126,
		"sprite" : null,
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"treasure" : {
		"object_id" : 590,
		"sprite" : null,
		"solid" : false,
		"visible" : true,
		"depth" : 101,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"water" : {
		"object_id" : 304,
		"sprite" : null,
		"solid" : false,
		"visible" : true,
		"depth" : 0,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"alien_ship" : {
		"object_id" : 646,
		"sprite" : "alien_top",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "solid",
		"mask" : null,
		},
	"alien_ship_floor" : {
		"object_id" : 647,
		"sprite" : "alien_floor",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "solid",
		"mask" : null,
		},
	"altar_left" : {
		"object_id" : 643,
		"sprite" : "altar_left",
		"solid" : false,
		"visible" : true,
		"depth" : 110,
		"persistent" : false,
		"parent" : "solid",
		"mask" : null,
		},
	"altar_right" : {
		"object_id" : 644,
		"sprite" : "altar_right",
		"solid" : false,
		"visible" : true,
		"depth" : 110,
		"persistent" : false,
		"parent" : "solid",
		"mask" : null,
		},
	"black_fade_up" : {
		"object_id" : 638,
		"sprite" : "black_fade_up",
		"solid" : false,
		"visible" : true,
		"depth" : 999999,
		"persistent" : false,
		"parent" : "menu",
		"mask" : null,
		},
	"block" : {
		"object_id" : 448,
		"sprite" : "block",
		"solid" : false,
		"visible" : true,
		"depth" : 110,
		"persistent" : false,
		"parent" : "solid",
		"mask" : null,
		},
	"brick" : {
		"object_id" : 320,
		"sprite" : "brick",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "solid",
		"mask" : null,
		},
	"brick_smooth" : {
		"object_id" : 671,
		"sprite" : "cave_smooth",
		"solid" : false,
		"visible" : true,
		"depth" : 110,
		"persistent" : false,
		"parent" : "solid",
		"mask" : null,
		},
	"cave_bg" : {
		"object_id" : 510,
		"sprite" : "cave_bg1",
		"solid" : false,
		"visible" : true,
		"depth" : 99999999,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"cave_bg2" : {
		"object_id" : 621,
		"sprite" : "cave_bg",
		"solid" : false,
		"visible" : true,
		"depth" : 998,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"cave_bg_entrance" : {
		"object_id" : 622,
		"sprite" : "cave_bg_entrance",
		"solid" : false,
		"visible" : true,
		"depth" : 998,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"dark" : {
		"object_id" : 491,
		"sprite" : "dark",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "solid",
		"mask" : null,
		},
	"dark_fall" : {
		"object_id" : 516,
		"sprite" : "dark_fall",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "moving_solid",
		"mask" : null,
		},
	"entrance" : {
		"object_id" : 458,
		"sprite" : "entrance",
		"solid" : false,
		"visible" : true,
		"depth" : 9000,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"exit" : {
		"object_id" : 459,
		"sprite" : "exit",
		"solid" : false,
		"visible" : true,
		"depth" : 9000,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"frozen_caveman" : {
		"object_id" : 517,
		"sprite" : "frozen_caveman",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"gold" : {
		"object_id" : 460,
		"sprite" : "gold",
		"solid" : true,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"gold_big" : {
		"object_id" : 468,
		"sprite" : "gold_big",
		"solid" : true,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"gold_door" : {
		"object_id" : 794,
		"sprite" : "gold_door",
		"solid" : false,
		"visible" : true,
		"depth" : 10000,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"grave" : {
		"object_id" : 743,
		"sprite" : "grave",
		"solid" : false,
		"visible" : true,
		"depth" : 110,
		"persistent" : false,
		"parent" : "solid",
		"mask" : null,
		},
	"hard_block" : {
		"object_id" : 388,
		"sprite" : "brick",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "solid",
		"mask" : null,
		},
	"ice" : {
		"object_id" : 496,
		"sprite" : "ice",
		"solid" : false,
		"visible" : true,
		"depth" : 110,
		"persistent" : false,
		"parent" : "solid",
		"mask" : null,
		},
	"ice_block" : {
		"object_id" : 878,
		"sprite" : "ice_block",
		"solid" : false,
		"visible" : true,
		"depth" : 110,
		"persistent" : false,
		"parent" : "moveable_solid",
		"mask" : null,
		},
	"ice_bottom" : {
		"object_id" : 722,
		"sprite" : "ice_bottom2",
		"solid" : false,
		"visible" : true,
		"depth" : 110,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"kali_head" : {
		"object_id" : 921,
		"sprite" : "kali_head1",
		"solid" : false,
		"visible" : true,
		"depth" : 997,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"ladder_orange" : {
		"object_id" : 322,
		"sprite" : "ladder",
		"solid" : false,
		"visible" : true,
		"depth" : 1000,
		"persistent" : false,
		"parent" : "ladder",
		"mask" : null,
		},
	"ladder_top" : {
		"object_id" : 449,
		"sprite" : "ladder_top",
		"solid" : false,
		"visible" : true,
		"depth" : 1000,
		"persistent" : false,
		"parent" : "platform",
		"mask" : null,
		},
	"lamp" : {
		"object_id" : 753,
		"sprite" : "lamp",
		"solid" : false,
		"visible" : true,
		"depth" : 201,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"lamp_red" : {
		"object_id" : 811,
		"sprite" : "lamp_red",
		"solid" : false,
		"visible" : true,
		"depth" : 201,
		"persistent" : false,
		"parent" : "lamp",
		"mask" : null,
		},
	"lava" : {
		"object_id" : 573,
		"sprite" : "lava",
		"solid" : false,
		"visible" : true,
		"depth" : 20,
		"persistent" : false,
		"parent" : "water",
		"mask" : null,
		},
	"lava_solid" : {
		"object_id" : 575,
		"sprite" : "lava",
		"solid" : true,
		"visible" : true,
		"depth" : 110,
		"persistent" : false,
		"parent" : "solid",
		"mask" : null,
		},
	"leaves" : {
		"object_id" : 586,
		"sprite" : "leaves",
		"solid" : false,
		"visible" : true,
		"depth" : 1,
		"persistent" : false,
		"parent" : "platform",
		"mask" : null,
		},
	"leaves_tile" : {
		"object_id" : 932,
		"sprite" : "leaves",
		"solid" : false,
		"visible" : true,
		"depth" : 1,
		"persistent" : false,
		"parent" : "platform",
		"mask" : null,
		},
	"lush" : {
		"object_id" : 473,
		"sprite" : "lush",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "solid",
		"mask" : null,
		},
	"moai" : {
		"object_id" : 785,
		"sprite" : "moai",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "solid",
		"mask" : null,
		},
	"moai2" : {
		"object_id" : 790,
		"sprite" : "moai2",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "solid",
		"mask" : null,
		},
	"moai3" : {
		"object_id" : 791,
		"sprite" : "moai3",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "solid",
		"mask" : null,
		},
	"moai_inside" : {
		"object_id" : 786,
		"sprite" : "moai_inside",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "solid",
		"mask" : null,
		},
	"msg_sign" : {
		"object_id" : 759,
		"sprite" : "msg_sign",
		"solid" : false,
		"visible" : true,
		"depth" : 998,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"push_block" : {
		"object_id" : 467,
		"sprite" : "block",
		"solid" : false,
		"visible" : true,
		"depth" : 110,
		"persistent" : false,
		"parent" : "moveable_solid",
		"mask" : null,
		},
	"sac_altar_left" : {
		"object_id" : 919,
		"sprite" : "sac_altar_left",
		"solid" : false,
		"visible" : true,
		"depth" : 110,
		"persistent" : false,
		"parent" : "solid",
		"mask" : null,
		},
	"sac_altar_right" : {
		"object_id" : 920,
		"sprite" : "sac_altar_right",
		"solid" : false,
		"visible" : true,
		"depth" : 110,
		"persistent" : false,
		"parent" : "sac_altar_left",
		"mask" : null,
		},
	"sign" : {
		"object_id" : 709,
		"sprite" : "sign_general",
		"solid" : false,
		"visible" : true,
		"depth" : 110,
		"persistent" : false,
		"parent" : "solid",
		"mask" : null,
		},
	"splash" : {
		"object_id" : 480,
		"sprite" : "splash",
		"solid" : false,
		"visible" : true,
		"depth" : 1,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"temple" : {
		"object_id" : 602,
		"sprite" : "temple",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "solid",
		"mask" : null,
		},
	"temple_fake" : {
		"object_id" : 545,
		"sprite" : "temple",
		"solid" : false,
		"visible" : true,
		"depth" : 60,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"thin_ice" : {
		"object_id" : 678,
		"sprite" : "thin_ice1",
		"solid" : false,
		"visible" : true,
		"depth" : 110,
		"persistent" : false,
		"parent" : "solid",
		"mask" : null,
		},
	"tiki_torch" : {
		"object_id" : 906,
		"sprite" : "tiki_torch",
		"solid" : false,
		"visible" : true,
		"depth" : 8999,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"tree" : {
		"object_id" : 585,
		"sprite" : "tree_trunk",
		"solid" : false,
		"visible" : true,
		"depth" : 2,
		"persistent" : false,
		"parent" : "solid",
		"mask" : null,
		},
	"tree_branch" : {
		"object_id" : 587,
		"sprite" : "tree_branch_right",
		"solid" : false,
		"visible" : true,
		"depth" : 2,
		"persistent" : false,
		"parent" : "platform",
		"mask" : null,
		},
	"tree_branch_tile" : {
		"object_id" : 933,
		"sprite" : "tree_branch_left",
		"solid" : false,
		"visible" : true,
		"depth" : 2,
		"persistent" : false,
		"parent" : "platform",
		"mask" : null,
		},
	"tree_tile" : {
		"object_id" : 931,
		"sprite" : "tree_trunk",
		"solid" : false,
		"visible" : true,
		"depth" : 2,
		"persistent" : false,
		"parent" : "solid",
		"mask" : null,
		},
	"vine" : {
		"object_id" : 483,
		"sprite" : "vine",
		"solid" : false,
		"visible" : true,
		"depth" : 1000,
		"persistent" : false,
		"parent" : "ladder",
		"mask" : null,
		},
	"vine_top" : {
		"object_id" : 503,
		"sprite" : "vine_top",
		"solid" : false,
		"visible" : true,
		"depth" : 1000,
		"persistent" : false,
		"parent" : "ladder",
		"mask" : null,
		},
	"water_swim" : {
		"object_id" : 478,
		"sprite" : "water",
		"solid" : false,
		"visible" : true,
		"depth" : 9003,
		"persistent" : false,
		"parent" : "water",
		"mask" : null,
		},
	"x_gold" : {
		"object_id" : 795,
		"sprite" : "exit",
		"solid" : false,
		"visible" : true,
		"depth" : 9000,
		"persistent" : false,
		"parent" : "exit",
		"mask" : null,
		},
	"x_market" : {
		"object_id" : 782,
		"sprite" : "exit",
		"solid" : false,
		"visible" : true,
		"depth" : 9000,
		"persistent" : false,
		"parent" : "exit",
		"mask" : null,
		},
	"xoc_block" : {
		"object_id" : 916,
		"sprite" : "gold_block",
		"solid" : false,
		"visible" : true,
		"depth" : 110,
		"persistent" : false,
		"parent" : "solid",
		"mask" : null,
		},
	"damsel" : {
		"object_id" : 556,
		"sprite" : "damsel_left",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "item",
		"mask" : null,
		},
	"damsel_kiss" : {
		"object_id" : 623,
		"sprite" : "damsel_left",
		"solid" : true,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"shopkeeper" : {
		"object_id" : 666,
		"sprite" : "shop_left",
		"solid" : false,
		"visible" : true,
		"depth" : 60,
		"persistent" : false,
		"parent" : "enemy",
		"mask" : null,
		},
	"shopkeeper2" : {
		"object_id" : 702,
		"sprite" : "shop_left",
		"solid" : false,
		"visible" : true,
		"depth" : 60,
		"persistent" : false,
		"parent" : "shopkeeper",
		"mask" : null,
		},
	"tunnel_man" : {
		"object_id" : 673,
		"sprite" : "tunnel_man_left",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"yell_help" : {
		"object_id" : 601,
		"sprite" : "yell_help",
		"solid" : false,
		"visible" : true,
		"depth" : 1,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"ankh" : {
		"object_id" : 784,
		"sprite" : "ankh",
		"solid" : false,
		"visible" : true,
		"depth" : 101,
		"persistent" : false,
		"parent" : "item",
		"mask" : null,
		},
	"bomb_bag" : {
		"object_id" : 541,
		"sprite" : "bomb_bag",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "item",
		"mask" : null,
		},
	"bomb_box" : {
		"object_id" : 710,
		"sprite" : "bomb_box",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "item",
		"mask" : null,
		},
	"bones" : {
		"object_id" : 662,
		"sprite" : "bones_left",
		"solid" : false,
		"visible" : true,
		"depth" : 900,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"cape" : {
		"object_id" : 741,
		"sprite" : "cape_right",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"cape_pickup" : {
		"object_id" : 740,
		"sprite" : "cape",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "item",
		"mask" : null,
		},
	"chest" : {
		"object_id" : 472,
		"sprite" : "chest",
		"solid" : false,
		"visible" : true,
		"depth" : 900,
		"persistent" : false,
		"parent" : "item",
		"mask" : null,
		},
	"compass" : {
		"object_id" : 732,
		"sprite" : "compass",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "item",
		"mask" : null,
		},
	"crate" : {
		"object_id" : 594,
		"sprite" : "crate",
		"solid" : false,
		"visible" : true,
		"depth" : 900,
		"persistent" : false,
		"parent" : "item",
		"mask" : null,
		},
	"crown" : {
		"object_id" : 789,
		"sprite" : "crown",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "item",
		"mask" : null,
		},
	"diamond" : {
		"object_id" : 806,
		"sprite" : "diamond",
		"solid" : true,
		"visible" : true,
		"depth" : 101,
		"persistent" : false,
		"parent" : "treasure",
		"mask" : null,
		},
	"emerald" : {
		"object_id" : 489,
		"sprite" : "emerald",
		"solid" : true,
		"visible" : true,
		"depth" : 101,
		"persistent" : false,
		"parent" : "treasure",
		"mask" : null,
		},
	"emerald_big" : {
		"object_id" : 486,
		"sprite" : "emerald_big",
		"solid" : true,
		"visible" : true,
		"depth" : 101,
		"persistent" : false,
		"parent" : "treasure",
		"mask" : null,
		},
	"fake_bones" : {
		"object_id" : 657,
		"sprite" : "fake_bones_left",
		"solid" : false,
		"visible" : true,
		"depth" : 900,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"fire_frog_armed" : {
		"object_id" : 881,
		"sprite" : "fire_frog_armed_l",
		"solid" : false,
		"visible" : true,
		"depth" : 900,
		"persistent" : false,
		"parent" : "item",
		"mask" : null,
		},
	"flare_crate" : {
		"object_id" : 935,
		"sprite" : "flare_crate",
		"solid" : false,
		"visible" : true,
		"depth" : 900,
		"persistent" : false,
		"parent" : "item",
		"mask" : null,
		},
	"gloves" : {
		"object_id" : 746,
		"sprite" : "glove",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "item",
		"mask" : null,
		},
	"gold_bar" : {
		"object_id" : 591,
		"sprite" : "gold_bar",
		"solid" : true,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "treasure",
		"mask" : null,
		},
	"gold_bars" : {
		"object_id" : 592,
		"sprite" : "gold_bars",
		"solid" : true,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "treasure",
		"mask" : null,
		},
	"gold_chunk" : {
		"object_id" : 462,
		"sprite" : "gold_chunk",
		"solid" : true,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "treasure",
		"mask" : null,
		},
	"gold_nugget" : {
		"object_id" : 461,
		"sprite" : "gold_nugget",
		"solid" : true,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "treasure",
		"mask" : null,
		},
	"jetpack" : {
		"object_id" : 738,
		"sprite" : "jetpack_right",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "item",
		"mask" : null,
		},
	"jordans" : {
		"object_id" : 718,
		"sprite" : "jordans",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "item",
		"mask" : null,
		},
	"kapala" : {
		"object_id" : 936,
		"sprite" : "kapala",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "item",
		"mask" : null,
		},
	"key" : {
		"object_id" : 780,
		"sprite" : "key_right",
		"solid" : false,
		"visible" : true,
		"depth" : 101,
		"persistent" : false,
		"parent" : "item",
		"mask" : null,
		},
	"locked_chest" : {
		"object_id" : 779,
		"sprite" : "locked_chest",
		"solid" : false,
		"visible" : true,
		"depth" : 900,
		"persistent" : false,
		"parent" : "item",
		"mask" : null,
		},
	"mitt" : {
		"object_id" : 798,
		"sprite" : "mitt",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "item",
		"mask" : null,
		},
	"para_pickup" : {
		"object_id" : 712,
		"sprite" : "para_pickup",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "item",
		"mask" : null,
		},
	"para_used" : {
		"object_id" : 704,
		"sprite" : "para_used",
		"solid" : false,
		"visible" : true,
		"depth" : 900,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"paste" : {
		"object_id" : 711,
		"sprite" : "paste",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "item",
		"mask" : null,
		},
	"rope_bag" : {
		"object_id" : 593,
		"sprite" : "rope_end",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "item",
		"mask" : null,
		},
	"rope_pile" : {
		"object_id" : 672,
		"sprite" : "rope_pile",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "item",
		"mask" : null,
		},
	"ruby" : {
		"object_id" : 487,
		"sprite" : "ruby",
		"solid" : true,
		"visible" : true,
		"depth" : 101,
		"persistent" : false,
		"parent" : "treasure",
		"mask" : null,
		},
	"ruby_big" : {
		"object_id" : 484,
		"sprite" : "ruby_big",
		"solid" : true,
		"visible" : true,
		"depth" : 101,
		"persistent" : false,
		"parent" : "treasure",
		"mask" : null,
		},
	"sapphire" : {
		"object_id" : 488,
		"sprite" : "sapphire",
		"solid" : true,
		"visible" : true,
		"depth" : 101,
		"persistent" : false,
		"parent" : "treasure",
		"mask" : null,
		},
	"sapphire_big" : {
		"object_id" : 485,
		"sprite" : "sapphire_big",
		"solid" : true,
		"visible" : true,
		"depth" : 101,
		"persistent" : false,
		"parent" : "treasure",
		"mask" : null,
		},
	"spectacles" : {
		"object_id" : 737,
		"sprite" : "spectacles",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "item",
		"mask" : null,
		},
	"spike_shoes" : {
		"object_id" : 876,
		"sprite" : "spike_shoes",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "item",
		"mask" : null,
		},
	"spring_shoes" : {
		"object_id" : 713,
		"sprite" : "spring_shoes",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "item",
		"mask" : null,
		},
	"udjat_eye" : {
		"object_id" : 781,
		"sprite" : "udjat_eye",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "item",
		"mask" : null,
		},
	"big_collect" : {
		"object_id" : 505,
		"sprite" : "big_collect",
		"solid" : false,
		"visible" : true,
		"depth" : 1,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"blood" : {
		"object_id" : 370,
		"sprite" : "blood",
		"solid" : false,
		"visible" : true,
		"depth" : 1,
		"persistent" : false,
		"parent" : "detritus",
		"mask" : null,
		},
	"blood_spark" : {
		"object_id" : 937,
		"sprite" : "blood_spark",
		"solid" : false,
		"visible" : true,
		"depth" : 1,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"blood_trail" : {
		"object_id" : 452,
		"sprite" : "blood_trail",
		"solid" : false,
		"visible" : true,
		"depth" : 1,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"bone" : {
		"object_id" : 654,
		"sprite" : "bone",
		"solid" : false,
		"visible" : true,
		"depth" : 1,
		"persistent" : false,
		"parent" : "detritus",
		"mask" : null,
		},
	"bubble" : {
		"object_id" : 504,
		"sprite" : "bubble",
		"solid" : false,
		"visible" : true,
		"depth" : 1,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"bullet" : {
		"object_id" : 669,
		"sprite" : "bullet",
		"solid" : false,
		"visible" : true,
		"depth" : 0,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"burn" : {
		"object_id" : 589,
		"sprite" : "burn",
		"solid" : false,
		"visible" : true,
		"depth" : 999,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"drip" : {
		"object_id" : 479,
		"sprite" : "drip",
		"solid" : false,
		"visible" : true,
		"depth" : 1,
		"persistent" : false,
		"parent" : "rubble_piece",
		"mask" : null,
		},
	"explosion" : {
		"object_id" : 391,
		"sprite" : "explosion",
		"solid" : false,
		"visible" : true,
		"depth" : 1,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"flame" : {
		"object_id" : 456,
		"sprite" : "flame",
		"solid" : false,
		"visible" : true,
		"depth" : 1,
		"persistent" : false,
		"parent" : "detritus",
		"mask" : null,
		},
	"flame_trail" : {
		"object_id" : 457,
		"sprite" : "flame_trail",
		"solid" : false,
		"visible" : true,
		"depth" : 1,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"flare_spark" : {
		"object_id" : 631,
		"sprite" : "flare_spark",
		"solid" : false,
		"visible" : true,
		"depth" : 150,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"fly" : {
		"object_id" : 776,
		"sprite" : "fly_left",
		"solid" : false,
		"visible" : true,
		"depth" : 0,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"heart" : {
		"object_id" : 624,
		"sprite" : "smooch_heart",
		"solid" : false,
		"visible" : true,
		"depth" : 1,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"items_get" : {
		"object_id" : 595,
		"sprite" : "item_get",
		"solid" : false,
		"visible" : true,
		"depth" : 1,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"laser" : {
		"object_id" : 534,
		"sprite" : "laser",
		"solid" : false,
		"visible" : true,
		"depth" : 1,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"laser_explode" : {
		"object_id" : 536,
		"sprite" : "laser_explode",
		"solid" : false,
		"visible" : true,
		"depth" : 1,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"laser_trail" : {
		"object_id" : 535,
		"sprite" : "laser_trail",
		"solid" : false,
		"visible" : true,
		"depth" : 1,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"lava_drip" : {
		"object_id" : 574,
		"sprite" : "lava_drip",
		"solid" : false,
		"visible" : true,
		"depth" : 1,
		"persistent" : false,
		"parent" : "rubble_piece",
		"mask" : null,
		},
	"leaf" : {
		"object_id" : 742,
		"sprite" : "leaf",
		"solid" : false,
		"visible" : true,
		"depth" : 1,
		"persistent" : false,
		"parent" : "rubble_piece",
		"mask" : null,
		},
	"poof" : {
		"object_id" : 691,
		"sprite" : "poof",
		"solid" : false,
		"visible" : true,
		"depth" : 1,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"psychic_create" : {
		"object_id" : 665,
		"sprite" : "psychic_create",
		"solid" : false,
		"visible" : true,
		"depth" : 1,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"psychic_create2" : {
		"object_id" : 692,
		"sprite" : "psychic_create",
		"solid" : false,
		"visible" : true,
		"depth" : 1,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"psychic_create_p" : {
		"object_id" : 793,
		"sprite" : "psychic_create",
		"solid" : false,
		"visible" : true,
		"depth" : 1,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"psychic_wave" : {
		"object_id" : 664,
		"sprite" : "psychic_wave",
		"solid" : false,
		"visible" : true,
		"depth" : 1,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"psychic_wave_p" : {
		"object_id" : 792,
		"sprite" : "psychic_wave_p",
		"solid" : false,
		"visible" : true,
		"depth" : 1,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"rope_burn" : {
		"object_id" : 651,
		"sprite" : "burn",
		"solid" : false,
		"visible" : true,
		"depth" : 99,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"rubble" : {
		"object_id" : 525,
		"sprite" : "rubble",
		"solid" : false,
		"visible" : true,
		"depth" : 1,
		"persistent" : false,
		"parent" : "rubble_piece",
		"mask" : null,
		},
	"rubble_dark" : {
		"object_id" : 537,
		"sprite" : "rubble_dark",
		"solid" : false,
		"visible" : true,
		"depth" : 1,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"rubble_dark_small" : {
		"object_id" : 538,
		"sprite" : "rubble_dark_small",
		"solid" : false,
		"visible" : true,
		"depth" : 1,
		"persistent" : false,
		"parent" : "rubble_piece",
		"mask" : null,
		},
	"rubble_small" : {
		"object_id" : 526,
		"sprite" : "rubble_small",
		"solid" : false,
		"visible" : true,
		"depth" : 1,
		"persistent" : false,
		"parent" : "rubble_piece",
		"mask" : null,
		},
	"shotgun_blast_left" : {
		"object_id" : 667,
		"sprite" : "shotgun_blast_left",
		"solid" : false,
		"visible" : true,
		"depth" : 0,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"shotgun_blast_right" : {
		"object_id" : 668,
		"sprite" : "shotgun_blast_right",
		"solid" : false,
		"visible" : true,
		"depth" : 0,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"small_collect" : {
		"object_id" : 502,
		"sprite" : "small_collect",
		"solid" : false,
		"visible" : true,
		"depth" : 1,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"smoke_puff" : {
		"object_id" : 490,
		"sprite" : "smoke_puff",
		"solid" : false,
		"visible" : true,
		"depth" : 1,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"volcano_flame" : {
		"object_id" : 679,
		"sprite" : "volcano_flame",
		"solid" : false,
		"visible" : true,
		"depth" : 1,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"web" : {
		"object_id" : 751,
		"sprite" : "web",
		"solid" : false,
		"visible" : true,
		"depth" : 200,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"web_ball" : {
		"object_id" : 750,
		"sprite" : "web_ball",
		"solid" : false,
		"visible" : true,
		"depth" : 1,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"yellow_ball" : {
		"object_id" : 579,
		"sprite" : "yellow_ball",
		"solid" : false,
		"visible" : true,
		"depth" : 1,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"yellow_trail" : {
		"object_id" : 747,
		"sprite" : "yellow_trail",
		"solid" : false,
		"visible" : true,
		"depth" : 1,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"alien" : {
		"object_id" : 636,
		"sprite" : "alien",
		"solid" : false,
		"visible" : true,
		"depth" : 60,
		"persistent" : false,
		"parent" : "enemy",
		"mask" : null,
		},
	"alien_boss" : {
		"object_id" : 658,
		"sprite" : "alien_boss",
		"solid" : false,
		"visible" : true,
		"depth" : 60,
		"persistent" : false,
		"parent" : "enemy",
		"mask" : null,
		},
	"alien_eject" : {
		"object_id" : 637,
		"sprite" : "alien_eject",
		"solid" : false,
		"visible" : true,
		"depth" : 60,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"barrier" : {
		"object_id" : 763,
		"sprite" : "barrier",
		"solid" : false,
		"visible" : true,
		"depth" : 108,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"barrier_emitter" : {
		"object_id" : 762,
		"sprite" : "barrier_emitter",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"bat" : {
		"object_id" : 352,
		"sprite" : "bat_hang",
		"solid" : false,
		"visible" : true,
		"depth" : 40,
		"persistent" : false,
		"parent" : "enemy",
		"mask" : null,
		},
	"caveman" : {
		"object_id" : 325,
		"sprite" : "caveman_left",
		"solid" : false,
		"visible" : true,
		"depth" : 60,
		"persistent" : false,
		"parent" : "enemy",
		"mask" : null,
		},
	"caveman_worship" : {
		"object_id" : 764,
		"sprite" : "caveman_worship_r",
		"solid" : false,
		"visible" : true,
		"depth" : 60,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"dead_fish" : {
		"object_id" : 745,
		"sprite" : "dead_fish_left",
		"solid" : false,
		"visible" : true,
		"depth" : 40,
		"persistent" : false,
		"parent" : "enemy",
		"mask" : null,
		},
	"enemy_sight" : {
		"object_id" : 558,
		"sprite" : "sight",
		"solid" : false,
		"visible" : false,
		"depth" : 0,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"entrance_check" : {
		"object_id" : 625,
		"sprite" : "sight",
		"solid" : false,
		"visible" : false,
		"depth" : 0,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"fire_frog" : {
		"object_id" : 882,
		"sprite" : "fire_frog_left",
		"solid" : false,
		"visible" : true,
		"depth" : 40,
		"persistent" : false,
		"parent" : "enemy",
		"mask" : null,
		},
	"frog" : {
		"object_id" : 554,
		"sprite" : "frog_left",
		"solid" : false,
		"visible" : true,
		"depth" : 40,
		"persistent" : false,
		"parent" : "enemy",
		"mask" : null,
		},
	"ghost" : {
		"object_id" : 736,
		"sprite" : "ghost_right",
		"solid" : false,
		"visible" : true,
		"depth" : 0,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"giant_spider" : {
		"object_id" : 749,
		"sprite" : "giant_spider_flip",
		"solid" : false,
		"visible" : true,
		"depth" : 40,
		"persistent" : false,
		"parent" : "enemy",
		"mask" : null,
		},
	"giant_spider_hang" : {
		"object_id" : 748,
		"sprite" : "giant_spider_hang",
		"solid" : false,
		"visible" : true,
		"depth" : 40,
		"persistent" : false,
		"parent" : "enemy",
		"mask" : null,
		},
	"hawkman" : {
		"object_id" : 588,
		"sprite" : "hawk_left",
		"solid" : false,
		"visible" : true,
		"depth" : 60,
		"persistent" : false,
		"parent" : "enemy",
		"mask" : null,
		},
	"hawkman_worship" : {
		"object_id" : 765,
		"sprite" : "hawk_left",
		"solid" : false,
		"visible" : true,
		"depth" : 0,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"jaws" : {
		"object_id" : 885,
		"sprite" : "jaws_left",
		"solid" : false,
		"visible" : true,
		"depth" : 40,
		"persistent" : false,
		"parent" : "enemy",
		"mask" : null,
		},
	"magma" : {
		"object_id" : 649,
		"sprite" : "magma",
		"solid" : false,
		"visible" : true,
		"depth" : 1,
		"persistent" : false,
		"parent" : "detritus",
		"mask" : null,
		},
	"magma_man" : {
		"object_id" : 648,
		"sprite" : "magma_man_left",
		"solid" : false,
		"visible" : true,
		"depth" : 60,
		"persistent" : false,
		"parent" : "enemy",
		"mask" : null,
		},
	"magma_trail" : {
		"object_id" : 650,
		"sprite" : "flame_trail",
		"solid" : false,
		"visible" : true,
		"depth" : 2,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"man_trap" : {
		"object_id" : 532,
		"sprite" : "man_trap_left",
		"solid" : false,
		"visible" : true,
		"depth" : 60,
		"persistent" : false,
		"parent" : "enemy",
		"mask" : null,
		},
	"monkey" : {
		"object_id" : 778,
		"sprite" : "monkey_left",
		"solid" : false,
		"visible" : true,
		"depth" : 40,
		"persistent" : false,
		"parent" : "enemy",
		"mask" : null,
		},
	"olmec" : {
		"object_id" : 559,
		"sprite" : "olmec_start1",
		"solid" : false,
		"visible" : true,
		"depth" : 40,
		"persistent" : false,
		"parent" : "moving_solid",
		"mask" : null,
		},
	"olmec_debris" : {
		"object_id" : 642,
		"sprite" : "olmec_debris",
		"solid" : false,
		"visible" : true,
		"depth" : 1,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"olmec_slam" : {
		"object_id" : 560,
		"sprite" : "olmec_slam",
		"solid" : false,
		"visible" : false,
		"depth" : 0,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"piranha" : {
		"object_id" : 481,
		"sprite" : "piranha_left",
		"solid" : false,
		"visible" : true,
		"depth" : 40,
		"persistent" : false,
		"parent" : "enemy",
		"mask" : null,
		},
	"scarab" : {
		"object_id" : 772,
		"sprite" : "scarab",
		"solid" : false,
		"visible" : true,
		"depth" : 40,
		"persistent" : false,
		"parent" : "enemy",
		"mask" : null,
		},
	"skeleton" : {
		"object_id" : 652,
		"sprite" : "skeleton_create_l",
		"solid" : false,
		"visible" : true,
		"depth" : 60,
		"persistent" : false,
		"parent" : "enemy",
		"mask" : null,
		},
	"snake" : {
		"object_id" : 552,
		"sprite" : "snake_left",
		"solid" : false,
		"visible" : true,
		"depth" : 60,
		"persistent" : false,
		"parent" : "enemy",
		"mask" : null,
		},
	"spider" : {
		"object_id" : 366,
		"sprite" : "spider_flip",
		"solid" : false,
		"visible" : true,
		"depth" : 40,
		"persistent" : false,
		"parent" : "enemy",
		"mask" : null,
		},
	"spider_hang" : {
		"object_id" : 367,
		"sprite" : "spider_hang",
		"solid" : false,
		"visible" : true,
		"depth" : 40,
		"persistent" : false,
		"parent" : "enemy",
		"mask" : null,
		},
	"tomb_lord" : {
		"object_id" : 775,
		"sprite" : "tomb_lord_left",
		"solid" : false,
		"visible" : true,
		"depth" : 60,
		"persistent" : false,
		"parent" : "enemy",
		"mask" : null,
		},
	"ufo" : {
		"object_id" : 518,
		"sprite" : "ufo",
		"solid" : false,
		"visible" : true,
		"depth" : 40,
		"persistent" : false,
		"parent" : "enemy",
		"mask" : null,
		},
	"ufo_crash" : {
		"object_id" : 797,
		"sprite" : "ufo_crash",
		"solid" : false,
		"visible" : true,
		"depth" : 0,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"vampire" : {
		"object_id" : 915,
		"sprite" : "vampire_left",
		"solid" : false,
		"visible" : true,
		"depth" : 60,
		"persistent" : false,
		"parent" : "enemy",
		"mask" : null,
		},
	"yeti" : {
		"object_id" : 572,
		"sprite" : "yeti_left",
		"solid" : false,
		"visible" : true,
		"depth" : 60,
		"persistent" : false,
		"parent" : "enemy",
		"mask" : null,
		},
	"yeti_king" : {
		"object_id" : 877,
		"sprite" : "yeti_king_left",
		"solid" : false,
		"visible" : true,
		"depth" : 60,
		"persistent" : false,
		"parent" : "enemy",
		"mask" : null,
		},
	"zombie" : {
		"object_id" : 744,
		"sprite" : "zombie_left",
		"solid" : false,
		"visible" : true,
		"depth" : 40,
		"persistent" : false,
		"parent" : "enemy",
		"mask" : null,
		},
	"check_box" : {
		"object_id" : 757,
		"sprite" : "box_checked",
		"solid" : false,
		"visible" : true,
		"depth" : 0,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"check_box2" : {
		"object_id" : 777,
		"sprite" : "box_checked",
		"solid" : false,
		"visible" : true,
		"depth" : 0,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"check_box3" : {
		"object_id" : 796,
		"sprite" : "box_checked",
		"solid" : false,
		"visible" : true,
		"depth" : 0,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"check_box4" : {
		"object_id" : 802,
		"sprite" : "box_checked",
		"solid" : false,
		"visible" : true,
		"depth" : 0,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"joy_config_button" : {
		"object_id" : 807,
		"sprite" : "joy_config_button",
		"solid" : false,
		"visible" : true,
		"depth" : 0,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"key_config_button" : {
		"object_id" : 804,
		"sprite" : "key_config_button",
		"solid" : false,
		"visible" : true,
		"depth" : 0,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"ok_button" : {
		"object_id" : 758,
		"sprite" : "ok_button",
		"solid" : false,
		"visible" : true,
		"depth" : 0,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"radio_box" : {
		"object_id" : 755,
		"sprite" : "box",
		"solid" : false,
		"visible" : true,
		"depth" : 0,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"slider1" : {
		"object_id" : 873,
		"sprite" : "slider",
		"solid" : false,
		"visible" : true,
		"depth" : 0,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"slider2" : {
		"object_id" : 874,
		"sprite" : "slider",
		"solid" : false,
		"visible" : true,
		"depth" : 0,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"slider_bg" : {
		"object_id" : 872,
		"sprite" : "slider_bg",
		"solid" : false,
		"visible" : true,
		"depth" : 0,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"arrow" : {
		"object_id" : 465,
		"sprite" : "arrow_right",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "item",
		"mask" : null,
		},
	"ball" : {
		"object_id" : 922,
		"sprite" : "ball",
		"solid" : false,
		"visible" : true,
		"depth" : 99,
		"persistent" : false,
		"parent" : "item",
		"mask" : null,
		},
	"ball2" : {
		"object_id" : 926,
		"sprite" : "ball",
		"solid" : false,
		"visible" : true,
		"depth" : 99,
		"persistent" : false,
		"parent" : "item",
		"mask" : null,
		},
	"basketball" : {
		"object_id" : 719,
		"sprite" : "basketball",
		"solid" : true,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "item",
		"mask" : null,
		},
	"bomb" : {
		"object_id" : 454,
		"sprite" : "bomb",
		"solid" : false,
		"visible" : true,
		"depth" : 99,
		"persistent" : false,
		"parent" : "item",
		"mask" : null,
		},
	"bow" : {
		"object_id" : 770,
		"sprite" : "bow_right",
		"solid" : false,
		"visible" : true,
		"depth" : 101,
		"persistent" : false,
		"parent" : "item",
		"mask" : null,
		},
	"chain" : {
		"object_id" : 923,
		"sprite" : "chain",
		"solid" : false,
		"visible" : true,
		"depth" : 1,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"chain2" : {
		"object_id" : 927,
		"sprite" : "chain",
		"solid" : false,
		"visible" : true,
		"depth" : 1,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"crystal_skull" : {
		"object_id" : 883,
		"sprite" : "crystal_skull",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "gold_idol",
		"mask" : null,
		},
	"dice" : {
		"object_id" : 773,
		"sprite" : "dice1",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "item",
		"mask" : null,
		},
	"fire_frog_bomb" : {
		"object_id" : 887,
		"sprite" : "fire_frog_armed_l",
		"solid" : false,
		"visible" : true,
		"depth" : 99,
		"persistent" : false,
		"parent" : "item",
		"mask" : null,
		},
	"fish_bone" : {
		"object_id" : 482,
		"sprite" : "fish_bone",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "item",
		"mask" : null,
		},
	"flare" : {
		"object_id" : 629,
		"sprite" : "flare",
		"solid" : false,
		"visible" : true,
		"depth" : 30,
		"persistent" : false,
		"parent" : "item",
		"mask" : null,
		},
	"gold_idol" : {
		"object_id" : 520,
		"sprite" : "gold_idol",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "item",
		"mask" : null,
		},
	"jar" : {
		"object_id" : 635,
		"sprite" : "jar",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "item",
		"mask" : null,
		},
	"lamp_item" : {
		"object_id" : 928,
		"sprite" : "lamp_item",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "item",
		"mask" : null,
		},
	"lamp_red_item" : {
		"object_id" : 929,
		"sprite" : "lamp_red_item",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "item",
		"mask" : null,
		},
	"machete" : {
		"object_id" : 705,
		"sprite" : "machete_right",
		"solid" : false,
		"visible" : true,
		"depth" : 101,
		"persistent" : false,
		"parent" : "item",
		"mask" : null,
		},
	"machete_pre" : {
		"object_id" : 707,
		"sprite" : "machete_pre_r",
		"solid" : false,
		"visible" : true,
		"depth" : 1,
		"persistent" : false,
		"parent" : "whip_pre",
		"mask" : null,
		},
	"mattock" : {
		"object_id" : 733,
		"sprite" : "mattock_right",
		"solid" : false,
		"visible" : true,
		"depth" : 101,
		"persistent" : false,
		"parent" : "item",
		"mask" : null,
		},
	"mattock_head" : {
		"object_id" : 752,
		"sprite" : "mattock_head",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "item",
		"mask" : null,
		},
	"mattock_hit" : {
		"object_id" : 735,
		"sprite" : "mattock_hit_r",
		"solid" : false,
		"visible" : true,
		"depth" : 1,
		"persistent" : false,
		"parent" : "whip",
		"mask" : null,
		},
	"mattock_pre" : {
		"object_id" : 734,
		"sprite" : "mattock_pre_r",
		"solid" : false,
		"visible" : true,
		"depth" : 1,
		"persistent" : false,
		"parent" : "whip_pre",
		"mask" : null,
		},
	"parachute" : {
		"object_id" : 703,
		"sprite" : "para_open",
		"solid" : false,
		"visible" : true,
		"depth" : 900,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"pistol" : {
		"object_id" : 708,
		"sprite" : "pistol_right",
		"solid" : false,
		"visible" : true,
		"depth" : 101,
		"persistent" : false,
		"parent" : "item",
		"mask" : null,
		},
	"rock" : {
		"object_id" : 450,
		"sprite" : "rock",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "item",
		"mask" : null,
		},
	"rope" : {
		"object_id" : 470,
		"sprite" : "rope",
		"solid" : false,
		"visible" : true,
		"depth" : 200,
		"persistent" : false,
		"parent" : "ladder",
		"mask" : null,
		},
	"rope_throw" : {
		"object_id" : 469,
		"sprite" : "rope_end",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "item",
		"mask" : null,
		},
	"rope_top" : {
		"object_id" : 471,
		"sprite" : "rope_top",
		"solid" : false,
		"visible" : true,
		"depth" : 200,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"sceptre" : {
		"object_id" : 788,
		"sprite" : "sceptre_right",
		"solid" : false,
		"visible" : true,
		"depth" : 101,
		"persistent" : false,
		"parent" : "item",
		"mask" : null,
		},
	"shotgun" : {
		"object_id" : 670,
		"sprite" : "shotgun_right",
		"solid" : false,
		"visible" : true,
		"depth" : 101,
		"persistent" : false,
		"parent" : "item",
		"mask" : null,
		},
	"skull" : {
		"object_id" : 663,
		"sprite" : "skull",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "item",
		"mask" : null,
		},
	"slash" : {
		"object_id" : 706,
		"sprite" : "slash_right",
		"solid" : false,
		"visible" : true,
		"depth" : 1,
		"persistent" : false,
		"parent" : "whip",
		"mask" : null,
		},
	"teleporter" : {
		"object_id" : 810,
		"sprite" : "teleporter",
		"solid" : false,
		"visible" : true,
		"depth" : 101,
		"persistent" : false,
		"parent" : "item",
		"mask" : null,
		},
	"web_cannon" : {
		"object_id" : 769,
		"sprite" : "web_cannon_r",
		"solid" : false,
		"visible" : true,
		"depth" : 101,
		"persistent" : false,
		"parent" : "item",
		"mask" : null,
		},
	"whip" : {
		"object_id" : 576,
		"sprite" : "whip_right",
		"solid" : false,
		"visible" : true,
		"depth" : 1,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"whip_pre" : {
		"object_id" : 596,
		"sprite" : "whip_pre_r",
		"solid" : false,
		"visible" : true,
		"depth" : 1,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"alien_boss_tile" : {
		"object_id" : 942,
		"sprite" : "alien_boss_tile",
		"solid" : false,
		"visible" : true,
		"depth" : 200,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"alien_tile" : {
		"object_id" : 842,
		"sprite" : "alien",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"bat_tile" : {
		"object_id" : 814,
		"sprite" : "bat_hang",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"bomb_bag_tile" : {
		"object_id" : 853,
		"sprite" : "bomb_bag_tile",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"bomb_box_tile" : {
		"object_id" : 854,
		"sprite" : "bomb_box_tile",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"bomb_paste_tile" : {
		"object_id" : 855,
		"sprite" : "bomb_paste_tile",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"bones_tile" : {
		"object_id" : 848,
		"sprite" : "fake_bones_left",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"bow_tile" : {
		"object_id" : 869,
		"sprite" : "bow_tile",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"cape_tile" : {
		"object_id" : 859,
		"sprite" : "cape_tile",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"caveman_tile" : {
		"object_id" : 832,
		"sprite" : "caveman_left",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"chest_tile" : {
		"object_id" : 823,
		"sprite" : "chest_tile",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"compass_tile" : {
		"object_id" : 870,
		"sprite" : "compass_tile",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"crate_tile" : {
		"object_id" : 824,
		"sprite" : "crate_tile",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"crystal_skull_tile" : {
		"object_id" : 889,
		"sprite" : "crystal_skull_tile",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"damsel_tile" : {
		"object_id" : 826,
		"sprite" : "damsel_left_ico",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"diamond_tile" : {
		"object_id" : 830,
		"sprite" : "diamond_tile",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"edit_button" : {
		"object_id" : 847,
		"sprite" : "edit_button",
		"solid" : false,
		"visible" : true,
		"depth" : 0,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"emerald_big_tile" : {
		"object_id" : 820,
		"sprite" : "emerald_big_tile",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"fire_frog_tile" : {
		"object_id" : 892,
		"sprite" : "fire_frog_left",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"frog_tile" : {
		"object_id" : 839,
		"sprite" : "frog_left",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"giant_spider_tile" : {
		"object_id" : 831,
		"sprite" : "giant_spider_hang",
		"solid" : false,
		"visible" : true,
		"depth" : 200,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"gloves_tile" : {
		"object_id" : 858,
		"sprite" : "gloves_tile",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"gold_bars_tile" : {
		"object_id" : 819,
		"sprite" : "gold_bars_tile",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"gold_bar_tile" : {
		"object_id" : 818,
		"sprite" : "gold_bar_tile",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"gold_idol_tile" : {
		"object_id" : 829,
		"sprite" : "gold_idol_tile",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"hawkman_tile" : {
		"object_id" : 834,
		"sprite" : "hawk_left",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"ice_tile" : {
		"object_id" : 895,
		"sprite" : "ice",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"jar_tile" : {
		"object_id" : 828,
		"sprite" : "jar_tile",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"jetpack_tile" : {
		"object_id" : 871,
		"sprite" : "jetpack_tile",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"lava_tile" : {
		"object_id" : 846,
		"sprite" : "lava",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"load_button" : {
		"object_id" : 905,
		"sprite" : "load_button",
		"solid" : false,
		"visible" : true,
		"depth" : 1,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"machete_tile" : {
		"object_id" : 862,
		"sprite" : "machete_tile",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"man_trap_tile" : {
		"object_id" : 835,
		"sprite" : "man_trap_left",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"mattock_tile" : {
		"object_id" : 864,
		"sprite" : "mattock_tile",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"mega_mouth_tile" : {
		"object_id" : 891,
		"sprite" : "mega_mouth_tile",
		"solid" : false,
		"visible" : true,
		"depth" : 200,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"mitt_tile" : {
		"object_id" : 863,
		"sprite" : "mitt_tile",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"monkey_tile" : {
		"object_id" : 838,
		"sprite" : "monkey_left",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"new_button" : {
		"object_id" : 912,
		"sprite" : "new_button",
		"solid" : false,
		"visible" : true,
		"depth" : 0,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"parachute_tile" : {
		"object_id" : 861,
		"sprite" : "parachute_tile",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"piranha_tile" : {
		"object_id" : 843,
		"sprite" : "piranha_tile",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"pistol_tile" : {
		"object_id" : 865,
		"sprite" : "pistol_tile",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"rock_tile" : {
		"object_id" : 827,
		"sprite" : "rock_tile",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"rope_pile_tile" : {
		"object_id" : 856,
		"sprite" : "rope_pile_tile",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"ruby_big_tile" : {
		"object_id" : 822,
		"sprite" : "ruby_big_tile",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"sapphire_big_tile" : {
		"object_id" : 821,
		"sprite" : "sapphire_big_tile",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"shopkeeper_tile" : {
		"object_id" : 841,
		"sprite" : "shop_left_ico",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"shotgun_tile" : {
		"object_id" : 866,
		"sprite" : "shotgun_tile",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"skeleton_tile" : {
		"object_id" : 836,
		"sprite" : "skeleton_left",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"smash_trap_tile" : {
		"object_id" : 850,
		"sprite" : "smash_trap",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"snake_tile" : {
		"object_id" : 815,
		"sprite" : "snake_left",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"spear_trap_tile_bot" : {
		"object_id" : 852,
		"sprite" : "spear_trap2",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"spear_trap_tile_top" : {
		"object_id" : 851,
		"sprite" : "spear_trap1",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"spectacles_tile" : {
		"object_id" : 857,
		"sprite" : "spectacles_tile",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"spider_tile" : {
		"object_id" : 816,
		"sprite" : "spider_hang",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"spike_shoes_tile" : {
		"object_id" : 888,
		"sprite" : "spike_shoes_tile",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"spring_shoes_tile" : {
		"object_id" : 860,
		"sprite" : "spring_shoes_tile",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"spring_trap_tile" : {
		"object_id" : 893,
		"sprite" : "spring_trap",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"teleporter_tile" : {
		"object_id" : 868,
		"sprite" : "teleporter_tile",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"test_button" : {
		"object_id" : 911,
		"sprite" : "test_button",
		"solid" : false,
		"visible" : true,
		"depth" : 0,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"tomb_lord_tile" : {
		"object_id" : 837,
		"sprite" : "tomb_lord_left",
		"solid" : false,
		"visible" : true,
		"depth" : 200,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"ufo_tile" : {
		"object_id" : 849,
		"sprite" : "ufo",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"vampire_tile" : {
		"object_id" : 925,
		"sprite" : "vampire_left",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"water_tile" : {
		"object_id" : 845,
		"sprite" : "water",
		"solid" : false,
		"visible" : true,
		"depth" : 999,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"web_cannon_tile" : {
		"object_id" : 867,
		"sprite" : "web_cannon_tile",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"web_tile" : {
		"object_id" : 896,
		"sprite" : "web_tile",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"yeti_king_tile" : {
		"object_id" : 890,
		"sprite" : "yeti_king_left",
		"solid" : false,
		"visible" : true,
		"depth" : 200,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"yeti_tile" : {
		"object_id" : 833,
		"sprite" : "yeti_left",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"zombie_tile" : {
		"object_id" : 840,
		"sprite" : "zombie_left",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"black" : {
		"object_id" : 561,
		"sprite" : "black",
		"solid" : false,
		"visible" : true,
		"depth" : 1,
		"persistent" : false,
		"parent" : "menu",
		"mask" : null,
		},
	"black_bg" : {
		"object_id" : 639,
		"sprite" : "black",
		"solid" : false,
		"visible" : true,
		"depth" : 9999999,
		"persistent" : false,
		"parent" : "menu",
		"mask" : null,
		},
	"cave_up" : {
		"object_id" : 506,
		"sprite" : "cave_up",
		"solid" : false,
		"visible" : true,
		"depth" : 0,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"hint_hand" : {
		"object_id" : 760,
		"sprite" : "hint_point",
		"solid" : false,
		"visible" : true,
		"depth" : 0,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"menu_bottom" : {
		"object_id" : 565,
		"sprite" : "menu_bottom",
		"solid" : false,
		"visible" : true,
		"depth" : 1,
		"persistent" : false,
		"parent" : "menu",
		"mask" : null,
		},
	"menu_left" : {
		"object_id" : 566,
		"sprite" : "menu_left",
		"solid" : false,
		"visible" : true,
		"depth" : 1,
		"persistent" : false,
		"parent" : "menu",
		"mask" : null,
		},
	"menu_ll" : {
		"object_id" : 570,
		"sprite" : "menu_ll",
		"solid" : false,
		"visible" : true,
		"depth" : 1,
		"persistent" : false,
		"parent" : "menu",
		"mask" : null,
		},
	"menu_lr" : {
		"object_id" : 571,
		"sprite" : "menu_lr",
		"solid" : false,
		"visible" : true,
		"depth" : 1,
		"persistent" : false,
		"parent" : "menu",
		"mask" : null,
		},
	"menu_right" : {
		"object_id" : 567,
		"sprite" : "menu_right",
		"solid" : false,
		"visible" : true,
		"depth" : 1,
		"persistent" : false,
		"parent" : "menu",
		"mask" : null,
		},
	"menu_sel" : {
		"object_id" : 902,
		"sprite" : "menu_sel_off",
		"solid" : false,
		"visible" : true,
		"depth" : 1,
		"persistent" : false,
		"parent" : "menu",
		"mask" : null,
		},
	"menu_top" : {
		"object_id" : 564,
		"sprite" : "menu_top",
		"solid" : false,
		"visible" : true,
		"depth" : 1,
		"persistent" : false,
		"parent" : "menu",
		"mask" : null,
		},
	"menu_ul" : {
		"object_id" : 568,
		"sprite" : "menu_ul",
		"solid" : false,
		"visible" : true,
		"depth" : 1,
		"persistent" : false,
		"parent" : "menu",
		"mask" : null,
		},
	"menu_ur" : {
		"object_id" : 569,
		"sprite" : "menu_ur",
		"solid" : false,
		"visible" : true,
		"depth" : 1,
		"persistent" : false,
		"parent" : "menu",
		"mask" : null,
		},
	"page_down" : {
		"object_id" : 901,
		"sprite" : "page_down",
		"solid" : false,
		"visible" : true,
		"depth" : 0,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"page_up" : {
		"object_id" : 900,
		"sprite" : "page_up",
		"solid" : false,
		"visible" : true,
		"depth" : 0,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"p_dummy" : {
		"object_id" : 508,
		"sprite" : "run_left",
		"solid" : false,
		"visible" : true,
		"depth" : 50,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"p_dummy2" : {
		"object_id" : 612,
		"sprite" : "run_left",
		"solid" : false,
		"visible" : true,
		"depth" : 997,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"p_dummy3" : {
		"object_id" : 616,
		"sprite" : "run_left",
		"solid" : false,
		"visible" : true,
		"depth" : 40,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"p_dummy4" : {
		"object_id" : 618,
		"sprite" : "run_left",
		"solid" : false,
		"visible" : true,
		"depth" : 50,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"p_dummy5" : {
		"object_id" : 634,
		"sprite" : "run_left",
		"solid" : false,
		"visible" : true,
		"depth" : 50,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"p_dummy6" : {
		"object_id" : 898,
		"sprite" : "stand_left",
		"solid" : false,
		"visible" : true,
		"depth" : 50,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"wal_damsel" : {
		"object_id" : 903,
		"sprite" : "wal_damsel",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"bg_end3" : {
		"object_id" : 632,
		"sprite" : "bg_end3",
		"solid" : false,
		"visible" : true,
		"depth" : 9999,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"big_chest" : {
		"object_id" : 583,
		"sprite" : "big_chest",
		"solid" : false,
		"visible" : true,
		"depth" : 0,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"big_treasure" : {
		"object_id" : 603,
		"sprite" : "big_treasure",
		"solid" : true,
		"visible" : true,
		"depth" : 997,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"end2_bg" : {
		"object_id" : 606,
		"sprite" : "end2_bg",
		"solid" : false,
		"visible" : true,
		"depth" : 9999,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"end_plat" : {
		"object_id" : 582,
		"sprite" : "end_plat",
		"solid" : true,
		"visible" : true,
		"depth" : 999,
		"persistent" : false,
		"parent" : "solid",
		"mask" : null,
		},
	"end_wall" : {
		"object_id" : 924,
		"sprite" : "end_wall",
		"solid" : false,
		"visible" : true,
		"depth" : 9999,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"lava_spray" : {
		"object_id" : 604,
		"sprite" : "lava_spray",
		"solid" : false,
		"visible" : true,
		"depth" : 999,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"player_sil" : {
		"object_id" : 608,
		"sprite" : "player_sil",
		"solid" : false,
		"visible" : true,
		"depth" : 1,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"treasure_sil" : {
		"object_id" : 609,
		"sprite" : "treasure_sil",
		"solid" : false,
		"visible" : true,
		"depth" : 1,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"bat_intro" : {
		"object_id" : 783,
		"sprite" : "bat_left",
		"solid" : false,
		"visible" : true,
		"depth" : 0,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"camel" : {
		"object_id" : 690,
		"sprite" : "camel",
		"solid" : false,
		"visible" : true,
		"depth" : 200,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"caravan" : {
		"object_id" : 768,
		"sprite" : "caravan1",
		"solid" : false,
		"visible" : true,
		"depth" : 200,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"desert" : {
		"object_id" : 610,
		"sprite" : "desert",
		"solid" : true,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "solid",
		"mask" : null,
		},
	"desert2" : {
		"object_id" : 917,
		"sprite" : "desert2",
		"solid" : true,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "solid",
		"mask" : null,
		},
	"desert_scroll" : {
		"object_id" : 682,
		"sprite" : "desert",
		"solid" : true,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"desert_scroll2" : {
		"object_id" : 918,
		"sprite" : "desert2",
		"solid" : true,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"desert_top" : {
		"object_id" : 611,
		"sprite" : "desert_top",
		"solid" : false,
		"visible" : true,
		"depth" : 10,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"desert_top_scroll" : {
		"object_id" : 684,
		"sprite" : "desert_top",
		"solid" : false,
		"visible" : true,
		"depth" : 10,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"intro_bg" : {
		"object_id" : 619,
		"sprite" : "intro_bg",
		"solid" : false,
		"visible" : true,
		"depth" : 9999,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"moon" : {
		"object_id" : 620,
		"sprite" : "moon",
		"solid" : false,
		"visible" : true,
		"depth" : 99999,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"palm_tree" : {
		"object_id" : 681,
		"sprite" : "palm_tree",
		"solid" : false,
		"visible" : true,
		"depth" : 999,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"palm_tree_dark" : {
		"object_id" : 627,
		"sprite" : "palm_tree_dark",
		"solid" : false,
		"visible" : true,
		"depth" : 999,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"palm_tree_scroll" : {
		"object_id" : 689,
		"sprite" : "palm_tree",
		"solid" : false,
		"visible" : true,
		"depth" : 999,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"shrub" : {
		"object_id" : 680,
		"sprite" : "shrub",
		"solid" : false,
		"visible" : true,
		"depth" : 998,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"shrub_dark" : {
		"object_id" : 628,
		"sprite" : "shrub_dark",
		"solid" : false,
		"visible" : true,
		"depth" : 998,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"shrub_scroll" : {
		"object_id" : 688,
		"sprite" : "shrub",
		"solid" : false,
		"visible" : true,
		"depth" : 998,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"basket" : {
		"object_id" : 716,
		"sprite" : "basket",
		"solid" : false,
		"visible" : true,
		"depth" : 99,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"bat_target" : {
		"object_id" : 940,
		"sprite" : "bat_left",
		"solid" : false,
		"visible" : true,
		"depth" : 0,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"button_highscore" : {
		"object_id" : 641,
		"sprite" : "button",
		"solid" : false,
		"visible" : true,
		"depth" : 999,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"copy" : {
		"object_id" : 943,
		"sprite" : "copy",
		"solid" : false,
		"visible" : true,
		"depth" : 0,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"level13_sign" : {
		"object_id" : 879,
		"sprite" : "level13_sign",
		"solid" : false,
		"visible" : true,
		"depth" : 999,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"level5_sign" : {
		"object_id" : 674,
		"sprite" : "level5_sign",
		"solid" : false,
		"visible" : true,
		"depth" : 999,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"level9_sign" : {
		"object_id" : 675,
		"sprite" : "level9_sign",
		"solid" : false,
		"visible" : true,
		"depth" : 999,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"multi_trophy" : {
		"object_id" : 939,
		"sprite" : "multi_gold",
		"solid" : false,
		"visible" : true,
		"depth" : 900,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"new" : {
		"object_id" : 761,
		"sprite" : "new",
		"solid" : false,
		"visible" : true,
		"depth" : 0,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"quit_sign" : {
		"object_id" : 626,
		"sprite" : "quit_sign",
		"solid" : false,
		"visible" : true,
		"depth" : 999,
		"persistent" : false,
		"parent" : "solid",
		"mask" : null,
		},
	"reset_sign" : {
		"object_id" : 640,
		"sprite" : "reset_sign",
		"solid" : false,
		"visible" : true,
		"depth" : 999,
		"persistent" : false,
		"parent" : "solid",
		"mask" : null,
		},
	"rim" : {
		"object_id" : 717,
		"sprite" : "rim",
		"solid" : false,
		"visible" : true,
		"depth" : 99,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"rim_deflect" : {
		"object_id" : 720,
		"sprite" : "rim_deflect",
		"solid" : false,
		"visible" : true,
		"depth" : 99,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"scores_sign" : {
		"object_id" : 660,
		"sprite" : "scores_sign",
		"solid" : false,
		"visible" : true,
		"depth" : 999,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"start_sign" : {
		"object_id" : 659,
		"sprite" : "start_sign",
		"solid" : false,
		"visible" : true,
		"depth" : 999,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"target" : {
		"object_id" : 771,
		"sprite" : "target",
		"solid" : false,
		"visible" : true,
		"depth" : 0,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"title_bg" : {
		"object_id" : 547,
		"sprite" : "title_bg",
		"solid" : false,
		"visible" : true,
		"depth" : 999999,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"title_logo" : {
		"object_id" : 546,
		"sprite" : "title",
		"solid" : false,
		"visible" : true,
		"depth" : 1,
		"persistent" : false,
		"parent" : "solid",
		"mask" : null,
		},
	"trophy" : {
		"object_id" : 699,
		"sprite" : "bronze_trophy",
		"solid" : false,
		"visible" : true,
		"depth" : 900,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"tutorial_sign" : {
		"object_id" : 799,
		"sprite" : "tutorial_sign",
		"solid" : false,
		"visible" : true,
		"depth" : 999,
		"persistent" : false,
		"parent" : "solid",
		"mask" : null,
		},
	"x_change" : {
		"object_id" : 725,
		"sprite" : "exit",
		"solid" : false,
		"visible" : true,
		"depth" : 999999,
		"persistent" : false,
		"parent" : "x_start",
		"mask" : null,
		},
	"x_change2" : {
		"object_id" : 938,
		"sprite" : "exit",
		"solid" : false,
		"visible" : true,
		"depth" : 999999,
		"persistent" : false,
		"parent" : "x_start",
		"mask" : null,
		},
	"x_end" : {
		"object_id" : 581,
		"sprite" : "exit",
		"solid" : false,
		"visible" : true,
		"depth" : 9000,
		"persistent" : false,
		"parent" : "x_start",
		"mask" : null,
		},
	"x_moon" : {
		"object_id" : 695,
		"sprite" : "exit",
		"solid" : false,
		"visible" : true,
		"depth" : 999999,
		"persistent" : false,
		"parent" : "x_start",
		"mask" : null,
		},
	"x_scores" : {
		"object_id" : 550,
		"sprite" : "exit",
		"solid" : false,
		"visible" : true,
		"depth" : 999999,
		"persistent" : false,
		"parent" : "x_start",
		"mask" : null,
		},
	"x_shortcut13" : {
		"object_id" : 880,
		"sprite" : "exit",
		"solid" : false,
		"visible" : true,
		"depth" : 999999,
		"persistent" : false,
		"parent" : "x_start",
		"mask" : null,
		},
	"x_shortcut5" : {
		"object_id" : 676,
		"sprite" : "exit",
		"solid" : false,
		"visible" : true,
		"depth" : 999999,
		"persistent" : false,
		"parent" : "x_start",
		"mask" : null,
		},
	"x_shortcut9" : {
		"object_id" : 677,
		"sprite" : "exit",
		"solid" : false,
		"visible" : true,
		"depth" : 999999,
		"persistent" : false,
		"parent" : "x_start",
		"mask" : null,
		},
	"x_stars" : {
		"object_id" : 696,
		"sprite" : "exit",
		"solid" : false,
		"visible" : true,
		"depth" : 999999,
		"persistent" : false,
		"parent" : "x_start",
		"mask" : null,
		},
	"x_start" : {
		"object_id" : 549,
		"sprite" : "exit",
		"solid" : false,
		"visible" : true,
		"depth" : 999999,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"x_sun" : {
		"object_id" : 694,
		"sprite" : "exit",
		"solid" : false,
		"visible" : true,
		"depth" : 999999,
		"persistent" : false,
		"parent" : "x_start",
		"mask" : null,
		},
	"x_title" : {
		"object_id" : 551,
		"sprite" : "exit",
		"solid" : false,
		"visible" : true,
		"depth" : 999999,
		"persistent" : false,
		"parent" : "x_start",
		"mask" : null,
		},
	"x_tutorial" : {
		"object_id" : 800,
		"sprite" : "exit",
		"solid" : false,
		"visible" : true,
		"depth" : 999999,
		"persistent" : false,
		"parent" : "x_start",
		"mask" : null,
		},
	"arrow_repeater_l" : {
		"object_id" : 724,
		"sprite" : "arrow_trap_left",
		"solid" : false,
		"visible" : true,
		"depth" : 110,
		"persistent" : false,
		"parent" : "solid",
		"mask" : null,
		},
	"arrow_repeater_r" : {
		"object_id" : 723,
		"sprite" : "arrow_trap_right",
		"solid" : false,
		"visible" : true,
		"depth" : 110,
		"persistent" : false,
		"parent" : "solid",
		"mask" : null,
		},
	"arrow_trap_left" : {
		"object_id" : 693,
		"sprite" : "arrow_trap_left",
		"solid" : false,
		"visible" : true,
		"depth" : 110,
		"persistent" : false,
		"parent" : "solid",
		"mask" : null,
		},
	"arrow_trap_left_lit" : {
		"object_id" : 909,
		"sprite" : "arrow_trap_left_lit",
		"solid" : false,
		"visible" : true,
		"depth" : 110,
		"persistent" : false,
		"parent" : "arrow_trap_left",
		"mask" : null,
		},
	"arrow_trap_right" : {
		"object_id" : 463,
		"sprite" : "arrow_trap_right",
		"solid" : false,
		"visible" : true,
		"depth" : 110,
		"persistent" : false,
		"parent" : "solid",
		"mask" : null,
		},
	"arrow_trap_right_lit" : {
		"object_id" : 908,
		"sprite" : "arrow_trap_right_lit",
		"solid" : false,
		"visible" : true,
		"depth" : 110,
		"persistent" : false,
		"parent" : "arrow_trap_right",
		"mask" : null,
		},
	"arrow_trap_test" : {
		"object_id" : 934,
		"sprite" : "red",
		"solid" : false,
		"visible" : false,
		"depth" : 0,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"boulder" : {
		"object_id" : 521,
		"sprite" : "boulder",
		"solid" : false,
		"visible" : true,
		"depth" : 200,
		"persistent" : false,
		"parent" : "moving_solid",
		"mask" : null,
		},
	"ceiling_trap" : {
		"object_id" : 542,
		"sprite" : "block",
		"solid" : false,
		"visible" : true,
		"depth" : 60,
		"persistent" : false,
		"parent" : "moving_solid",
		"mask" : null,
		},
	"door" : {
		"object_id" : 544,
		"sprite" : "door",
		"solid" : false,
		"visible" : true,
		"depth" : 9000,
		"persistent" : false,
		"parent" : "moving_solid",
		"mask" : null,
		},
	"giant_tiki_head" : {
		"object_id" : 522,
		"sprite" : "giant_tiki_head",
		"solid" : false,
		"visible" : true,
		"depth" : 997,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"smash_trap" : {
		"object_id" : 540,
		"sprite" : "smash_trap",
		"solid" : false,
		"visible" : true,
		"depth" : 60,
		"persistent" : false,
		"parent" : "moving_solid",
		"mask" : null,
		},
	"smash_trap_lit" : {
		"object_id" : 914,
		"sprite" : "smash_trap_lit",
		"solid" : false,
		"visible" : true,
		"depth" : 60,
		"persistent" : false,
		"parent" : "moving_solid",
		"mask" : null,
		},
	"spears_left" : {
		"object_id" : 528,
		"sprite" : "spears_left",
		"solid" : false,
		"visible" : true,
		"depth" : 999,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"spear_trap_bottom" : {
		"object_id" : 531,
		"sprite" : "spear_trap2",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "solid",
		"mask" : null,
		},
	"spear_trap_lit" : {
		"object_id" : 907,
		"sprite" : "spear_trap_lit",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "spear_trap_top",
		"mask" : null,
		},
	"spear_trap_top" : {
		"object_id" : 527,
		"sprite" : "spear_trap1",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : "solid",
		"mask" : null,
		},
	"spikes" : {
		"object_id" : 447,
		"sprite" : "spikes",
		"solid" : false,
		"visible" : true,
		"depth" : 120,
		"persistent" : false,
		"parent" : "drawn_sprite",
		"mask" : null,
		},
	"spring_trap" : {
		"object_id" : 875,
		"sprite" : "spring_trap",
		"solid" : false,
		"visible" : true,
		"depth" : 100,
		"persistent" : false,
		"parent" : null,
		"mask" : null,
		},
	"temp" : {
		"object_id" : 466,
		"sprite" : "arrow_trap_left",
		"solid" : true,
		"visible" : true,
		"depth" : 110,
		"persistent" : false,
		"parent" : "solid",
		"mask" : null,
		},
	"thwomp_trap" : {
		"object_id" : 539,
		"sprite" : "thwomp_trap",
		"solid" : false,
		"visible" : true,
		"depth" : 60,
		"persistent" : false,
		"parent" : "moving_solid",
		"mask" : null,
		},
	"trap_block" : {
		"object_id" : 555,
		"sprite" : "skull_block",
		"solid" : false,
		"visible" : true,
		"depth" : 110,
		"persistent" : false,
		"parent" : "solid",
		"mask" : null,
		}
}
